Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2018-11, with the labels that each got.

#660 Only compile Terraform's versioned files once per run on MM.
  compiler.rb
  coverage/.last_run.json
  products/binaryauthorization/terraform.yaml
  products/compute/ansible.yaml
  products/compute/terraform.yaml
  products/container/ansible.yaml
  products/containeranalysis/terraform.yaml
  products/dns/ansible.yaml
  products/filestore/terraform.yaml
  products/monitoring/terraform.yaml
  products/pubsub/ansible.yaml
  products/redis/terraform.yaml
  products/resourcemanager/terraform.yaml
  products/spanner/ansible.yaml
  products/sql/ansible.yaml
  products/storage/ansible.yaml
  products/storage/terraform.yaml
  provider/ansible/product~compile.yaml
  provider/core.rb
  provider/terraform/common~compile.yaml
  provider/terraform/product~compile.yaml
Labels: automerged, cla: yes, downstream-generated

#622 Moving Ansible to share the same LIST api fields as InSpec
  api/resource.rb
  products/container/ansible.yaml
  products/container/api.yaml
  products/dns/ansible.yaml
  products/dns/api.yaml
  products/pubsub/ansible.yaml
  products/pubsub/api.yaml
  products/spanner/ansible.yaml
  products/spanner/api.yaml
  provider/ansible/facts_override.rb
  templates/ansible/facts.erb
Labels: automerged, cla: yes, downstream-generated

#685 Redo custom code branch
  products/compute/inspec.yaml
  provider/inspec/resource_override.rb
  templates/inspec/singular_resource.erb
  templates/inspec/tests/zones_test.rb
Labels: automerged, cla: yes, downstream-generated

#655 Replace NameValues with KeyValuePairs, Map
  DEVELOPER.md
  api/object.rb
  api/type.rb
  coverage/.last_run.json
  products/bigquery/api.yaml
  products/binaryauthorization/api.yaml
  products/compute/api.yaml
  products/compute/disks.yaml
  products/compute/instance_metadata.yaml
  products/container/node_config.yaml
  products/filestore/api.yaml
  products/redis/api.yaml
  products/resourcemanager/api.yaml
  products/spanner/api.yaml
  provider/ansible.rb
  provider/core.rb
  provider/inspec.rb
  provider/property_override.rb
  provider/resource_overrides.rb
  provider/terraform.rb
  provider/terraform/property_override.rb
  templates/terraform/expand_property_method.erb
  templates/terraform/flatten_property_method.erb
  templates/terraform/nested_property_documentation.erb
  templates/terraform/property_documentation.erb
  templates/terraform/schema_property.erb
Labels: automerged, cla: yes, downstream-generated

#537 Release puppet bundle with version of recent releases.
  .ci/containers/jq/Dockerfile
  .ci/release.yml.tmpl
  .ci/release/create_bundle_manifest.sh
  .ci/release/create_bundle_manifest.yml
  .ci/vars.tmpl
Labels: automerged, cla: yes, downstream-generated

#875 Update README.md
  .ci/README.md
Labels: automerged, cla: yes, downstream-generated

#880 Remove :test_data from core.rb
  api/resource.rb
  products/pubsub/example.yaml
  provider/core.rb
Labels: automerged, cla: yes, downstream-generated

#876 Remove old config.examples field.
  products/pubsub/example.yaml
  products/resourcemanager/ansible.yaml
  provider/config.rb
  provider/core.rb
Labels: automerged, cla: yes, downstream-generated

#671 Validation logic for new overrides
  provider/overrides/resources.rb
  provider/overrides/validator.rb
  spec/compiler_spec.rb
  spec/data/good-file.yaml
  spec/override_validator_spec.rb
Labels: automerged, cla: yes, downstream-generated

#878 Clean up various unused things in core.rb, reorder similar methods.
  TEMPLATE_SDK.md
  provider/core.rb
Labels: automerged, cla: yes, downstream-generated

#908 Uploading vcr cassettes
  .ci/acceptance-tests/inspec-integration.sh
  .ci/ci.yml.tmpl
Labels: automerged, cla: yes, downstream-generated

#914 [Terraform] use shorter beta link in docs instead of long description
  third_party/terraform/website/docs/d/google_container_engine_versions.html.markdown
  third_party/terraform/website/docs/r/compute_backend_service.html.markdown
  third_party/terraform/website/docs/r/compute_global_forwarding_rule.html.markdown
  third_party/terraform/website/docs/r/compute_instance_group_manager.html.markdown
  third_party/terraform/website/docs/r/compute_region_instance_group_manager.html.markdown
  third_party/terraform/website/docs/r/container_cluster.html.markdown
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform

#919 Reset inspec repo
  .ci/magic-modules/generate-inspec.sh
  .ci/unit-tests/inspec.sh
Labels: automerged, cla: yes, downstream-generated

#669 [Terraform]: Start removing beta igm/rigm fields.
  third_party/terraform/resources/resource_compute_instance_group_manager.go.erb
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go.erb
  third_party/terraform/tests/resource_compute_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go.erb
  third_party/terraform/website/docs/r/compute_region_instance_group_manager.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform

#943 Introduction of merged-prs resource
  .ci/ci.yml.tmpl
  .ci/containers/merged-prs-resource/Dockerfile
  .ci/containers/merged-prs-resource/check.py
  .ci/containers/merged-prs-resource/get_downstream_prs.py
  .ci/containers/merged-prs-resource/in.py
  .ci/containers/python/Dockerfile
Labels: automerged, cla: yes, downstream-generated

#946 Bump version of PR resources, add better titles to downstreams.
  .ci/ci.yml.tmpl
  .ci/magic-modules/generate-ansible.sh
  .ci/magic-modules/generate-inspec.sh
  .ci/magic-modules/generate-terraform.sh
Labels: automerged, cla: yes, downstream-generated

#950 Wrap 404 error so it can be detected later, instead of overwriting.
  third_party/terraform/utils/logging_exclusion_billing_account.go
  third_party/terraform/utils/logging_exclusion_folder.go
  third_party/terraform/utils/logging_exclusion_organization.go
  third_party/terraform/utils/logging_exclusion_project.go
Labels: automerged, cla: yes, downstream-generated, terraform

#955 Ensure patches are accurate
  .ci/ci.yml.tmpl
  .ci/containers/merged-prs-resource/check.py
Labels: automerged, cla: yes, downstream-generated

#953 remove editable
  products/compute/ansible.yaml
  products/dns/ansible.yaml
  products/pubsub/ansible.yaml
  provider/ansible/resource_override.rb
Labels: automerged, cla: yes, downstream-generated

#959 Retry all fetches of github PR resource.
  .ci/ci.yml.tmpl
Labels: automerged, cla: yes, downstream-generated

#960 Add new inspec docker image
  .ci/containers/inspec/Dockerfile
  .ci/containers/inspec/Gemfile
  .ci/unit-tests/inspec.yml
Labels: automerged, cla: yes, downstream-generated

#889 api.yaml linter
  Rakefile
  tools/linter/README.md
  tools/linter/discovery.rb
  tools/linter/docs.yaml
  tools/linter/fetcher.rb
  tools/linter/run.rb
  tools/linter/tests.rb
Labels: automerged, cla: yes, downstream-generated

#962 fixing rubocop break because of linter
  tools/linter/discovery.rb
  tools/linter/fetcher.rb
  tools/linter/run.rb
Labels: cla: yes, downstream-generated

#964 We need to pull external revs because the push requires the real git repo.
  .ci/ci.yml.tmpl
Labels: automerged, cla: yes, downstream-generated

#944 Add tutorial
  TUTORIAL.md
Labels: automerged, cla: yes, downstream-generated

#970 Don't log echo
  .ci/acceptance-tests/inspec-integration.sh
  .ci/unit-tests/inspec.sh
Labels: automerged, cla: yes, downstream-generated

#972 Set x not e
  .ci/acceptance-tests/inspec-integration.sh
  .ci/unit-tests/inspec.sh
Labels: automerged, cla: yes, downstream-generated
