Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2018-05, with the labels that each got.

#141 Add more test cases to TestReplaceVars test in Terraform
  templates/terraform/transport_test.go
Labels: downstream-generated

#150 cc PRs to the creator of the original issue.
  .ci/containers/hub/Dockerfile
  .ci/magic-modules/create-pr.sh
Labels: downstream-generated

#149 Label the correct PRs with downstream-generated.
  .ci/ci.yml.tmpl
Labels: downstream-generated

#153 Run rubocop and MM rspec test on every PR using travis
  .rubocop.yml
  .travis.yml
Labels: downstream-generated

#152 Always parse a string fixed64 string to a int64 even on 32 bits platform
  templates/terraform/flatten_property_method.erb
Labels: downstream-generated, terraform

#159 The tests - they pass!
  provider/ansible/documentation.rb
  provider/ansible/module.rb
  provider/ansible/property_override.rb
  provider/ansible/resource_override.rb
  provider/chef.rb
  provider/core.rb
  provider/resource_overrides.rb
  spec/copyright.rb
  spec/copyright_spec.rb
  spec/data/bad-property-reference-config.yaml
  spec/data/chef-config.yaml
  spec/data/good-file-config.yaml
  spec/data/good-resource.yaml
  spec/data/missing-array-property-config.yaml
  spec/data/missing-nested-property-config.yaml
  spec/data/missing-property-config.yaml
  spec/data/puppet-config.yaml
  spec/data/puppet-longuri-config.yaml
  spec/data/puppet-multicode.yaml
  spec/provider_chef_spec.rb
  spec/provider_puppet_spec.rb
  tools/presubmit/README.md
  tools/presubmit/lib/module.rb
  tools/presubmit/lib/test.rb
  tools/presubmit/spec/app_spec.rb
  tools/presubmit/spec/mocked_module.rb
  tools/presubmit/spec/mocked_tests.rb
  tools/presubmit/spec/module_spec.rb
  tools/presubmit/spec/spec_helper.rb
  tools/presubmit/spec/test_spec.rb
Labels: downstream-generated

#146 Ansible: Backend Bucket Fixes
  products/compute/api.yaml
  templates/ansible/resource.erb
Labels: ansible, downstream-generated

#166 Bugfixes to make nested properties work correctly.
  templates/terraform/expand_property_method.erb
  templates/terraform/flatten_property_method.erb
  templates/terraform/schema_property.erb
Labels: downstream-generated

#160 Add a swissknife container to manually test out changes with puppet
  tools/swissknife/CHANGELOG.md
  tools/swissknife/Dockerfile
  tools/swissknife/README.md
  tools/swissknife/docker-entrypoint.sh
Labels: downstream-generated

#158 replace product base_url with versions object
  api/product.rb
  api/resource.rb
  coverage/.last_run.json
  products/compute/api.yaml
  products/container/api.yaml
  products/dns/api.yaml
  products/iam/api.yaml
  products/pubsub/api.yaml
  products/resourcemanager/api.yaml
  products/spanner/api.yaml
  products/sql/api.yaml
  products/storage/api.yaml
  provider/ansible.rb
  provider/core.rb
  provider/terraform.rb
  spec/data/good-export-file.yaml
  spec/data/good-file.yaml
  spec/data/good-longuri.yaml
  spec/data/good-multi-file.yaml
  spec/data/good-multi2-file.yaml
  spec/data/good-single-file.yaml
  spec/data/good-single-readonly-file.yaml
  spec/data/resourceref-missingimports.yaml
  spec/data/resourceref-missingresource.yaml
  spec/product_spec.rb
Labels: downstream-generated

#162 Support excluding properties for all resources
  api/resource.rb
  api/type.rb
  provider/terraform.rb
  provider/terraform/property_override.rb
  templates/terraform/expand_property_method.erb
  templates/terraform/flatten_property_method.erb
  templates/terraform/nested_property_documentation.erb
  templates/terraform/resource.erb
  templates/terraform/resource.html.markdown.erb
  templates/terraform/schema_property.erb
Labels: downstream-generated

#169 Allow overriding excluded property
  api/resource.rb
  api/type.rb
  provider/resource_overrides.rb
Labels: downstream-generated

#163 Create and enable custom code to be injected into templates.
  api/type.rb
  provider/terraform.rb
  provider/terraform/custom_code.rb
  provider/terraform/property_override.rb
  provider/terraform/resource_override.rb
  templates/terraform/expand_property_method.erb
  templates/terraform/flatten_property_method.erb
  templates/terraform/resource.erb
Labels: downstream-generated

#165 Bugfix: non-settable properties like labelFingerprint may need to be sent in updates.
  templates/terraform/resource.erb
Labels: downstream-generated

#190 Add documentation for fields in api/resource.
  api/resource.rb
Labels: downstream-generated

#148 Default values on properties
  api/type.rb
  products/compute/api.yaml
  provider/ansible/documentation.rb
  provider/ansible/module.rb
Labels: downstream-generated

#191 Add liens to Terraform.
  .ci/magic-modules/generate-terraform.sh
  products/resourcemanager/api.yaml
  products/resourcemanager/terraform.yaml
  provider/terraform/import.rb
  provider/terraform/resource_override.rb
  templates/terraform/decoders/avoid_meaningless_project_update.erb
  templates/terraform/post_create/lien.erb
  templates/terraform/post_import/lien_import.erb
  templates/terraform/pre_delete/modify_delete_url.erb
  templates/terraform/provider_gen.erb
  templates/terraform/resource.erb
  templates/terraform/self_link_query.erb
  templates/terraform/transport.go
Labels: downstream-generated

#201 Use the new default value feature in api.yaml in terraform
  products/compute/terraform.yaml
  provider/terraform/property_override.rb
  templates/terraform/schema_property.erb
Labels: downstream-generated

#208 Remove Terraform-specific hack.
  products/resourcemanager/terraform.yaml
  provider/config.rb
  provider/core.rb
  templates/terraform/resource.erb
Labels: downstream-generated

#214 Governance code review.
  GOVERNANCE.md
Labels: downstream-generated

#197 Ansible support on the Magician
  .ci/ci.yml.tmpl
  .ci/magic-modules/create-pr.sh
  .ci/magic-modules/create-pr.yml
  .ci/magic-modules/generate-ansible.sh
  .ci/magic-modules/generate-ansible.yml
  .ci/magic-modules/point-to-submodules.sh
  .ci/magic-modules/point-to-submodules.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: downstream-generated

#222 Ansible CI changes - ansible should run all products
  .ci/magic-modules/generate-ansible.sh
Labels: downstream-generated

#228 Run rspec in parallel for MM tests
  Gemfile
  Gemfile.lock
  spec/data/terraform-config.yaml
  spec/provider_terraform_import_spec.rb
  spec/provider_terraform_spec.rb
  spec/spec_helper.rb
  tasks/rspec.rb
Labels: downstream-generated

#231 25 lines to a method, not 15.
  .rubocop.yml
  api/resource.rb
  provider/ansible.rb
  provider/ansible/documentation.rb
  provider/ansible/example.rb
  provider/ansible/module.rb
  provider/ansible/request.rb
  provider/ansible/resource_override.rb
  provider/ansible/selflink.rb
  provider/chef.rb
  provider/chef/test_catalog.rb
  provider/core.rb
  provider/puppet.rb
  provider/puppet/test_manifest.rb
  provider/terraform/property_override.rb
  provider/test_data/create_data.rb
  provider/test_data/expectations.rb
  provider/test_data/formatter.rb
  provider/test_data/generator.rb
  provider/test_data/property.rb
  provider/test_data/spec_formatter.rb
  spec/network_blocker.rb
  spec/provider_chef_spec.rb
  spec/provider_puppet_spec.rb
Labels: downstream-generated
