Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2019-10, with the labels that each got.

#2407 Fix downstream changelog body replacement
  .ci/magic-modules/pyutils/strutils.py
  .ci/magic-modules/pyutils/strutils_test.py
Labels: automerged, cla: yes, downstream-generated

#2409 Add import support to google_bigtable_instance
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/tests/resource_bigtable_instance_test.go
  third_party/terraform/website/docs/r/bigtable_instance.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2410 release pipeline fix
  .ci/containers/hub/Dockerfile
  .ci/magic-modules/release-ansible.sh
  .ci/magic-modules/release-ansible.yml
  products/compute/ansible.yaml
  products/container/ansible_version_added.yaml
Labels: ansible, automerged, cla: yes, downstream-generated, terraform-provider-google-beta

#2415 Inspec filestore support
  products/filestore/inspec.yaml
  templates/inspec/examples/google_filestore_instance/google_filestore_instance.erb
  templates/inspec/examples/google_filestore_instance/google_filestore_instance_attributes.erb
  templates/inspec/examples/google_filestore_instance/google_filestore_instances.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
Labels: automerged, cla: yes, downstream-generated, inspec, terraform-provider-google-beta

#2403 Delete google_project_services in 3.0.0.
  third_party/terraform/data_sources/data_source_google_project_services.go
  third_party/terraform/resources/resource_cloudiot_registry.go
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/resources/resource_google_project_services.go
  third_party/terraform/tests/data_source_google_project_services_test.go
  third_party/terraform/tests/resource_google_project_services_test.go
  third_party/terraform/tests/resource_storage_bucket_test.go
  third_party/terraform/utils/batcher.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/serviceusage_operation.go
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/d/google_project_services.html.markdown
  third_party/terraform/website/docs/provider_reference.html.markdown
  third_party/terraform/website/docs/r/google_project_service.html.markdown
  third_party/terraform/website/docs/r/google_project_services.html.markdown
Labels: changelog: breaking-change, cla: yes

#2418 fix integration test pipeline
  .ci/acceptance-tests/ansible-integration.sh
Labels: automerged, cla: yes, downstream-generated

#2422 Add InSpec support for runtime config and variable resources
  products/runtimeconfig/api.yaml
  products/runtimeconfig/inspec.yaml
  products/runtimeconfig/terraform.yaml
  templates/inspec/examples/google_runtime_config_config/google_runtime_config_config.erb
  templates/inspec/examples/google_runtime_config_config/google_runtime_config_config_attributes.erb
  templates/inspec/examples/google_runtime_config_config/google_runtime_config_configs.erb
  templates/inspec/examples/google_runtime_config_variable/google_runtime_config_variable.erb
  templates/inspec/examples/google_runtime_config_variable/google_runtime_config_variable_attributes.erb
  templates/inspec/examples/google_runtime_config_variable/google_runtime_config_variables.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
Labels: automerged, cla: yes, downstream-generated, inspec

#2424 Add support for renamed services in google_project_service* resources.
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/resources/resource_google_project_services.go
  third_party/terraform/tests/resource_google_project_service_test.go
  third_party/terraform/tests/resource_google_project_services_test.go
  third_party/terraform/utils/serviceusage_batching.go
  third_party/terraform/utils/utils.go.erb
Labels: automerged, cla: yes, downstream-generated, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#2438 Changing IAM audit config to be authoritative
  third_party/terraform/resources/resource_iam_audit_config.go
  third_party/terraform/utils/iam.go
  third_party/terraform/utils/iam_test.go
Labels: cla: yes

#2431 Update service renames comment
  third_party/terraform/resources/resource_google_project_service.go
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2282 Add validation for scratch disks in Instance Template
  third_party/terraform/resources/resource_compute_instance_template.go
  third_party/terraform/tests/resource_compute_instance_template_test.go
Labels: cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2331 Support for deleting the service upon destrory
  products/appengine/api.yaml
  products/appengine/terraform.yaml
  templates/terraform/custom_delete/appversion_delete.go.erb
  templates/terraform/custom_delete/noop_on_destroy_appengine_version.go.erb
  templates/terraform/examples/app_engine_standard_app_version.tf.erb
Labels: automerged, cla: yes, community, downstream-generated, inspec, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#2461 Change default id format from {{name}} to self_link_uri
  overrides/terraform/resource_override.rb
  products/resourcemanager/terraform.yaml
  provider/terraform.rb
  templates/terraform/iam_policy.go.erb
  templates/terraform/resource.erb
  templates/terraform/resource_iam.html.markdown.erb
Labels: cla: yes

#2443 Implement basepath patches in the provider.
  templates/terraform/custom_expand/compute_full_url.erb
  templates/terraform/custom_expand/self_link_from_name.erb
  third_party/terraform/data_sources/data_source_google_compute_zones.go
  third_party/terraform/resources/resource_compute_instance_group.go
  third_party/terraform/resources/resource_compute_target_pool.go
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_google_project.go
Labels: automerged, cla: yes, downstream-generated, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#2473 Add userinfo.email to default scopes
  third_party/terraform/data_sources/data_source_google_client_openid_userinfo.go
  third_party/terraform/tests/data_source_google_client_openid_userinfo_test.go
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/website/docs/d/datasource_google_client_openid_userinfo.html.markdown
  third_party/terraform/website/docs/provider_reference.html.markdown
Labels: cla: yes

#2471 Set GKE Stackdriver defaults to GKE Stackdriver Monitoring
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#2475 Add support for one-field-at-a-time update to Subnetwork
  api/type.rb
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/iam/helpers/ansible/service_account_key_template.erb
  products/storage/helpers/ansible/object_template.erb
  provider/core.rb
  spec/provider_terraform_spec.rb
  templates/ansible/resource.erb
  templates/terraform/resource.erb
  third_party/terraform/tests/resource_compute_subnetwork_test.go
Labels: ansible, automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2480 Add note about using 2.13.0 in google_project_services deprecation
  third_party/terraform/resources/resource_google_project_services.go
  third_party/terraform/website/docs/version_3_upgrade.html.markdown
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2466 Terraform AppEngine Dispatch Resource
  products/appengine/ansible.yaml
  products/appengine/api.yaml
  products/appengine/inspec.yaml
  products/appengine/terraform.yaml
  templates/terraform/custom_check_destroy/appengine.go.erb
  templates/terraform/examples/app_engine_application_url_dispatch_rules_basic.tf.erb
  third_party/terraform/website-compiled/google.erb
Labels: ansible, cla: yes, community, downstream-generated, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#2491 Fix some TF diff issues in MM 3.0.0 branch.
  .ci/ci.yml.tmpl
  .ci/magic-modules/diff-terraform.sh
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated

#2495 only allow instance templates with 375gb scratch disks
  third_party/terraform/resources/resource_compute_instance_template.go
  third_party/terraform/tests/resource_compute_instance_template_test.go
  third_party/terraform/utils/test_utils.go
  third_party/terraform/utils/utils.go.erb
Labels: cla: yes

#2501 Update cloudfunction id for 3.0.0 release
  third_party/terraform/data_sources/data_source_google_cloudfunctions_function.go
  third_party/terraform/resources/resource_cloudfunctions_function.go
Labels: cla: yes

#2499 handle cloudfunctions deprecating nodejs6
  templates/inspec/tests/integration/build/gcp-mm.tf
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
  third_party/terraform/website/docs/r/cloudfunctions_function.html.markdown
  third_party/terraform/website/docs/version_3_upgrade.html.markdown
Labels: cla: yes

#2502 Handwritten id updates for several compute resources
  third_party/terraform/resources/resource_composer_environment.go.erb
  third_party/terraform/resources/resource_compute_attached_disk.go
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/resources/resource_compute_instance_from_template.go
  third_party/terraform/resources/resource_compute_instance_group.go
  third_party/terraform/resources/resource_compute_instance_group_manager.go.erb
  third_party/terraform/resources/resource_compute_instance_template.go
  third_party/terraform/tests/resource_compute_attached_disk_test.go
  third_party/terraform/tests/resource_compute_instance_template_test.go
  third_party/terraform/tests/resource_compute_instance_test.go
  third_party/terraform/website/docs/r/compute_attached_disk.html.markdown
  third_party/terraform/website/docs/r/compute_instance_group.html.markdown
  third_party/terraform/website/docs/r/compute_instance_group_manager.html.markdown
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
Labels: cla: yes

#2497 Added support for GCS IAM policies
  provider/terraform_object_library.rb
  third_party/validator/storage_bucket_iam.go
Labels: automerged, cla: yes, community, downstream-generated, terraform-google-conversion

#2524 Add templates for the changelog generator.
  .ci/changelog.tmpl
  .ci/release-note.tmpl
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated

#2542 Fix gofmt diff in Cloud Functions
  third_party/terraform/resources/resource_cloudfunctions_function.go
Labels: changelog: no-release-note, cla: yes

#2527 More handwritten ids
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go.erb
  third_party/terraform/resources/resource_compute_security_policy.go
  third_party/terraform/resources/resource_compute_target_pool.go
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_container_node_pool.go.erb
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_security_policy_test.go
  third_party/terraform/tests/resource_compute_target_pool_test.go
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/compute_security_policy.html.markdown
  third_party/terraform/website/docs/r/compute_target_pool.html.markdown
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#2535 Clarify fields that are regexes in docs.
  products/cloudbuild/api.yaml
Labels: ansible, automerged, changelog: no-release-note, cla: yes, downstream-generated, inspec, terraform-provider-google, terraform-provider-google-beta

#2550 fix container cluster
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: changelog: no-release-note, cla: yes

#2544 Datasource id updates
  third_party/terraform/data_sources/data_source_compute_network_endpoint_group.go
  third_party/terraform/data_sources/data_source_dns_managed_zone.go
  third_party/terraform/data_sources/data_source_google_compute_address.go
  third_party/terraform/data_sources/data_source_google_compute_backend_service.go
  third_party/terraform/data_sources/data_source_google_compute_forwarding_rule.go
  third_party/terraform/data_sources/data_source_google_compute_global_address.go
  third_party/terraform/data_sources/data_source_google_compute_instance.go
  third_party/terraform/data_sources/data_source_google_compute_instance_group.go
  third_party/terraform/data_sources/data_source_google_compute_network.go
  third_party/terraform/data_sources/data_source_google_compute_region_instance_group.go
  third_party/terraform/data_sources/data_source_google_compute_resource_policy.go.erb
  third_party/terraform/data_sources/data_source_google_compute_ssl_certificate.go
  third_party/terraform/data_sources/data_source_google_compute_ssl_policy.go
  third_party/terraform/data_sources/data_source_google_compute_subnetwork.go
  third_party/terraform/data_sources/data_source_google_compute_vpn_gateway.go
  third_party/terraform/data_sources/data_source_google_container_cluster.go
  third_party/terraform/data_sources/data_source_google_organization.go
  third_party/terraform/data_sources/data_source_google_project.go
Labels: cla: yes

#2540 Even more handwritten ids
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/resources/resource_dataproc_job.go
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/resources/resource_sql_database_instance.go
  third_party/terraform/resources/resource_sql_ssl_cert.go
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
  third_party/terraform/tests/resource_dataproc_job_test.go
  third_party/terraform/tests/resource_google_project_test.go
Labels: cla: yes

#2519 changes for spanner Insatnce and database
  products/spanner/inspec.yaml
  templates/inspec/examples/google_spanner_database/google_spanner_database.erb
  templates/inspec/examples/google_spanner_database/google_spanner_database_attributes.erb
  templates/inspec/examples/google_spanner_database/google_spanner_databases.erb
  templates/inspec/examples/google_spanner_instance/google_spanner_instance.erb
  templates/inspec/examples/google_spanner_instance/google_spanner_instance_attributes.erb
  templates/inspec/examples/google_spanner_instance/google_spanner_instances.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
Labels: automerged, cla: yes, community, downstream-generated, inspec

#2558 Add back encoder that always sends autoCreateSubnetworks
  products/compute/terraform.yaml
  templates/terraform/encoders/network.erb
Labels: cla: yes

#2537 Allow defining empty taint, remove old DSF
  third_party/terraform/utils/node_config.go.erb
Labels: cla: yes

#2559 Remove encoder, can be done as send_empty_value on autoCreateSubnetworks
  products/compute/terraform.yaml
  templates/terraform/encoders/network.erb
Labels: cla: yes

#2555 Fix nil reference to ShieldedNodes
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: automerged, cla: yes, community, downstream-generated, terraform-provider-google-beta

#2566 Add iamMember to bigquery dataset access
  products/bigquery/ansible.yaml
  products/bigquery/api.yaml
  products/bigquery/terraform.yaml
  templates/inspec/examples/google_bigquery_dataset/google_bigquery_datasets.erb
Labels: automerged, cla: yes, downstream-generated, inspec
