Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2019-11, with the labels that each got.

#2573 deprecate 0.11 syntax in docs (datasources)
  third_party/terraform/tests/data_source_compute_lb_ip_ranges_test.go
  third_party/terraform/tests/data_source_dns_managed_zone_test.go
  third_party/terraform/tests/data_source_google_active_folder_test.go
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/d/datasource_client_config.html.markdown
  third_party/terraform/website/docs/d/datasource_compute_address.html.markdown
  third_party/terraform/website/docs/d/datasource_compute_global_address.html.markdown
  third_party/terraform/website/docs/d/datasource_compute_image.html.markdown
  third_party/terraform/website/docs/d/datasource_compute_instance.html.markdown
  third_party/terraform/website/docs/d/datasource_compute_lb_ip_ranges.html.markdown
  third_party/terraform/website/docs/d/datasource_compute_region_instance_group.html.markdown
  third_party/terraform/website/docs/d/datasource_compute_ssl_certificate.html.markdown
  third_party/terraform/website/docs/d/datasource_compute_ssl_policy.html.markdown
  third_party/terraform/website/docs/d/datasource_google_client_openid_userinfo.html.markdown
  third_party/terraform/website/docs/d/datasource_google_composer_image_versions.html.markdown
  third_party/terraform/website/docs/d/datasource_google_compute_backend_service.html.markdown
  third_party/terraform/website/docs/d/datasource_google_compute_network_endpoint_group.html.markdown
  third_party/terraform/website/docs/d/datasource_google_folder_organization_policy.html.markdown
  third_party/terraform/website/docs/d/datasource_google_iam_role.html.markdown
  third_party/terraform/website/docs/d/datasource_google_netblock_ip_ranges.html.markdown
  third_party/terraform/website/docs/d/datasource_google_project_organization_policy.html.markdown
  third_party/terraform/website/docs/d/datasource_google_service_account.html.markdown
  third_party/terraform/website/docs/d/datasource_google_service_account_access_token.html.markdown
  third_party/terraform/website/docs/d/datasource_google_service_account_key.html.markdown
  third_party/terraform/website/docs/d/datasource_tpu_tensorflow_versions.html.markdown
  third_party/terraform/website/docs/d/dns_managed_zone.html.markdown
  third_party/terraform/website/docs/d/google_active_folder.html.markdown
  third_party/terraform/website/docs/d/google_billing_account.html.markdown
  third_party/terraform/website/docs/d/google_compute_default_service_account.html.markdown
  third_party/terraform/website/docs/d/google_compute_node_types.html.markdown
  third_party/terraform/website/docs/d/google_compute_regions.html.markdown
  third_party/terraform/website/docs/d/google_compute_resource_policy.html.markdown
  third_party/terraform/website/docs/d/google_compute_zones.html.markdown
  third_party/terraform/website/docs/d/google_container_cluster.html.markdown
  third_party/terraform/website/docs/d/google_container_engine_versions.html.markdown
  third_party/terraform/website/docs/d/google_container_registry_image.html.markdown
  third_party/terraform/website/docs/d/google_container_registry_repository.html.markdown
  third_party/terraform/website/docs/d/google_folder.html.markdown
  third_party/terraform/website/docs/d/google_kms_crypto_key.html.markdown
  third_party/terraform/website/docs/d/google_kms_crypto_key_version.html.markdown
  third_party/terraform/website/docs/d/google_kms_secret.html.markdown
  third_party/terraform/website/docs/d/google_kms_secret_ciphertext.html.markdown
  third_party/terraform/website/docs/d/google_organization.html.markdown
  third_party/terraform/website/docs/d/google_project.html.markdown
  third_party/terraform/website/docs/d/google_projects.html.markdown
  third_party/terraform/website/docs/d/google_storage_project_service_account.html.markdown
  third_party/terraform/website/docs/d/google_storage_transfer_project_service_account.html.markdown
  third_party/terraform/website/docs/d/signed_url.html.markdown
Labels: cla: yes

#2577 Add InSpec support for cloud scheduler job
  products/cloudscheduler/inspec.yaml
  templates/inspec/examples/google_cloud_scheduler_job/google_cloud_scheduler_job.erb
  templates/inspec/examples/google_cloud_scheduler_job/google_cloud_scheduler_job_attributes.erb
  templates/inspec/examples/google_cloud_scheduler_job/google_cloud_scheduler_jobs.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
Labels: automerged, cla: yes, downstream-generated, inspec

#2580 Convert tests to import style
  third_party/terraform/tests/resource_compute_network_endpoint_test.go.erb
  third_party/terraform/tests/resource_compute_region_autoscaler_test.go.erb
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_route_test.go
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2561 remove long name behavior for pubsub subscriptions, clean up custom expanders
  products/binaryauthorization/terraform.yaml
  products/cloudscheduler/terraform.yaml
  products/compute/terraform.yaml
  products/pubsub/terraform.yaml
  products/redis/terraform.yaml
  products/sourcerepo/terraform.yaml
  provider/terraform/sub_template.rb
  templates/terraform/custom_expand/binaryauthorization_attestor_name.erb
  templates/terraform/custom_expand/cloudscheduler_job_name.erb
  templates/terraform/custom_expand/computed_subscription_name.erb
  templates/terraform/custom_expand/monitoring_group_name.erb
  templates/terraform/custom_expand/redis_instance_name.erb
  templates/terraform/custom_expand/repository_name_from_short_name.go.erb
  templates/terraform/custom_expand/route_gateway.erb
  templates/terraform/custom_expand/shortname_to_url.go.erb
  templates/terraform/custom_expand/spanner_instance_config.go
  templates/terraform/custom_expand/url_map_only_set_string.go.erb
  templates/terraform/expand_property_method.erb
  templates/terraform/objectlib/base.go.erb
  templates/terraform/resource.erb
  third_party/terraform/tests/resource_pubsub_subscription_test.go
  third_party/terraform/utils/pubsub_utils.go
Labels: cla: yes

#2583 Update IGM/RIGM tests to use version
  templates/terraform/examples/autoscaler_basic.tf.erb
  templates/terraform/examples/backend_service_signed_url_key.tf.erb
  templates/terraform/examples/region_autoscaler_basic.tf.erb
Labels: automerged, cla: yes, downstream-generated

#2591 Use default instance timeout on direct operation wait
  third_party/terraform/tests/resource_compute_instance_test.go
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2602 Remove unused regexes from rigm
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go.erb
Labels: cla: yes

#2600 Fix missing paren + bad var in resourcepolicy datasource 3.0.0
  third_party/terraform/data_sources/data_source_google_compute_resource_policy.go.erb
Labels: cla: yes

#2605 Test fixes based on integration tests, id formats + other easy fixes
  templates/terraform/post_create/cloudbuild_trigger_id.go.erb
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/tests/data_source_google_cloudfunctions_function_test.go
  third_party/terraform/tests/data_source_google_organization_test.go
  third_party/terraform/tests/resource_compute_disk_test.go.erb
  third_party/terraform/tests/resource_compute_http_health_check_test.go
  third_party/terraform/tests/resource_compute_image_test.go
  third_party/terraform/tests/resource_compute_instance_from_template_test.go
  third_party/terraform/tests/resource_compute_network_test.go
  third_party/terraform/tests/resource_compute_region_disk_test.go
Labels: cla: yes

#2597 Update subnetwork to remove enable_flow_logs and depend on log_config
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/constants/subnetwork.erb
  templates/terraform/custom_expand/subnetwork_log_config.go.erb
  templates/terraform/extra_schema_entry/subnetwork.erb
  third_party/terraform/tests/resource_compute_subnetwork_test.go
Labels: cla: yes

#2609 Test updates to not depend on id format. Also test fixes
  third_party/terraform/tests/resource_compute_ssl_certificate_test.go
  third_party/terraform/tests/resource_compute_ssl_policy_test.go
  third_party/terraform/tests/resource_compute_target_http_proxy_test.go
  third_party/terraform/tests/resource_compute_target_https_proxy_test.go
  third_party/terraform/tests/resource_compute_url_map_test.go
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
Labels: cla: yes

#2608 Update hand-written resources with `AtLeastOneOf` and `ExactlyOneOf` attributes
  products/appengine/api.yaml
  products/bigtable/api.yaml
  products/cloudbuild/api.yaml
  products/cloudrun/api.yaml
  products/cloudscheduler/api.yaml
  products/compute/terraform.yaml
  products/dns/api.yaml
  products/monitoring/api.yaml
  third_party/terraform/resources/resource_app_engine_application.go
  third_party/terraform/resources/resource_bigquery_table.go.erb
  third_party/terraform/resources/resource_cloudiot_registry.go
  third_party/terraform/resources/resource_composer_environment.go.erb
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/resources/resource_compute_instance_group_manager.go.erb
  third_party/terraform/resources/resource_compute_instance_template.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go.erb
  third_party/terraform/resources/resource_compute_router_peer.go
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/resources/resource_dataproc_job.go
  third_party/terraform/resources/resource_google_organization_policy.go
  third_party/terraform/resources/resource_sql_database_instance.go
  third_party/terraform/resources/resource_storage_bucket.go
  third_party/terraform/resources/resource_storage_transfer_job.go
  third_party/terraform/tests/resource_dataproc_job_test.go
  third_party/terraform/tests/resource_storage_bucket_test.go
  third_party/terraform/utils/utils.go.erb
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: cla: yes

#2614 Magician shouldn't delete handwritten Ansible module
  .ci/magic-modules/generate-ansible.sh
Labels: automerged, cla: yes, downstream-generated

#2619 fix imports
  third_party/terraform/resources/resource_compute_instance_group_manager.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
Labels: cla: yes

#2615 Remove automatic subnetwork creation in GKE
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#2617 More integration test fixes
  products/accesscontextmanager/terraform.yaml
  third_party/terraform/resources/resource_bigtable_table.go
  third_party/terraform/resources/resource_cloudiot_registry.go
  third_party/terraform/tests/resource_compute_instance_template_test.go
  third_party/terraform/tests/resource_compute_target_pool_test.go
  third_party/terraform/tests/resource_compute_target_ssl_proxy_test.go
  third_party/terraform/tests/resource_compute_target_tcp_proxy_test.go
Labels: cla: yes

#2623 (r)igm imports for customdiff
  third_party/terraform/resources/resource_compute_instance_group_manager.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
Labels: cla: yes

#2624 Fix IGM custom diff and reuse method between resources
  third_party/terraform/resources/resource_compute_instance_group_manager.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
Labels: cla: yes

#2620 Forwardingrule ip address
  products/compute/terraform.yaml
  third_party/terraform/utils/validation.go
Labels: cla: yes

#2625 Remove unused sort import from rigm
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
Labels: changelog: no-release-note, cla: yes

#2631 add composer test fixes, backend bucket signed url key
  third_party/terraform/resources/resource_composer_environment.go.erb
  third_party/terraform/tests/resource_composer_environment_test.go.erb
  third_party/terraform/tests/resource_compute_backend_bucket_signed_url_key_test.go
Labels: cla: yes

#2626 Stop users from specifying bigquery-json in 3.0.0
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/tests/resource_google_project_service_test.go
Labels: cla: yes

#2630 Add import support to google_bigtable_table
  third_party/terraform/resources/resource_bigtable_table.go
  third_party/terraform/tests/resource_bigtable_table_test.go
  third_party/terraform/website/docs/r/bigtable_table.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2635 Send null logConfig if subnetwork is L7ILB
  products/compute/api.yaml
  templates/terraform/custom_expand/subnetwork_log_config.go.erb
Labels: cla: yes

#2593 deprecate 0.11 syntax in tests (datasources)
  third_party/terraform/tests/data_source_container_registry_test.go
  third_party/terraform/tests/data_source_google_billing_account_test.go
  third_party/terraform/tests/data_source_google_cloudfunctions_function_test.go
  third_party/terraform/tests/data_source_google_compute_address_test.go
  third_party/terraform/tests/data_source_google_compute_backend_service_test.go
  third_party/terraform/tests/data_source_google_compute_forwarding_rule_test.go
  third_party/terraform/tests/data_source_google_compute_global_address_test.go
  third_party/terraform/tests/data_source_google_compute_image_test.go
  third_party/terraform/tests/data_source_google_compute_instance_group_test.go.erb
  third_party/terraform/tests/data_source_google_compute_instance_test.go
  third_party/terraform/tests/data_source_google_compute_network_test.go
  third_party/terraform/tests/data_source_google_compute_region_instance_group_test.go.erb
  third_party/terraform/tests/data_source_google_compute_ssl_certificate_test.go
  third_party/terraform/tests/data_source_google_compute_ssl_policy_test.go
  third_party/terraform/tests/data_source_google_compute_subnetwork_test.go
  third_party/terraform/tests/data_source_google_compute_vpn_gateway_test.go
  third_party/terraform/tests/data_source_google_container_cluster_test.go
  third_party/terraform/tests/data_source_google_folder_organization_policy_test.go
  third_party/terraform/tests/data_source_google_folder_test.go
  third_party/terraform/tests/data_source_google_iam_role_test.go
  third_party/terraform/tests/data_source_google_kms_crypto_key_test.go
  third_party/terraform/tests/data_source_google_kms_crypto_key_version_test.go
  third_party/terraform/tests/data_source_google_kms_key_ring_test.go
  third_party/terraform/tests/data_source_google_kms_secret_ciphertext_test.go
  third_party/terraform/tests/data_source_google_kms_secret_test.go
  third_party/terraform/tests/data_source_google_organization_test.go
  third_party/terraform/tests/data_source_google_project_organization_policy_test.go
  third_party/terraform/tests/data_source_google_project_test.go
  third_party/terraform/tests/data_source_google_service_account_access_token_test.go
  third_party/terraform/tests/data_source_google_service_account_key_test.go
  third_party/terraform/tests/data_source_google_service_account_test.go
  third_party/terraform/tests/data_source_storage_object_signed_url_test.go
Labels: cla: yes

#2642 Make master_authorized_networks_config.cidr_blocks Optional in GKE
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: changelog: no-release-note, cla: yes

#2639 update magic module-generated resources with at_least_one_of
  api/type.rb
  overrides/terraform/property_override.rb
  products/accesscontextmanager/api.yaml
  products/appengine/api.yaml
  products/cloudrun/api.yaml
  products/cloudscheduler/api.yaml
  products/compute/api.yaml
  products/dataproc/api.yaml
  products/dns/api.yaml
  products/healthcare/api.yaml
  products/logging/api.yaml
  products/mlengine/api.yaml
  products/monitoring/api.yaml
  products/pubsub/api.yaml
  products/securityscanner/api.yaml
  products/tpu/api.yaml
  templates/terraform/examples/backend_service_traffic_director_ring_hash.tf.erb
  templates/terraform/examples/backend_service_traffic_director_round_robin.tf.erb
  templates/terraform/examples/region_backend_service_ilb_ring_hash.tf.erb
  templates/terraform/examples/region_backend_service_ilb_round_robin.tf.erb
  templates/terraform/examples/region_ssl_certificate_target_https_proxies.tf.erb
  templates/terraform/examples/region_target_http_proxy_basic.tf.erb
  templates/terraform/examples/region_target_https_proxy_basic.tf.erb
  templates/terraform/schema_property.erb
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/tests/resource_compute_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_health_check_test.go
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_region_health_check_test.go.erb
  third_party/terraform/tests/resource_compute_region_target_http_proxy_test.go.erb
  third_party/terraform/tests/resource_compute_region_target_https_proxy_test.go.erb
  third_party/terraform/tests/resource_compute_region_url_map_test.go.erb
  third_party/terraform/tests/resource_pubsub_subscription_test.go
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: cla: yes

#2656 Add note on id format changes
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: cla: yes

#2653 Add upgrade guide for subnetwork log_config
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: cla: yes

#2658 Add note on audit log config
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: cla: yes

#2657 Add misc entries to the upgrade guide
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: changelog: no-release-note, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2659 add info on scratch disk size and remove duplicate kms_key_self_link section
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: changelog: no-release-note, cla: yes

#2663 Add upgrade guide notes.
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: changelog: no-release-note, cla: yes

#2666 Add upgrade guide for forwarding rule validation
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: changelog: no-release-note, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2638 Convert old import formats (using non-/) to use /.
  third_party/terraform/data_sources/data_source_google_folder_organization_policy.go
  third_party/terraform/resources/resource_google_folder_organization_policy.go
  third_party/terraform/resources/resource_google_organization_policy.go
  third_party/terraform/website/docs/r/bigquery_table.html.markdown
  third_party/terraform/website/docs/r/google_folder_organization_policy.html.markdown
  third_party/terraform/website/docs/r/google_organization_policy.html.markdown
Labels: cla: yes

#2668 Upgrade proofreading
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: changelog: no-release-note, cla: yes

#2670 Password is not actually required.
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: changelog: no-release-note, cla: yes

#2664 Improve docs for private_cluster_config
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2671 Add improved for_each non-module variant to project service upgrade guide
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: changelog: no-release-note, cla: yes

#2673 Update bigtable import & tests to 3.0
  third_party/terraform/resources/resource_bigtable_table.go
  third_party/terraform/tests/resource_bigtable_table_test.go
Labels: cla: yes

#2665 update upgrade guide
  products/accesscontextmanager/api.yaml
  products/appengine/api.yaml
  products/bigquery/api.yaml
  products/bigtable/api.yaml
  products/binaryauthorization/api.yaml
  products/cloudbuild/api.yaml
  products/cloudfunctions/api.yaml
  products/cloudrun/api.yaml
  products/cloudscheduler/api.yaml
  products/compute/api.yaml
  products/dns/api.yaml
  products/firestore/api.yaml
  products/monitoring/api.yaml
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/resources/resource_compute_instance_group_manager.go
  third_party/terraform/resources/resource_compute_instance_template.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
  third_party/terraform/resources/resource_storage_bucket.go
  third_party/terraform/utils/utils.go.erb
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: cla: yes

#2674 update formatting for upgrade doc
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: changelog: no-release-note, cla: yes

#2667 Add rigm to upgrade guide
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
  third_party/terraform/website/docs/r/compute_instance_group_manager.html.markdown
  third_party/terraform/website/docs/r/compute_region_instance_group_manager.html.markdown
Labels: cla: yes

#2688 remove unused variable for compute instance lint
  third_party/terraform/resources/resource_compute_instance.go
Labels: ansible, automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2685 Fix Ansible spurious diffs
  provider/ansible/documentation.rb
  provider/ansible/gcp_utils.py
Labels: automerged, cla: yes, downstream-generated

#2706 Change removed update_strategy to computed
  third_party/terraform/resources/resource_compute_instance_group_manager.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
Labels: automerged, cla: yes, downstream-generated, terraform-3.0, terraform-provider-google, terraform-provider-google-beta

#2691 Bump GKE timeouts
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_container_node_pool.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: ansible, automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2712 Use name, not id to fetch dns managed zone datasource
  third_party/terraform/data_sources/data_source_dns_managed_zone.go
Labels: automerged, cla: yes, downstream-generated, terraform-3.0, terraform-provider-google, terraform-provider-google-beta

#2715 Default min instances to 0 for secondary worker config
  products/dataproc/api.yaml
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google-beta

#2736 Dataproc autoscaling ga
  products/dataproc/api.yaml
  products/dataproc/terraform.yaml
  templates/terraform/examples/dataproc_autoscaling_policy.tf.erb
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/website-compiled/google.erb
Labels: automerged, cla: yes, downstream-generated, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#2732 non-NIC0 ILB support
  products/compute/api.yaml
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
Labels: automerged, cla: yes, downstream-generated, enhancement, terraform-provider-google-beta
