Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2019-04, with the labels that each got.

#1601 Turn `go mod vendor` back on in the Magician
  .ci/magic-modules/generate-terraform.sh
Labels: automerged, cla: yes, downstream-generated, terraform-google-conversion

#1621 Linter stuff
  tools/linter/README.md
  tools/linter/discovery.rb
  tools/linter/docs.yaml
  tools/linter/run.rb
  tools/linter/tests/test_runner.rb
Labels: automerged, cla: yes, downstream-generated

#1622 Add support for aliasing resource names.
  tools/linter/README.md
  tools/linter/discovery.rb
  tools/linter/docs.yaml
  tools/linter/tests/test_runner.rb
Labels: automerged, cla: yes, downstream-generated

#1618 moving coverage dashboard to nightly
  .ci/release.yml.tmpl
Labels: automerged, cla: yes, downstream-generated

#1605 Provider Generation Refactor
  provider/ansible.rb
  provider/core.rb
  provider/inspec.rb
  provider/terraform.rb
  provider/terraform_example.rb
  provider/terraform_object_library.rb
  templates/terraform/examples/base_configs/test_file.go.erb
Labels: automerged, cla: yes, downstream-generated

#1640 Remove manifest config
  products/bigquery/ansible.yaml
  products/bigquery/inspec.yaml
  products/cloudbuild/ansible.yaml
  products/cloudbuild/inspec.yaml
  products/cloudfunctions/inspec.yaml
  products/compute/ansible.yaml
  products/compute/inspec.yaml
  products/container/ansible.yaml
  products/container/inspec.yaml
  products/dns/ansible.yaml
  products/dns/inspec.yaml
  products/iam/ansible.yaml
  products/pubsub/ansible.yaml
  products/pubsub/inspec.yaml
  products/redis/ansible.yaml
  products/resourcemanager/ansible.yaml
  products/resourcemanager/inspec.yaml
  products/sourcerepo/ansible.yaml
  products/sourcerepo/inspec.yaml
  products/spanner/ansible.yaml
  products/sql/ansible.yaml
  products/storage/ansible.yaml
  provider/ansible.rb
  provider/ansible/config.rb
  provider/ansible/documentation.rb
  provider/ansible/example.rb
  provider/ansible/manifest.rb
  provider/ansible/resourceref.rb
  provider/core.rb
  provider/inspec.rb
  provider/inspec/manifest.rb
  templates/ansible/documentation.erb
  templates/ansible/facts.erb
Labels: automerged, cla: yes, downstream-generated

#1642 Fix API Linter Spreadsheet
  .ci/magic-modules/coverage-spreadsheet-upload.sh
  tools/linter/spreadsheet.rb
Labels: automerged, cla: yes, downstream-generated

#1648 Add back `|| true` to spreadsheet script
  .ci/magic-modules/coverage-spreadsheet-upload.sh
Labels: automerged, cla: yes, downstream-generated

#1646 Remove unused methods
  provider/ansible.rb
  provider/core.rb
  provider/inspec.rb
Labels: automerged, cla: yes, downstream-generated

#1647 Don't allow secondary ip ranges to be computed in subnetwork
  products/compute/terraform.yaml
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1651 Hard remove broken Removed fields, fix 0.12 configs
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/resources/resource_compute_instance_from_template.go
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/tests/resource_dataflow_job_test.go
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1653 Push provider specific info into provider specific FileTemplate objects
  provider/ansible.rb
  provider/core.rb
  provider/terraform.rb
Labels: automerged, cla: yes, downstream-generated

#1655 inlining storage, container, sql api.yaml
  products/container/api.yaml
  products/container/async.yaml
  products/container/node_config.yaml
  products/sql/api.yaml
  products/storage/api.yaml
  products/storage/bucket_access_control.yaml
  products/storage/object_access_control.yaml
Labels: automerged, cla: yes, downstream-generated

#1662 0.12 Computed+Optional Attr syntax fixes
  third_party/terraform/tests/resource_compute_instance_from_template_test.go
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/utils/node_config.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1674 Removing ability to use compilation logic in api.yaml
  api/compiler.rb
  spec/compiler_spec.rb
Labels: automerged, cla: yes, downstream-generated

#1676 Add support for network endpoint groups
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/network_endpoint_group.tf.erb
  third_party/terraform/website-compiled/google.erb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1678 Remove confusing truthy methods
  provider/core.rb
  templates/ansible/resource.erb
Labels: automerged, cla: yes, downstream-generated

#1679 Remove unused configs in provider core
  provider/ansible.rb
  provider/core.rb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google

#1680 Remove unused requires and type properties
  api/type.rb
  provider/inspec.rb
Labels: automerged, cla: yes, downstream-generated

#1681 Remove unused utils and tests
  google/hash_utils.rb
  google/integer_utils.rb
  google/ruby_utils.rb
  provider/core.rb
  provider/inspec.rb
  spec/data/missing-array-property-config.yaml
  spec/data/missing-nested-property-config.yaml
  spec/data/missing-property-config.yaml
  spec/data/network_spec_template.erb
  spec/data/prov_spec_template.erb
  spec/data/prov_template.erb
  spec/data/recipe_template.erb
  spec/data/type_template.erb
  spec/hash_utils_spec.rb
  spec/integer_utils_spec.rb
Labels: automerged, cla: yes, downstream-generated

#1694 Don't vendor in Terraform
  .ci/magic-modules/generate-terraform.sh
Labels: automerged, cla: yes, downstream-generated

#1696 Moving Async to Product-level
  api/async.rb
  api/product.rb
  api/resource.rb
  overrides/terraform/resource_override.rb
  products/accesscontextmanager/api.yaml
  products/accesscontextmanager/terraform.yaml
  products/compute/terraform.yaml
  products/container/api.yaml
  products/filestore/api.yaml
  products/filestore/terraform.yaml
  products/firestore/api.yaml
  products/firestore/terraform.yaml
  products/redis/api.yaml
  products/redis/terraform.yaml
  products/resourcemanager/api.yaml
  products/sql/api.yaml
  products/tpu/api.yaml
  products/tpu/terraform.yaml
  provider/terraform.rb
  templates/terraform/resource.erb
  templates/terraform/resource.html.markdown.erb
Labels: ansible, automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta
