Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2019-05, with the labels that each got.

#1737 Revert "Revert "Do not read or flatten url_param_only properties in Terraform""
  api/resource.rb
  templates/terraform/resource.erb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1738 fix TestAccContainerCluster_errorCleanDanglingCluster
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1731 Better debugging output for bad api.yaml values
  api/product.rb
  api/resource.rb
  api/type.rb
  google/yaml_validator.rb
  overrides/validator.rb
  spec/override_validator_spec.rb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1746 Adding debug info to the community PR responder
  .ci/magic-modules/welcome-contributor.sh
Labels: automerged, cla: yes, downstream-generated

#1765 Add HTTP2 protocol to backend service
  products/compute/api.yaml
Labels: ansible, automerged, cla: yes, downstream-generated, inspec, terraform-provider-google, terraform-provider-google-beta

#1773 Flatten all base urls in MM proper
  api/resource.rb
  products/dns/api.yaml
  provider/ansible.rb
  provider/core.rb
  provider/terraform.rb
  spec/provider_terraform_spec.rb
  templates/ansible/async.erb
  templates/inspec/iam_policy/iam_policy.erb
  templates/inspec/iam_policy/iam_policy.md.erb
  templates/inspec/plural_resource.erb
  templates/inspec/singular_resource.erb
  templates/terraform/examples/base_configs/test_file.go.erb
  templates/terraform/operation.go.erb
  templates/terraform/post_create/labels.erb
  templates/terraform/resource.erb
Labels: automerged, cla: yes, downstream-generated

#1777 fix closing quote
  .ci/magic-modules/welcome-contributor.sh
Labels: automerged, cla: yes, downstream-generated

#1778 Add new line before project doc bullet
  templates/terraform/resource.html.markdown.erb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1710 Run MM tests in parallel to create-prs
  .ci/ci.yml.tmpl
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1722 Fixes nat subnetwork reference in docs
  third_party/terraform/website/docs/r/compute_router_nat.html.markdown
Labels: automerged, cla: no, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1771 Improve to_json output
  api/resource.rb
  api/type.rb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1784 Refactor expander method template
  templates/terraform/expand_property_method.erb
Labels: automerged, cla: yes, downstream-generated

#1782 Refactor Api::Resource
  api/resource.rb
  api/resource/iam_policy.rb
  api/resource/nested_query.rb
  api/resource/reference_links.rb
  api/resource/response_list.rb
Labels: automerged, cla: yes, downstream-generated

#1788 Add documentation for resource.rb fields
  api/resource.rb
Labels: automerged, cla: yes, downstream-generated

#1796 Update storage_transfer_job.html.markdown
  third_party/terraform/website/docs/r/storage_transfer_job.html.markdown
Labels: automerged, cla: no, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1785 Diff suppress storage transfer job start_time_of_day
  third_party/terraform/resources/resource_storage_transfer_job.go
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1716 [terraform-beta] adding AUTH_NONE to enums for istio addon_config
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google-beta

#1815 rename terraformExample to disambiguate from generated tests
  compiler.rb
  provider/terraform_object_library.rb
  provider/terraform_oics.rb
Labels: automerged, cla: yes, downstream-generated

#1822 Split Terraform custom code objects to multiple files
  overrides/terraform/resource_override.rb
  provider/terraform.rb
  provider/terraform/custom_code.rb
  provider/terraform/docs.rb
  provider/terraform/examples.rb
Labels: automerged, cla: yes, downstream-generated

#1824 Remove appengine location validation
  third_party/terraform/resources/resource_app_engine_application.go
Labels: automerged, cla: no, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1814 Fix OiCS example generation
  provider/terraform.rb
Labels: automerged, cla: yes, downstream-generated

#1767 Update Magician deployment instructions
  .ci/README.md
Labels: automerged, cla: yes, downstream-generated

#1828 Move rubocop to inspec unit test
  .ci/unit-tests/inspec.sh
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google-beta

#1834 rubocop the vcr_config
  templates/inspec/vcr_config.rb
Labels: automerged, cla: yes, downstream-generated

#1770 Don't split on base urls, self links
  api/resource.rb
  products/dns/api.yaml
  products/filestore/api.yaml
  products/sql/api.yaml
Labels: ansible, automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1844 Fix GKE examples
  third_party/terraform/website/docs/r/container_cluster.html.markdown
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1809 Delete handwritten GFR docs
  third_party/terraform/website/docs/r/compute_global_forwarding_rule.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1851 Change collection_url_response to a string
  api/resource.rb
  api/resource/response_list.rb
  products/bigquery/api.yaml
  products/cloudbuild/api.yaml
  products/cloudbuild/inspec.yaml
  products/cloudfunctions/api.yaml
  products/compute/api.yaml
  products/container/api.yaml
  products/dns/api.yaml
  products/iam/api.yaml
  products/pubsub/api.yaml
  products/redis/api.yaml
  products/resourcemanager/api.yaml
  products/sourcerepo/api.yaml
  products/spanner/api.yaml
  products/sql/api.yaml
  templates/ansible/facts.erb
  templates/inspec/plural_resource.erb
  templates/inspec/singular_resource.erb
Labels: ansible, automerged, cla: yes, downstream-generated, inspec

#1854 Remove deprecated collection_url_response from KMS
  products/kms/api.yaml
Labels: automerged, cla: yes, downstream-generated

#1861 Remove downstream-specific PR titles
  .ci/magic-modules/extract_from_pr_description.py
  .ci/magic-modules/extract_from_pr_description_test.py
  .ci/magic-modules/generate-ansible.sh
  .ci/magic-modules/generate-inspec.sh
  .ci/magic-modules/generate-terraform.sh
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google-beta

#1833 Add support for INTERNAL_SELF_MANAGED backend service
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/global_forwarding_rule_internal.tf.erb
  third_party/terraform/tests/resource_compute_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_global_forwarding_rule_test.go.erb
Labels: ansible, automerged, cla: yes, downstream-generated, inspec, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta
