Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2019-01, with the labels that each got.

#1131 CI change - incorporates PR #1 against ndmckinley/github-pullrequest-resource.
  .ci/ci.yml.tmpl
Labels: automerged, cla: yes, downstream-generated

#1140 Add update mask support to uptimeChecks
  products/monitoring/terraform.yaml
Labels: automerged, cla: yes, downstream-generated

#1138 Remove puppet from releases.
  .ci/release.yml.tmpl
Labels: automerged, cla: yes, downstream-generated

#1089 Migrate TF over to new Overrides
  api/type.rb
  products/accesscontextmanager/terraform.yaml
  products/binaryauthorization/terraform.yaml
  products/compute/helpers/terraform/autoscaler_overrides.yaml
  products/compute/helpers/terraform/disk_overrides.yaml
  products/compute/terraform.yaml
  products/containeranalysis/terraform.yaml
  products/dns/terraform.yaml
  products/filestore/terraform.yaml
  products/redis/terraform.yaml
  products/resourcemanager/terraform.yaml
  products/storage/terraform.yaml
  provider/overrides/runner.rb
  provider/overrides/validator.rb
  provider/terraform/property_override.rb
  spec/override_runner_spec.rb
  spec/override_validator_spec.rb
Labels: automerged, cla: yes, downstream-generated

#1158 Add signoff for inspec repo commits
  .ci/magic-modules/generate-inspec.sh
Labels: automerged, cla: yes, downstream-generated

#1157 Add ResourceRefs for Compute Route.
  products/compute/api.yaml
  products/compute/terraform.yaml
Labels: automerged, cla: yes, downstream-generated

#1165 [Terraform-Beta] Enable flexible pod CIDR for GKE clusters.
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: automerged, cla: yes, downstream-generated

#1182 First draft of new README.md
  README.md
Labels: automerged, cla: yes, downstream-generated

#1183 CI changes to move to GCR
  .ci/README.md
  .ci/acceptance-tests/inspec-integration.yml
  .ci/ci.yml.tmpl
  .ci/containers/ansible/Dockerfile
  .ci/containers/go-ruby-python/Dockerfile
  .ci/containers/hub/Dockerfile
  .ci/containers/inspec/Dockerfile
  .ci/containers/inspec/Gemfile
  .ci/containers/jq/Dockerfile
  .ci/containers/merged-prs-resource/Dockerfile
  .ci/containers/puppet-forge/Dockerfile
  .ci/containers/puppet-forge/Gemfile
  .ci/containers/puppet-forge/check.rb
  .ci/containers/puppet-forge/in.rb
  .ci/containers/puppet-forge/out.rb
  .ci/containers/terraform-gcloud-inspec/Dockerfile
  .ci/magic-modules/branch.yml
  .ci/magic-modules/create-pr.yml
  .ci/magic-modules/generate-ansible.yml
  .ci/magic-modules/generate-inspec.yml
  .ci/magic-modules/generate-terraform.yml
  .ci/magic-modules/get-merged-patches.yml
  .ci/magic-modules/merge.yml
  .ci/magic-modules/point-to-submodules.yml
  .ci/release.yml.tmpl
  .ci/release/create_bundle_manifest.sh
  .ci/release/create_bundle_manifest.yml
  .ci/unit-tests/inspec.yml
Labels: automerged, cla: yes, downstream-generated

#1185 Add contents of CONTRIBUTING, DEVELOPER to README.
  CONTRIBUTING.md
  DEVELOPER.md
  GOVERNANCE.md
  README.md
  TEMPLATE_SDK.md
  docs/philosophy.md
Labels: automerged, cla: yes, downstream-generated

#1173 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerged, cla: yes, downstream-generated

#1188 Inline TEMPLATE_SDK, remove it.
  TEMPLATE_SDK.md
  api/product.rb
  api/resource.rb
Labels: automerged, cla: yes, downstream-generated

#1187 Add version exclusion for beta container cluster code
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: automerged, cla: yes, downstream-generated

#1149 Adding labels based on downstreams created
  .ci/ci.yml.tmpl
  .ci/magic-modules/create-pr.sh
Labels: ansible, automerged, cla: yes, downstream-generated, terraform

#1079 Allow final version of the api.yaml to be output
  .gitignore
  compiler.rb
  provider/core.rb
Labels: automerged, cla: yes, downstream-generated

#1192 Fix CLA links in README
  README.md
Labels: automerged, cla: yes, downstream-generated

#1193 Update the Overview section in README
  README.md
Labels: automerged, cla: yes, downstream-generated

#1167 add magician step to run affected terraform tests
  .ci/acceptance-tests/terraform-acceptance.sh
  .ci/acceptance-tests/terraform-acceptance.yml
  .ci/ci.yml.tmpl
Labels: The Magician, automerged, cla: yes, downstream-generated

#1194 Update merged pr resource version
  .ci/ci.yml.tmpl
Labels: automerged, cla: yes, downstream-generated, no-op

#1198 Magic Modules no longer overwrites files mid run
  compiler.rb
  provider/ansible.rb
  provider/core.rb
  provider/terraform/common~compile.yaml
  spec/provider_core_spec.rb
  spec/provider_terraform_import_spec.rb
  spec/provider_terraform_spec.rb
  third_party/terraform/website-compiled/google.erb
Labels: automerged, cla: yes, downstream-generated, no-op

#1172 [Terraform]: Add timePartitioning.requirePartitionFilter to bigquery table
  third_party/terraform/resources/resource_bigquery_table.go
  third_party/terraform/tests/resource_bigquery_table_test.go
  third_party/terraform/website/docs/r/bigquery_table.html.markdown
Labels: automerged, cla: no, downstream-generated, terraform

#1180 Remove some simple puppet/chef stuff no longer in use.
  products/compute/inspec.yaml
  provider/config.rb
  provider/core.rb
  templates/CHANGELOG.md.erb
Labels: automerged, cla: yes, downstream-generated

#1203 Remove changelog from inspec generation
  .ci/magic-modules/generate-inspec.sh
  provider/config.rb
Labels: automerged, cla: yes, downstream-generated, no-op

#1153 Migrating Ansible + InSpec to new Overrides
  api/type.rb
  products/bigquery/ansible.yaml
  products/compute/ansible.yaml
  products/compute/inspec.yaml
  products/container/ansible.yaml
  products/dns/ansible.yaml
  products/iam/ansible.yaml
  products/pubsub/ansible.yaml
  products/resourcemanager/ansible.yaml
  products/spanner/ansible.yaml
  products/sql/ansible.yaml
  products/storage/ansible.yaml
  provider/ansible.rb
  provider/ansible/config.rb
  provider/ansible/facts_override.rb
  provider/ansible/property_override.rb
  provider/ansible/resource_override.rb
  provider/core.rb
  provider/inspec.rb
  provider/inspec/resource_override.rb
  provider/overrides/ansible/property_override.rb
  provider/overrides/ansible/resource_override.rb
  provider/overrides/inspec/property_override.rb
  provider/overrides/inspec/resource_override.rb
  provider/overrides/runner.rb
Labels: automerged, cla: yes, downstream-generated, no-op

#1205 Contributor: dataproc encryption
  third_party/terraform/resources/resource_dataproc_cluster.go
  third_party/terraform/tests/resource_dataproc_cluster_test.go
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
Labels: automerged, cla: no, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1216 Fix AppEngine FirewallRule naming
  products/appengine/terraform.yaml
  templates/terraform/examples/app_engine_firewall_rule_basic.tf.erb
  third_party/terraform/website-compiled/google.erb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1201 [Terraform] Add more OAuth2 credential options.
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/config_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/provider_reference.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1225 Add back a CONTRIBUTING markdown file.
  .github/CONTRIBUTING.md
  README.md
Labels: automerged, cla: yes, downstream-generated, no-op

#1226 Add a glossary of MM terms to the README
  README.md
Labels: automerged, cla: yes, downstream-generated, no-op, terraform-provider-google

#1238 Fix typo in google_compute_security_policy docs
  third_party/terraform/website/docs/r/compute_security_policy.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1243 Remove unused methods in core
  compile/core.rb
Labels: automerged, cla: yes, downstream-generated, no-op

#1241 Removing _bundle and auth (unused)
  Rakefile
  api/bundle.rb
  api/compiler.rb
  compile/core.rb
  compiler.rb
  products/_bundle/api.yaml
  products/_bundle/files/spec/.keep
  products/auth/api.yaml
  provider/ansible/bundle.rb
  provider/core.rb
Labels: automerged, cla: yes, downstream-generated, no-op

#1246 Add instance group manager resource to InSpec
  products/compute/inspec.yaml
  templates/inspec/examples/attributes/external_attributes.yml
  templates/inspec/examples/attributes/google_compute_instance_group_manager.erb
  templates/inspec/examples/google_compute_instance_group_manager.erb
  templates/inspec/examples/google_compute_instance_group_managers.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
Labels: automerged, cla: yes, downstream-generated, inspec

#1265 Move disk parameters inline for RegionDisk
  products/compute/api.yaml
  products/compute/disk_parameters.yaml
Labels: cla: yes, downstream-generated, inspec

#1260 Ensure exclude_if_not_in_version is run
  api/resource.rb
  api/type.rb
  provider/core.rb
  spec/resource_spec.rb
Labels: automerged, cla: yes, downstream-generated, inspec

#1272 Make it easier to handle community PRs.
  .ci/ci.yml.tmpl
Labels: automerged, cla: yes, downstream-generated, no-op

#1276 Spreadsheet/linter should ignore operation
  tools/linter/discovery.rb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1288 Fix map in Random provider in SSLCert OiCS example.
  templates/terraform/examples/ssl_certificate_random_provider.tf.erb
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1293 Fix Terraform examples override changes that got lost in merges
  overrides/terraform/resource_override.rb
Labels: automerged, cla: yes, downstream-generated, no-op

#1290 Remove Example provider code
  compiler.rb
  provider/example.rb
  templates/example/compiled_file
  templates/example/copied_file
  templates/example/resource.erb
Labels: automerged, cla: yes, downstream-generated, no-op

#1292 Inline generate_file, comment thoroughly
  api/compiler.rb
  provider/core.rb
Labels: automerged, cla: yes, downstream-generated, no-op

#1306 change test assertions to match new values
  third_party/terraform/tests/resource_dataproc_cluster_test.go
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1102 [Terraform] Gcloud scheduler
  products/cloudscheduler/api.yaml
  products/cloudscheduler/terraform.yaml
  templates/terraform/custom_expand/cloudscheduler_job_name.erb
  templates/terraform/custom_flatten/http_headers.erb
  third_party/terraform/tests/resource_cloudscheduler_job_test.go.erb
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/validate-http-headers.go.erb
Labels: automerged, cla: no, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1313 [Terraform]: Fix PG docs as PG 9.6 is GA
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1315 Check downstreams to make sure that there aren't any unmerged.
  .ci/ci.yml.tmpl
  .ci/magic-modules/ensure-downstreams-merged.yml
  .ci/magic-modules/ensure_downstreams_merged.py
  .ci/magic-modules/welcome-contributor.sh
Labels: automerged, cla: yes, downstream-generated, no-op

#1320 Make sure that we don't respond to community PRs more than once.
  .ci/ci.yml.tmpl
  .ci/magic-modules/welcome-contributor.sh
Labels: automerged, cla: yes, downstream-generated, no-op

#1321 Add support for target TCP proxy in InSpec
  products/compute/inspec.yaml
  templates/inspec/examples/attributes/google_compute_target_tcp_proxy.erb
  templates/inspec/examples/google_compute_target_tcp_proxies.erb
  templates/inspec/examples/google_compute_target_tcp_proxy.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
Labels: automerged, cla: yes, downstream-generated, inspec

#1324 Remove unused input.
  .ci/magic-modules/welcome-contributor.yml
Labels: automerged, cla: yes, downstream-generated, no-op

#400 PR Script
  .gitignore
  tools/ansible-pr/README.md
  tools/ansible-pr/run
  tools/ansible-pr/template.md.erb
  tools/ansible-pr/templates/.keep
Labels: automerged, cla: yes, downstream-generated

#1097 [Terraform] ip_address.0.time_to_retire it's not optional
  third_party/terraform/resources/resource_sql_database_instance.go.erb
Labels: automerged, cla: yes, community, downstream-generated, terraform-provider-google, terraform-provider-google-beta
