Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2019-07, with the labels that each got.

#1982 Pub/Sub Topic CMEK/KMS support
  products/pubsub/api.yaml
  products/pubsub/terraform.yaml
  templates/terraform/examples/pubsub_topic_cmek.tf.erb
  third_party/terraform/tests/resource_pubsub_topic_test.go
Labels: ansible, automerged, cla: yes, downstream-generated, inspec, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#1979 Note that disks created from snapshots in other projects need full URL
  products/compute/api.yaml
Labels: automerged, cla: yes, downstream-generated, inspec, terraform-provider-google, terraform-provider-google-beta

#2009 Set empty security policy
  templates/terraform/post_create/compute_backend_service_security_policy.go.erb
  third_party/terraform/tests/resource_compute_backend_service_test.go.erb
Labels: automerged, changelog: bugfix, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2022 Simplify the parse command
  overrides/runner.rb
  provider/config.rb
Labels: automerged, cla: yes, downstream-generated

#1996 Terraform.yaml overrides
  compiler.rb
  overrides/runner.rb
  spec/provider_terraform_resource_override_spec.rb
Labels: automerged, cla: yes, downstream-generated

#2019 Revert "old ansible release script"
  tools/ansible-pr/README.md
  tools/ansible-pr/generate_template.rb
  tools/ansible-pr/run.sh
Labels: automerged, cla: yes, downstream-generated, inspec

#2003 Fix regexp and name for downstreaming changelog script
  .ci/magic-modules/downstream_changelog_metadata.py
  .ci/magic-modules/pyutils/strutils.py
Labels: automerged, cla: yes, downstream-generated

#2025 Add versioning reqs to README
  README.md
Labels: automerged, cla: yes, downstream-generated

#2031 Remove nodepool autoscaling when disabled
  third_party/terraform/resources/resource_container_node_pool.go.erb
Labels: automerged, changelog: bugfix, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2036 Fix release note parsing to actually replace the release note.
  .ci/magic-modules/pyutils/strutils.py
  .ci/magic-modules/pyutils/strutils_test.py
Labels: automerged, cla: yes, downstream-generated

#2039 ansible needs to ship doc fragments too
  .ci/magic-modules/release-ansible.sh
Labels: automerged, cla: yes, downstream-generated

#2040 Better messages, template formatting for auto-changelog
  .ci/magic-modules/downstream_changelog_metadata.py
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerged, cla: yes, downstream-generated

#2046 Fix iam destination directory
  provider/terraform.rb
Labels: automerged, cla: yes, downstream-generated

#2038 Support delete for network peering
  third_party/terraform/resources/resource_service_networking_connection.go
  third_party/terraform/tests/resource_service_networking_connection_test.go
  third_party/terraform/utils/service_networking_operation.go
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2048 Adding 'service_account_file' type
  provider/ansible/gcp_doc_frag.py
Labels: ansible, automerged, cla: yes, downstream-generated

#2053 Fix internal field diff in monitoring uptime check
  products/monitoring/terraform.yaml
  templates/terraform/decoders/monitoring_uptime_check_internal.go.erb
Labels: automerged, changelog: bug-fix, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2027 Add request batching to service usage
  .ci/magic-modules/pyutils/strutils.py
  provider/terraform_object_library.rb
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/resources/resource_google_project_services.go
  third_party/terraform/tests/resource_google_project_service_test.go
  third_party/terraform/tests/resource_google_project_services_test.go
  third_party/terraform/utils/batcher.go
  third_party/terraform/utils/batcher_test.go
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/config_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/serviceusage_batching.go
  third_party/terraform/utils/validation.go
  third_party/terraform/website/docs/provider_reference.html.markdown
Labels: cla: yes, downstream-generated, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#2057 Add ability to use an alternate directory within provider configs
  compiler.rb
  provider/config.rb
Labels: automerged, cla: yes, downstream-generated

#2087 Compile ansible/inspec for all products
  .ci/magic-modules/generate-ansible.sh
  .ci/magic-modules/generate-inspec.sh
Labels: automerged, cla: yes, downstream-generated

#2088 Only add oics providers for beta specifically.
  templates/terraform/examples/base_configs/test_file.go.erb
  third_party/terraform/utils/provider_test.go.erb
Labels: automerged, cla: yes, downstream-generated

#2096 Able to specify file path in terraform example
  provider/terraform/examples.rb
Labels: automerged, cla: yes, downstream-generated

#2095 Add ability to specify a custom delete check for generated tests
  provider/terraform/custom_code.rb
  templates/terraform/examples/base_configs/test_file.go.erb
Labels: automerged, cla: yes, downstream-generated

#2094 Allow private to be a superset of all versions
  api/product/version.rb
Labels: ansible, automerged, cla: yes, downstream-generated
