Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2019-02, with the labels that each got.

#1336 [Terraform] Store SHA 256 of certificate SSL private keys
  products/compute/terraform.yaml
  templates/terraform/custom_flatten/sha256.erb
  third_party/terraform/utils/utils.go
Labels: automerged, cla: yes, downstream-generated, no-op, terraform-provider-google, terraform-provider-google-beta

#1329 Update GKE examples, docs to recommend fine grained node pools.
  third_party/terraform/website/docs/r/container_cluster.html.markdown
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1339 Make objects immutable
  provider/ansible.rb
  provider/ansible/product~compile.yaml
  provider/core.rb
Labels: automerged, cla: yes, downstream-generated, no-op

#1252 Add custom JSON generation
  .ci/magic-modules/ensure_downstreams_merged.py
  api/product.rb
  api/resource.rb
  api/type.rb
Labels: automerged, cla: yes, downstream-generated, no-op, terraform-provider-google, terraform-provider-google-beta

#1348 Add InSpec test link to readme
  README.md
Labels: automerged, cla: yes, downstream-generated, no-op

#1350 Fix OiCS generation for 2.0.0
  provider/terraform/custom_code.rb
  provider/terraform_example.rb
Labels: automerged, cla: yes, downstream-generated, no-op

#1346 Inspec property refactor
  provider/inspec.rb
  templates/inspec/nested_object.erb
Labels: automerged, cla: yes, downstream-generated, no-op

#1345 No more Exports
  api/resource.rb
  api/type.rb
  products/compute/api.yaml
  products/container/api.yaml
  products/dns/api.yaml
  products/iam/api.yaml
  products/monitoring/api.yaml
  products/pubsub/api.yaml
  products/spanner/api.yaml
  products/sql/api.yaml
  products/storage/api.yaml
  spec/data/good-export-file.yaml
  spec/data/good-file.yaml
  spec/data/good-multi-file.yaml
  templates/terraform/resource.erb
  templates/terraform/resource.html.markdown.erb
Labels: automerged, cla: yes, downstream-generated, no-op

#1379 Add a downgrade guide to the upgrade guide
  third_party/terraform/website/docs/version_2_upgrade.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#1380 Add post merge step to record new master cassettes for InSpec
  .ci/acceptance-tests/inspec-post-merge.sh
  .ci/acceptance-tests/inspec-post-merge.yml
  .ci/ci.yml.tmpl
Labels: automerged, cla: yes, downstream-generated, no-op

#1390 Add note about unintended downstreams to README
  README.md
Labels: cla: yes, downstream-generated, no-op

#1391 Move integration tests to release pipeline
  .ci/acceptance-tests/ansible-integration.sh
  .ci/acceptance-tests/ansible-integration.yml
  .ci/ci.yml.tmpl
  .ci/release.yml.tmpl
Labels: automerged, cla: yes, downstream-generated, no-op

#1399 Templates, inspec.yaml for bigquery table
  products/bigquery/inspec.yaml
  templates/inspec/examples/google_bigquery_table/google_bigquery_table.erb
  templates/inspec/examples/google_bigquery_table/google_bigquery_table_attributes.erb
  templates/inspec/examples/google_bigquery_table/google_bigquery_tables.erb
Labels: automerged, cla: yes, downstream-generated, inspec

#1401 Fix shell script reference
  .ci/acceptance-tests/inspec-post-approve.yml
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google-beta

#1404 remember to chmod +x your ci things.
  .ci/magic-modules/write-branch-name.sh
Labels: cla: yes, downstream-generated, no-op

#1402 Gsutil parallel
  .ci/acceptance-tests/inspec-post-approve.sh
  .ci/acceptance-tests/inspec-post-merge.sh
  .ci/acceptance-tests/inspec-vcr.sh
  .ci/unit-tests/inspec.sh
Labels: automerged, cla: yes, downstream-generated, no-op, terraform-provider-google-beta

#1409 removing nightly trigger + changing release pipeline script for Ansible
  .ci/magic-modules/release-ansible.sh
Labels: automerged, cla: yes, downstream-generated, no-op

#1410 Ordering changes in create-prs.
  .ci/ci.yml.tmpl
  .ci/magic-modules/create-pr.sh
Labels: automerged, cla: yes, downstream-generated, no-op

#1407 Remove unused update_statement code
  overrides/terraform/property_override.rb
  templates/terraform/resource.erb
Labels: automerged, cla: yes, downstream-generated, no-op

#1398 Compile/copy files in parallel
  compile/core.rb
  provider/core.rb
Labels: automerged, cla: yes, downstream-generated, no-op

#1412 Ansible Release Pipeline - new version of hub image + set SSH keys
  .ci/containers/hub/Dockerfile
  .ci/magic-modules/release-ansible.sh
  .ci/magic-modules/release-ansible.yml
  .ci/release.yml.tmpl
  tools/ansible-pr/run.sh
Labels: automerged, cla: yes, downstream-generated, no-op

#1413 Final fixes for Release Pipeline
  .ci/magic-modules/release-ansible.sh
  .ci/magic-modules/release-ansible.yml
  .ci/release.yml.tmpl
  tools/ansible-pr/run.sh
Labels: automerged, cla: yes, downstream-generated, inspec, no-op

#1421 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerged, cla: yes, downstream-generated, no-op

#1416 moving ansible release pipeline back to nightly build on HEAD
  .ci/magic-modules/release-ansible.sh
  .ci/magic-modules/release-ansible.yml
  .ci/release.yml.tmpl
Labels: automerged, cla: yes, downstream-generated, inspec

#1424 ignore all excluded/not versioned files in ansible
  provider/ansible/product~compile.yaml
Labels: automerged, cla: yes, downstream-generated, no-op

#1428 Only run go mod vendor if git differences
  .ci/magic-modules/generate-terraform.sh
Labels: automerged, cla: yes, downstream-generated, no-op

#1441 Move terraform test image to latest go version
  .ci/unit-tests/task.yml
  .ci/unit-tests/test-terraform.yml
Labels: automerged, cla: yes, downstream-generated, no-op

#1447 Add API requirements for some products
  api/product.rb
  products/bigquery/api.yaml
  products/cloudbuild/api.yaml
  products/compute/api.yaml
  products/container/api.yaml
  products/dns/api.yaml
  products/iam/api.yaml
  products/monitoring/api.yaml
  products/pubsub/api.yaml
  products/resourcemanager/api.yaml
  products/sourcerepo/api.yaml
  products/spanner/api.yaml
  products/sql/api.yaml
  products/storage/api.yaml
Labels: automerged, cla: yes, downstream-generated, no-op, terraform-provider-google, terraform-provider-google-beta

#1456 Ansible -> InSpec in create PR
  .ci/magic-modules/create-pr.sh
Labels: automerged, cla: yes, downstream-generated, no-op
