Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2020-10, with the labels that each got.

#3897 Upstream bq mat view
  third_party/terraform/resources/resource_bigquery_table.go
  third_party/terraform/tests/resource_bigquery_table_test.go
  third_party/terraform/website/docs/r/bigquery_table.html.markdown
Labels: cla: yes

#4006 Allow management of old AppEngine resources from before CLOUD_DATASTORE_COMPATIBILITY.
  third_party/terraform/resources/resource_app_engine_application.go
  third_party/terraform/website/docs/r/app_engine_application.html.markdown
Labels: cla: yes

#4004 fixed error when a boolean field set to false
  products/datacatalog/api.yaml
  products/datacatalog/terraform.yaml
  templates/terraform/encoders/data_catalog_tag.go.erb
  templates/terraform/examples/data_catalog_entry_tag_false.tf.erb
Labels: cla: yes

#4038 Note that recurring_window should use UTC time
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3981 Add Bigtable Table IAM Resources
  third_party/terraform/tests/resource_bigtable_table_iam_test.go
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/iam_bigtable_table.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/r/bigtable_table_iam.html.markdown
Labels: cla: yes

#4039 Mark dataflow_flex_template labels as deprecated
  third_party/terraform/resources/resource_dataflow_flex_template_job.go.erb
  third_party/terraform/website/docs/r/dataflow_flex_template_job.html.markdown
Labels: cla: yes

#4029 Node_config image_type case diff suppress
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/utils/node_config.go.erb
Labels: cla: yes

#4036 Add google_cloud_run_service datasource
  third_party/terraform/data_sources/data_source_cloud_run_service.go
  third_party/terraform/tests/data_source_cloud_run_service_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/cloud_run_service.html.markdown
Labels: cla: yes

#4045 feat: Add forwarding_path to google_dns_policy
  products/dns/api.yaml
  templates/terraform/examples/dns_policy_basic.tf.erb
  third_party/terraform/tests/resource_dns_policy_test.go.erb
Labels: cla: yes

#4048 Added myself to the contributor / member lists
  .ci/containers/contributor-checker/check-contributor.sh
  .ci/containers/terraform-vcr-community/reverse_check_membership.sh
  .ci/containers/terraform-vcr-tester/check_membership.sh
Labels: cla: yes

#4042 Use compatible machine type with gvisor
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
Labels: cla: yes

#4043 Add location to bigquery job self_link
  products/bigquery/api.yaml
  products/bigquery/terraform.yaml
  third_party/terraform/tests/resource_bigquery_job_test.go
Labels: cla: yes

#3946 Use cloud.json to find out cloud-netblocks
  third_party/terraform/data_sources/data_source_google_netblock_ip_ranges.go
Labels: cla: no

#4047 Stateful MIG -> GA
  products/compute/api.yaml
  third_party/terraform/resources/resource_compute_instance_group_manager.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
  third_party/terraform/tests/resource_compute_instance_group_manager_test.go
  third_party/terraform/tests/resource_compute_per_instance_config_test.go
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go
  third_party/terraform/tests/resource_compute_region_per_instance_config_test.go
  third_party/terraform/utils/stateful_mig_polling.go
  third_party/terraform/website/docs/r/compute_instance_group_manager.html.markdown
  third_party/terraform/website/docs/r/compute_region_instance_group_manager.html.markdown
Labels: cla: yes

#4035 Refactoring clients (the rest of them)
  third_party/terraform/data_sources/data_source_cloud_identity_group_memberships.go.erb
  third_party/terraform/data_sources/data_source_cloud_identity_groups.go.erb
  third_party/terraform/data_sources/data_source_google_bigquery_default_service_account.go
  third_party/terraform/data_sources/data_source_google_billing_account.go
  third_party/terraform/data_sources/data_source_google_storage_transfer_project_service_account.go
  third_party/terraform/resources/resource_app_engine_application.go
  third_party/terraform/resources/resource_bigquery_table.go
  third_party/terraform/resources/resource_bigtable_gc_policy.go
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/resources/resource_bigtable_table.go
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/resources/resource_composer_environment.go.erb
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/resources/resource_dataproc_job.go
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/resources/resource_service_networking_connection.go
  third_party/terraform/resources/resource_storage_transfer_job.go
  third_party/terraform/tests/resource_big_query_dataset_test.go
  third_party/terraform/tests/resource_bigquery_table_test.go
  third_party/terraform/tests/resource_bigtable_gc_policy_test.go
  third_party/terraform/tests/resource_bigtable_instance_test.go
  third_party/terraform/tests/resource_bigtable_table_test.go
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
  third_party/terraform/tests/resource_composer_environment_test.go.erb
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
  third_party/terraform/tests/resource_dataproc_job_test.go
  third_party/terraform/tests/resource_google_billing_account_iam_test.go
  third_party/terraform/tests/resource_google_project_test.go
  third_party/terraform/tests/resource_healthcare_dataset_iam_test.go
  third_party/terraform/tests/resource_healthcare_dataset_test.go
  third_party/terraform/tests/resource_healthcare_dicom_store_iam_test.go
  third_party/terraform/tests/resource_healthcare_dicom_store_test.go
  third_party/terraform/tests/resource_healthcare_fhir_store_iam_test.go
  third_party/terraform/tests/resource_healthcare_fhir_store_test.go
  third_party/terraform/tests/resource_healthcare_hl7_v2_store_iam_test.go
  third_party/terraform/tests/resource_healthcare_hl7_v2_store_test.go
  third_party/terraform/tests/resource_service_networking_connection_test.go
  third_party/terraform/tests/resource_storage_transfer_job_test.go
  third_party/terraform/utils/appengine_operation.go
  third_party/terraform/utils/cloudfunctions_operation.go
  third_party/terraform/utils/composer_operation.go
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/dataproc_cluster_operation.go
  third_party/terraform/utils/dataproc_job_operation.go
  third_party/terraform/utils/iam_bigtable_instance.go
  third_party/terraform/utils/iam_bigtable_table.go
  third_party/terraform/utils/iam_billing_account.go
  third_party/terraform/utils/iam_dataproc_cluster.go
  third_party/terraform/utils/iam_dataproc_job.go
  third_party/terraform/utils/iam_healthcare_dataset.go
  third_party/terraform/utils/iam_healthcare_dicom_store.go
  third_party/terraform/utils/iam_healthcare_fhir_store.go
  third_party/terraform/utils/iam_healthcare_hl7_v2_store.go
  third_party/terraform/utils/iam_spanner_database.go
  third_party/terraform/utils/iam_spanner_instance.go
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/utils/service_networking_operation.go
Labels: cla: yes

#4054 Override artifact registry self_link and self_link iam override
  api/resource/iam_policy.rb
  products/artifactregistry/api.yaml
  products/artifactregistry/terraform.yaml
  templates/terraform/examples/base_configs/iam_test_file.go.erb
  templates/terraform/iam/iam_attributes.tf.erb
  templates/terraform/resource_iam.html.markdown.erb
Labels: cla: yes

#4053 Make RegionBackendService health checks optional
  products/compute/api.yaml
Labels: cla: yes

#4052 Add Global forwarding rule datasource
  third_party/terraform/data_sources/data_source_google_global_compute_forwarding_rule.go
  third_party/terraform/tests/data_source_google_global_compute_forwarding_rule_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/compute_global_forwarding_rule.html.markdown
Labels: cla: yes

#4040 Upstream https://github.com/hashicorp/terraform-provider-google/pull/7349
  third_party/terraform/website/docs/r/app_engine_application.html.markdown
Labels: cla: yes

#4051 Fix Regional Forwarding rule datasource to use the new style.
  third_party/terraform/data_sources/data_source_google_compute_forwarding_rule.go
  third_party/terraform/tests/data_source_google_compute_forwarding_rule_test.go
  third_party/terraform/website/docs/d/compute_forwarding_rule.html.markdown
Labels: cla: yes, hacktoberfest-accepted

#4056 Update terminology for IAM roles
  products/bigquery/api.yaml
Labels: cla: yes

#4055 Added COMMENTS_ENABLED_FOR_EXTERNAL_CONTRIBUTORS_ONLY support to github pullRequest commentControl
  products/cloudbuild/api.yaml
Labels: cla: yes

#4059 Clarification on the use of the 'roles/owner' role
  third_party/terraform/website/docs/r/google_project_iam.html.markdown
Labels: cla: no

#4057 Fix mixed up client name
  third_party/terraform/resources/resource_bigtable_gc_policy.go
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/resources/resource_bigtable_table.go
  third_party/terraform/tests/resource_bigtable_gc_policy_test.go
  third_party/terraform/tests/resource_bigtable_instance_test.go
  third_party/terraform/tests/resource_bigtable_table_test.go
  third_party/terraform/utils/config.go.erb
Labels: cla: yes

#3993 Change condition age example to an integer
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
Labels: cla: yes

#4060 Add source snapshot to ansible
  products/compute/ansible.yaml
Labels: cla: yes

#4062 Add data source for pubsub topics
  third_party/terraform/data_sources/data_source_pubsub_topic.go
  third_party/terraform/tests/data_source_pubsub_topic_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/pubsub_topic.html.markdown
Labels: cla: no

#4063 Skip cmek test
  third_party/terraform/tests/resource_compute_snapshot_test.go
Labels: cla: yes

#4064 fix deleting monitoring dashboards
  third_party/terraform/resources/resource_monitoring_dashboard.go
Labels: cla: yes

#4041 Upstream https://github.com/hashicorp/terraform-provider-google/pull/7350
  third_party/terraform/website/docs/r/service_networking_connection.html.markdown
Labels: cla: yes

#4058 Fix id token datasource
  third_party/terraform/data_sources/data_source_google_service_account_id_token.go
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/website/docs/d/service_account_id_token.html.markdown
Labels: cla: yes, hacktoberfest-accepted

#4067 Add support for Monthly/Yearly BigQuery Partitioning
  third_party/terraform/resources/resource_bigquery_table.go
  third_party/terraform/tests/resource_bigquery_table_test.go
  third_party/terraform/website/docs/r/bigquery_table.html.markdown
Labels: cla: no

#4069 Update organization.html.markdown to clarify permissions, organization value format
  third_party/terraform/website/docs/d/organization.html.markdown
Labels: cla: yes

#4070 docs(bigquery): remove list of location
  products/bigquery/api.yaml
Labels: cla: yes

#4065 fix permadiff with new access approval cloud product mappings
  products/accessapproval/api.yaml
  products/accessapproval/terraform.yaml
  templates/terraform/constants/access_approval.go.erb
  third_party/terraform/tests/resource_access_approval_organization_settings_test.go
Labels: cla: yes

#4072 Project precheck
  third_party/terraform/resources/resource_google_project.go
Labels: cla: yes

#4075 update tf website documentation index page
  third_party/terraform/website/docs/index.html.markdown
Labels: cla: yes

#4027 Upstream resource_logging_project_sink exclusions
  third_party/terraform/resources/resource_logging_sink.go
  third_party/terraform/tests/resource_logging_project_sink_test.go
  third_party/terraform/website/docs/r/logging_project_sink.html.markdown
Labels: cla: yes

#4079 Terraform 7459 redis AUTH support in beta
  products/redis/api.yaml
  third_party/terraform/tests/resource_redis_instance_test.go.erb
  third_party/terraform/website/docs/d/redis_instance.html.markdown
Labels: cla: yes

#4061 separate code generation and docs generation
  .ci/containers/downstream-builder/generate_downstream.sh
  compiler.rb
  provider/ansible.rb
  provider/ansible_devel.rb
  provider/core.rb
  provider/inspec.rb
  provider/terraform.rb
  provider/terraform/common~copy.yaml
  provider/terraform_object_library.rb
  provider/terraform_oics.rb
Labels: cla: yes

#4083 only separate docs for terraform && ga
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: cla: yes

#4078 Added field graceful_decomissioning_timeout to resource dataproc_cluster
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
Labels: cla: yes

#4077 Added stackdriver_logging_config to cloud_tasks_queue resource
  products/cloudtasks/api.yaml
  products/cloudtasks/terraform.yaml
  templates/terraform/examples/cloud_tasks_queue_advanced.tf.erb
  third_party/terraform/tests/resource_cloud_tasks_queue_test.go.erb
Labels: cla: yes

#4088 fix lint errors
  .rubocop.yml
  compiler.rb
  provider/ansible.rb
  provider/ansible_devel.rb
  provider/core.rb
  provider/terraform.rb
  provider/terraform_object_library.rb
  provider/terraform_oics.rb
Labels: cla: yes

#4026 Add Image filters to google_compute_image.
  third_party/terraform/data_sources/data_source_google_compute_image.go
  third_party/terraform/tests/data_source_google_compute_image_test.go
  third_party/terraform/website/docs/d/compute_image.html.markdown
Labels: cla: yes

#4087 use sweeper-friendly delete url for activedirectory domain
  products/activedirectory/api.yaml
Labels: cla: yes

#4073 logging bucket destination added to sink resource docs
  third_party/terraform/website/docs/r/logging_billing_account_sink.html.markdown
  third_party/terraform/website/docs/r/logging_folder_sink.html.markdown
  third_party/terraform/website/docs/r/logging_organization_sink.html.markdown
  third_party/terraform/website/docs/r/logging_project_sink.html.markdown
Labels: cla: yes

#4033 Support logs bucket creation and custom ID's
  third_party/terraform/resources/resource_logging_bucket_config.go
  third_party/terraform/tests/resource_logging_bucket_config_test.go
  third_party/terraform/website/docs/r/logging_project_bucket_config.html.markdown
Labels: cla: yes

#4090 update variable name configList
  third_party/terraform/tests/resource_logging_bucket_config_test.go
Labels: cla: yes

#4086 Update storage_bucket.html.markdown
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
Labels: cla: yes

#4068 cloudrun: adds GKE caveat to minScale annotation
  products/cloudrun/api.yaml
Labels: cla: yes

#3954 Add delete_protection to SQL Instances + Service Networking Pre Create Checks
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/resources/resource_sql_ssl_cert_test.go
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
  third_party/terraform/tests/resource_sql_database_test.go
  third_party/terraform/tests/resource_sql_user_test.go
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: yes

#4082 send empty value for [region]healthcheck description
  products/compute/api.yaml
  third_party/terraform/tests/resource_compute_health_check_test.go
  third_party/terraform/tests/resource_compute_region_health_check_test.go.erb
Labels: cla: yes

#4092 update to use new service networking client
  third_party/terraform/resources/resource_sql_database_instance.go.erb
Labels: cla: yes

#4093 Fixing the gcloud service list command example
  third_party/terraform/website/docs/r/google_project_service.html.markdown
Labels: cla: yes

#4085 allow setting a project on oslogin ssh key
  products/oslogin/api.yaml
  products/oslogin/terraform.yaml
  templates/terraform/examples/os_login_ssh_key_with_project.tf.erb
  templates/terraform/pre_create/os_login_ssh_public_key.go.erb
Labels: cla: yes

#4094 Address bigquery's low-but-fast-refreshing quota by accepting and retrying quota errors.
  products/bigquery/terraform.yaml
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#4096 add deletion_protection=false to tests with sql_database_instance
  products/cloudrun/terraform.yaml
  products/sql/terraform.yaml
  templates/terraform/examples/cloud_run_service_sql.tf.erb
  templates/terraform/examples/sql_database_basic.tf.erb
  third_party/terraform/tests/data_source_google_sql_ca_certs_test.go
  third_party/terraform/tests/data_source_sql_database_instance_test.go
Labels: cla: yes

#4097 Add Node group maintenance policy
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/node_group_autoscaling_policy.tf.erb
Labels: cla: yes

#4095 Add a warning about User ADCs for Cloud Identity Resources.
  products/cloudidentity/terraform.yaml
Labels: cla: yes

#4081 use E2 VMs
  third_party/terraform/tests/resource_compute_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_disk_test.go.erb
  third_party/terraform/tests/resource_compute_global_forwarding_rule_test.go.erb
  third_party/terraform/tests/resource_compute_instance_from_template_test.go
  third_party/terraform/tests/resource_compute_instance_template_test.go.erb
  third_party/terraform/tests/resource_compute_instance_test.go.erb
Labels: cla: yes

#4030 Compute - Add update support for Network IP when changing network/subnetwork
  third_party/terraform/resources/resource_compute_instance.go.erb
  third_party/terraform/tests/resource_compute_instance_test.go.erb
  third_party/terraform/utils/compute_instance_network_interface_helpers.go
  third_party/terraform/utils/test_utils.go
  third_party/terraform/utils/utils.go.erb
Labels: cla: yes

#4099 add scott to contributor / code review lists
  .ci/containers/contributor-checker/check-contributor.sh
  .ci/containers/terraform-vcr-community/reverse_check_membership.sh
  .ci/containers/terraform-vcr-tester/check_membership.sh
Labels: cla: yes

#4098 add retry to disable project services, update serviceUsageServiceBeingActivated
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#4103 update execute time for os_config_patch_deployment test
  templates/terraform/examples/os_config_patch_deployment_basic.tf.erb
Labels: cla: yes

#4100 regex fixed for global network endpoint import
  products/compute/api.yaml
  templates/terraform/custom_import/compute_global_network_endpoint.go.erb
Labels: cla: yes

#4074 add access_context_manager_access_level_condition
  products/accesscontextmanager/api.yaml
  products/accesscontextmanager/inspec.yaml
  products/accesscontextmanager/terraform.yaml
  templates/terraform/examples/access_context_manager_access_level_condition_basic.tf.erb
  third_party/terraform/tests/resource_access_context_manager_access_level_condition_test.go
  third_party/terraform/tests/resource_access_context_manager_access_policy_test.go.erb
Labels: cla: yes

#4101 Upstream GKE scopes description
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: no

#4107 Fix a typo in "detatch" word, add a "do".
  products/compute/api.yaml
  third_party/terraform/resources/resource_compute_instance_group_manager.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
  third_party/terraform/website/docs/r/compute_instance_group_manager.html.markdown
  third_party/terraform/website/docs/r/compute_region_instance_group_manager.html.markdown
Labels: cla: yes

#4105 use e2 vms, part 2
  templates/terraform/examples/autoscaler_basic.tf.erb
  templates/terraform/examples/autoscaler_single_instance.tf.erb
  templates/terraform/examples/backend_service_signed_url_key.tf.erb
  templates/terraform/examples/compute_packet_mirroring_full.tf.erb
  templates/terraform/examples/forwarding_rule_http_lb.tf.erb
  templates/terraform/examples/global_forwarding_rule_internal.tf.erb
  templates/terraform/examples/instance_basic.tf.erb
  templates/terraform/examples/kms_secret_ciphertext_basic.tf.erb
  templates/terraform/examples/machine_image_basic.tf.erb
  templates/terraform/examples/network_endpoint.tf.erb
  templates/terraform/examples/network_management_connectivity_test_instances.tf.erb
  templates/terraform/examples/notebook_instance_basic.tf.erb
  templates/terraform/examples/notebook_instance_basic_container.tf.erb
  templates/terraform/examples/notebook_instance_basic_gpu.tf.erb
  templates/terraform/examples/notebook_instance_full.tf.erb
  templates/terraform/examples/os_config_guest_policies_basic.tf.erb
  templates/terraform/examples/os_config_patch_deployment_instance.tf.erb
  templates/terraform/examples/region_autoscaler_basic.tf.erb
  templates/terraform/examples/region_backend_service_balancing_mode.tf.erb
  templates/terraform/examples/stateful_igm.tf.erb
  templates/terraform/examples/stateful_rigm.tf.erb
  templates/terraform/examples/target_instance_basic.tf.erb
  templates/terraform/examples/target_instance_custom_network.tf.erb
  third_party/terraform/resources/resource_compute_instance_iam_test.go
  third_party/terraform/tests/data_source_google_compute_instance_group_test.go.erb
  third_party/terraform/tests/data_source_google_compute_instance_serial_port_test.go
  third_party/terraform/tests/data_source_google_compute_instance_test.go
  third_party/terraform/tests/data_source_google_compute_region_instance_group_test.go.erb
  third_party/terraform/tests/resource_compute_autoscaler_test.go.erb
  third_party/terraform/tests/resource_compute_instance_group_manager_test.go
  third_party/terraform/tests/resource_compute_instance_group_test.go
  third_party/terraform/tests/resource_compute_network_endpoint_test.go.erb
  third_party/terraform/tests/resource_compute_per_instance_config_test.go
  third_party/terraform/tests/resource_compute_region_autoscaler_test.go.erb
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_region_disk_test.go
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go
Labels: cla: yes

#4110 add config and deployment script for triage app
  .ci/containers/terraform-triage-party/config.yaml
  .ci/containers/terraform-triage-party/deploy.sh
Labels: cla: yes

#4114 add docs for create_before_destroy on network endpoint groups
  products/compute/api.yaml
Labels: cla: yes

#4111 Add Spanner instance datasource
  third_party/terraform/data_sources/data_source_spanner_instance.go
  third_party/terraform/tests/data_source_spanner_instance_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/spanner_instance.html.markdown
Labels: cla: yes

#4106 add deletion_protection=false to bigquery connection dbs
  products/bigqueryconnection/terraform.yaml
  templates/terraform/examples/bigquery_connection_basic.tf.erb
  templates/terraform/examples/bigquery_connection_full.tf.erb
  third_party/terraform/tests/resource_bigquery_connection_test.go.erb
Labels: cla: yes

#4015 Implement Service Account Impersonation
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/config_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/guides/provider_reference.html.markdown
Labels: cla: yes

#4112 Add iam policy resources for netbook instance
  products/notebooks/api.yaml
Labels: cla: yes

#4050 Update google_billing_budget resource to add disable_default_iam_recipients
  products/billingbudget/api.yaml
  templates/terraform/examples/billing_budget_notify.tf.erb
Labels: cla: yes

#4115 Promote HA VPN to GA
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/external_vpn_gateway.tf.erb
  templates/terraform/examples/ha_vpn_gateway_basic.tf.erb
  templates/terraform/examples/ha_vpn_gateway_gcp_to_gcp.tf.erb
Labels: cla: yes

#4116 add interface attribute to google_compute_disk
  products/compute/api.yaml
  third_party/terraform/tests/resource_compute_disk_test.go.erb
Labels: cla: yes

#4119 remove megan07 from random assignee
  .ci/containers/contributor-checker/check-contributor.sh
Labels: cla: yes

#4118 fix doc formatting errors
  products/compute/api.yaml
Labels: cla: yes

#4108 Remove TestAccProviderMeta_setModuleName from VCR
  third_party/terraform/utils/provider_test.go.erb
Labels: cla: yes

#4117 Terraform 7456 spanner database deletion protection
  products/spanner/terraform.yaml
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/terraform/examples/spanner_database_basic.tf.erb
  templates/terraform/pre_delete/resource_spanner_database.go
  templates/terraform/resource.erb
  third_party/terraform/tests/resource_spanner_database_iam_test.go
  third_party/terraform/tests/resource_spanner_database_test.go
Labels: cla: yes

#4120 Change exactly one of in VPN tunnel to conflicts with
  products/compute/api.yaml
Labels: cla: yes

#4121 add explicit notes to resources w/o import support
  templates/terraform/resource.html.markdown.erb
  third_party/terraform/website/docs/r/bigtable_gc_policy.html.markdown
  third_party/terraform/website/docs/r/compute_instance_from_template.html.markdown
  third_party/terraform/website/docs/r/container_registry.html.markdown
  third_party/terraform/website/docs/r/dataflow_flex_template_job.html.markdown
  third_party/terraform/website/docs/r/dataflow_job.html.markdown
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
  third_party/terraform/website/docs/r/dataproc_job.html.markdown
  third_party/terraform/website/docs/r/endpoints_service.html.markdown
  third_party/terraform/website/docs/r/google_service_account_key.html.markdown
  third_party/terraform/website/docs/r/project_service_identity.html.markdown
  third_party/terraform/website/docs/r/storage_bucket_acl.html.markdown
  third_party/terraform/website/docs/r/storage_bucket_object.html.markdown
  third_party/terraform/website/docs/r/storage_default_object_acl.html.markdown
  third_party/terraform/website/docs/r/storage_object_acl.html.markdown
Labels: cla: yes

#4122 fix TestAccNotebooksInstance_notebookInstanceFullExample
  templates/terraform/examples/notebook_instance_full.tf.erb
Labels: cla: yes

#4126 VPC network custom MTU support
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/network_custom_mtu.tf.erb
Labels: cla: yes

#4124 mark nil errors as nil instead of non-retryable
  third_party/terraform/utils/retry_transport.go
Labels: cla: yes

#3108 Update doc service networking connection
  third_party/terraform/website/docs/r/service_networking_connection.html.markdown
Labels: cla: yes, community

#3938 Add maxUtilization field to hash function of BackendService
  templates/terraform/constants/backend_service.go.erb
  templates/terraform/encoders/backend_service.go.erb
  third_party/terraform/tests/resource_compute_backend_service_test.go.erb
Labels: cla: yes

#4123 Stop editing the global config object with new useragent entries
  products/appengine/terraform.yaml
  products/compute/terraform.yaml
  products/iap/terraform.yaml
  products/kms/terraform.yaml
  products/securitycenter/terraform.yaml
  templates/terraform/custom_delete/skip_delete.go.erb
  templates/terraform/resource.erb
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/resources/resource_iam_audit_config.go
  third_party/terraform/resources/resource_iam_binding.go.erb
  third_party/terraform/resources/resource_iam_member.go.erb
  third_party/terraform/resources/resource_iam_policy.go.erb
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/utils/utils.go.erb
Labels: cla: yes

#4109 added new resource bq/routine
  products/bigquery/ansible.yaml
  products/bigquery/api.yaml
  products/bigquery/inspec.yaml
  products/bigquery/terraform.yaml
  templates/terraform/custom_expand/bigquery_routine_ref.go.erb
  templates/terraform/examples/big_query_routine_basic.tf.erb
  templates/terraform/examples/big_query_routine_json.tf.erb
  third_party/terraform/tests/resource_big_query_routine_test.go
Labels: cla: yes

#4071 add iam workload identity federation
  products/iambeta/api.yaml
  products/iambeta/terraform.yaml
  templates/terraform/constants/iam_workload_identity_pool.go.erb
  templates/terraform/examples/iam_workload_identity_pool_basic.tf.erb
  templates/terraform/examples/iam_workload_identity_pool_full.tf.erb
  third_party/terraform/tests/resource_iam_beta-workload_identity_pool_id_test.go.erb
  third_party/terraform/tests/resource_iam_beta_workload_identity_pool_test.go.erb
Labels: cla: yes

#4128 Mark google_pubsub_subscription.enable_message_ordering as ForceNew
  products/pubsub/api.yaml
Labels: cla: yes

#4131 Added newline after virtual fields in documentation generation
  templates/terraform/resource.html.markdown.erb
Labels: cla: yes

#4076 Add taxonomy and policy_tag resources to data_catalog product
  products/datacatalog/api.yaml
  products/datacatalog/terraform.yaml
  provider/terraform.rb
  templates/terraform/examples/data_catalog_taxonomies_policy_tag_basic.tf.erb
  templates/terraform/examples/data_catalog_taxonomies_policy_tag_child_policies.tf.erb
  templates/terraform/examples/data_catalog_taxonomy_basic.tf.erb
  templates/terraform/iam_policy.go.erb
Labels: cla: yes

#4113 use e2 vms, part 3
  templates/terraform/examples/game_service_cluster_basic.tf.erb
  third_party/terraform/tests/resource_compute_instance_migrate_test.go
  third_party/terraform/tests/resource_compute_region_per_instance_config_test.go
  third_party/terraform/tests/resource_compute_resource_policy_test.go
  third_party/terraform/tests/resource_compute_route_test.go
  third_party/terraform/tests/resource_compute_target_pool_test.go
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/tests/resource_dataflow_job_test.go
  third_party/terraform/tests/resource_dataproc_cluster_iam_test.go
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
  third_party/terraform/tests/resource_dataproc_job_test.go
  third_party/terraform/tests/resource_network_management_connectivity_test_resource_test.go
  third_party/terraform/tests/resource_notebooks_instance_container_test.go.erb
  third_party/terraform/tests/resource_notebooks_instance_gpu_test.go.erb
  third_party/terraform/tests/resource_notebooks_instance_test.go.erb
  third_party/terraform/website/docs/d/compute_instance_serial_port.html.markdown
  third_party/terraform/website/docs/d/kms_secret_ciphertext.html.markdown
  third_party/terraform/website/docs/r/composer_environment.html.markdown
  third_party/terraform/website/docs/r/compute_attached_disk.html.markdown
  third_party/terraform/website/docs/r/compute_instance.html.markdown
  third_party/terraform/website/docs/r/compute_instance_from_template.html.markdown
  third_party/terraform/website/docs/r/compute_instance_group.html.markdown
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
  third_party/terraform/website/docs/r/logging_project_sink.html.markdown
Labels: cla: yes

#4125 relax load balancing scheme validation of region backend service
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/constants/region_backend_service.go.erb
  templates/terraform/encoders/region_backend_service.go.erb
  templates/terraform/examples/forwarding_rule_externallb.tf.erb
  templates/terraform/examples/region_backend_service_external.tf.erb
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
Labels: cla: yes

#4133 Add Build Enviroment Vars to Cloud Functions
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
  third_party/terraform/utils/utils.go.erb
  third_party/terraform/website/docs/r/cloudfunctions_function.html.markdown
Labels: cla: yes

#4140 remove danawillow from random reviewer rotation 😭 👋
  .ci/containers/contributor-checker/check-contributor.sh
Labels: cla: yes

#4139 region NEG moved to TPG
  products/compute/api.yaml
  templates/terraform/examples/region_network_endpoint_group_appengine.tf.erb
  templates/terraform/examples/region_network_endpoint_group_cloudrun.tf.erb
  templates/terraform/examples/region_network_endpoint_group_functions.tf.erb
Labels: cla: yes

#4136 Added confidential_nodes field to google_container_cluster
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#4138 update network peering custom routes
  third_party/terraform/resources/resource_compute_network_peering.go
  third_party/terraform/tests/resource_compute_network_peering_test.go
Labels: cla: yes

#4141 Don't run sql precheck if projects.get call fails
  third_party/terraform/resources/resource_service_networking_connection.go
  third_party/terraform/resources/resource_sql_database_instance.go.erb
Labels: cla: yes

#4143 Apply dsf to google_compute_health_check port value with no portspec
  templates/terraform/constants/health_check.erb
Labels: cla: yes

#4066 Add API Gateway resources
  api/resource.rb
  api/type.rb
  products/apigateway/api.yaml
  products/apigateway/terraform.yaml
  templates/terraform/examples/apigateway_api_basic.tf.erb
  templates/terraform/examples/apigateway_api_config_basic.tf.erb
  templates/terraform/examples/apigateway_api_config_full.tf.erb
  templates/terraform/examples/apigateway_api_full.tf.erb
  templates/terraform/examples/apigateway_gateway_basic.tf.erb
  templates/terraform/examples/apigateway_gateway_full.tf.erb
  templates/terraform/iam/example_config_body/api_gateway_api_config.tf.erb
  templates/terraform/resource.erb
  third_party/terraform/tests/resource_api_gateway_api_config_test.go.erb
  third_party/terraform/tests/resource_api_gateway_api_test.go.erb
  third_party/terraform/tests/resource_api_gateway_gateway_test.go.erb
  third_party/terraform/utils/test-fixtures/apigateway/openapi.yaml
Labels: cla: yes

#3873 Machine image updates
  products/compute/api.yaml
  products/compute/terraform.yaml
  third_party/terraform/resources/resource_compute_instance_from_machine_image.go.erb
  third_party/terraform/tests/resource_compute_instance_from_machine_image_test.go.erb
  third_party/terraform/utils/field_helpers.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/r/compute_instance_from_machine_image.html.markdown
Labels: cla: yes

#4144 rename test resources so they get swept
  third_party/terraform/tests/resource_compute_instance_from_template_test.go
Labels: cla: yes

#4145 add more messages to retry on for monitoring
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#4023 Added conditions to Cloud Asset Feeds
  products/cloudasset/api.yaml
  templates/terraform/examples/cloud_asset_folder_feed.tf.erb
  templates/terraform/examples/cloud_asset_organization_feed.tf.erb
  templates/terraform/examples/cloud_asset_project_feed.tf.erb
Labels: cla: yes

#3895 Add scheduleOptions to BigQuery Data Transfer
  products/bigquerydatatransfer/api.yaml
  third_party/terraform/tests/resource_bigquery_data_transfer_config_test.go
Labels: cla: yes

#4137 Add IAP Tunnel IAM Resource
  products/iap/api.yaml
  products/iap/terraform.yaml
Labels: cla: yes

#4150 Container and NodePool additions for InSpec
  products/container/api.yaml
Labels: cla: yes

#4152 Add note on referencing instance template from within stateful MIG
  templates/terraform/examples/stateful_igm.tf.erb
  templates/terraform/examples/stateful_rigm.tf.erb
Labels: cla: yes

#4148 Updated disruption budget to use API-correct percent key instead of p…
  products/osconfig/api.yaml
Labels: cla: yes

#4153 Move release channel to GA
  products/container/api.yaml
Labels: cla: yes

#3907 Add skip_initial_version_creation to kms crypto key
  products/kms/api.yaml
  products/kms/terraform.yaml
  templates/terraform/custom_delete/kms_crypto_key.erb
  templates/terraform/custom_import/kms_crypto_key.go.erb
  templates/terraform/examples/kms_key_ring_import_job.tf.erb
  templates/terraform/resource.erb
Labels: cla: yes

#4154 Remove Logging bucket location from the Docs
  third_party/terraform/resources/resource_logging_bucket_config.go
  third_party/terraform/website/docs/r/logging_billing_account_bucket_config.html.markdown
  third_party/terraform/website/docs/r/logging_folder_bucket_config.html.markdown
  third_party/terraform/website/docs/r/logging_project_bucket_config.html.markdown
Labels: cla: yes

#4151 removed Ignition Config for Container-Optimized OS
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#4146 Add support for custom info types to inspect template.
  products/dlp/api.yaml
  products/dlp/terraform.yaml
  templates/terraform/examples/dlp_inspect_template_custom_type.tf.erb
Labels: cla: yes

#4084 Allow GCB builds of downstream-builder container to use cache.
  .ci/containers/downstream-builder/Dockerfile
  .ci/gcb-downstream-builder.yml
Labels: cla: yes

#4034 Direct google access
  products/compute/api.yaml
  products/compute/terraform.yaml
Labels: cla: yes

#4157 Add MQL based alerts
  products/monitoring/api.yaml
  third_party/terraform/tests/resource_monitoring_alert_policy_test.go
Labels: cla: yes

#4156 feat(bigquery-data-transfer): add email preferences
  products/bigquerydatatransfer/api.yaml
  third_party/terraform/tests/resource_bigquery_data_transfer_config_test.go
Labels: cla: yes

#4161 Clarify description of filter_expr
  products/compute/api.yaml
Labels: cla: yes

#4165 Fix mentions of GCP products not compliant with Branding Guidelines
  third_party/terraform/resources/resource_compute_instance.go.erb
  third_party/terraform/resources/resource_compute_instance_template.go.erb
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_dataflow_job.go
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/resources/resource_storage_bucket.go
  third_party/terraform/resources/resource_storage_notification.go
Labels: cla: yes

#4162 Convert all the range values to be doubles and add a test that uses a double.
  products/monitoring/api.yaml
  templates/terraform/examples/monitoring_slo_request_based.tf.erb
Labels: cla: yes

#4164 Fix typos
  third_party/terraform/resources/resource_bigquery_table.go
  third_party/terraform/resources/resource_google_organization_iam_custom_role.go
  third_party/terraform/resources/resource_storage_transfer_job.go
  third_party/terraform/website/docs/r/bigquery_table.html.markdown
  third_party/terraform/website/docs/r/storage_transfer_job.html.markdown
Labels: cla: yes

#4127 added project service to validator
  provider/terraform_object_library.rb
  third_party/validator/project_service.go
  third_party/validator/project_service_test.go
Labels: cla: yes

#4163 Moving rake tests to cloud build
  .ci/gcb-downstream-builder.yml
  .ci/gcb-run-rake-tests.yml
  .travis.yml
Labels: cla: yes

#4168 zone attribute mandatory check removed
  third_party/terraform/resources/resource_dataflow_job.go
Labels: cla: yes

#4170 Update headers in dataproc resource iam docs.
  third_party/terraform/website/docs/r/dataproc_cluster_iam.html.markdown
  third_party/terraform/website/docs/r/dataproc_job_iam.html.markdown
Labels: cla: yes

#4174 update resources for api version v0.34.0
  third_party/terraform/resources/resource_storage_transfer_job.go
  third_party/terraform/tests/resource_storage_transfer_job_test.go
Labels: cla: yes

#4171 Add support for creating 4GB Functions
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/website/docs/r/cloudfunctions_function.html.markdown
Labels: cla: yes

#4175 Removed duplicative flaky test & related example
  products/oslogin/terraform.yaml
  templates/terraform/examples/os_login_ssh_key_basic.tf.erb
  templates/terraform/examples/os_login_ssh_key_with_project.tf.erb
Labels: cla: yes

#4167 Add support for google_project_default_service_accounts resource
  third_party/terraform/resources/resource_google_project_default_service_accounts.go
  third_party/terraform/tests/resource_google_project_default_service_accounts_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/website/docs/r/google_project_default_service_accounts.html.markdown
Labels: cla: yes
