Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2020-02, with the labels that each got.

#3065 Remove notes about base-64 encoding of secret data in markdown
  products/secretmanager/api.yaml
  third_party/terraform/data_sources/data_source_secret_manager_secret_version.go.erb
  third_party/terraform/website/docs/d/datasource_google_secret_manager_secret_version.html.markdown
Labels: cla: yes

#3052 add fine-grained resource for service perimeter resource
  products/accesscontextmanager/api.yaml
  products/accesscontextmanager/inspec.yaml
  products/accesscontextmanager/terraform.yaml
  templates/terraform/custom_import/access_context_manager_service_perimeter_resource.go.erb
  templates/terraform/examples/access_context_manager_service_perimeter_resource_basic.tf.erb
  templates/terraform/nested_query.go.erb
  templates/terraform/resource.erb
  third_party/terraform/tests/resource_access_context_manager_access_policy_test.go.erb
  third_party/terraform/tests/resource_access_context_manager_service_perimeter_resource_test.go
  third_party/terraform/utils/bootstrap_utils_test.go
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3069 Always diff $OLD $NEW instead of $NEW $OLD
  .ci/containers/github-differ/generate_comment.sh
Labels: cla: yes

#3063 have metadata item fail on create if the key is already present
  third_party/terraform/resources/resource_compute_project_metadata_item.go
  third_party/terraform/tests/resource_compute_project_metadata_item_test.go
Labels: cla: yes

#3067 Add custom_create custom code attachement.
  provider/terraform/custom_code.rb
  templates/terraform/resource.erb
Labels: cla: yes

#3068 Add note about Postgres requiring user passwords
  third_party/terraform/website/docs/r/sql_user.html.markdown
Labels: changelog: no-release-note, cla: yes

#3071 Split up TF utils.go.erb
  provider/terraform_object_library.rb
  third_party/terraform/utils/common_diff_suppress.go.erb
  third_party/terraform/utils/error_retry_predicates.go
  third_party/terraform/utils/retry_utils.go
  third_party/terraform/utils/utils.go.erb
Labels: changelog: no-release-note, cla: yes

#3070 only include PatchUpdateEncoder if the resource is updatable
  templates/terraform/nested_query.go.erb
Labels: cla: yes

#3066 no changelog on ansible or inspec
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: cla: yes

#3074 Make org iam policy warning red
  third_party/terraform/website/docs/r/google_organization_iam_policy.html.markdown
Labels: cla: yes

#3072 Change generated test vars to use sweeper prefix
  products/appengine/terraform.yaml
  products/bigtable/terraform.yaml
  products/cloudfunctions/terraform.yaml
  products/cloudrun/terraform.yaml
  products/compute/terraform.yaml
  products/dataproc/terraform.yaml
  products/dialogflow/terraform.yaml
  products/iap/terraform.yaml
  products/identityplatform/terraform.yaml
  products/secretmanager/terraform.yaml
  provider/terraform/examples.rb
Labels: changelog: no-release-note, cla: yes

#3075 Add encryption_key_name to google_sql_database_instance.
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: yes

#3073 Gcr resource
  third_party/terraform/resources/resource_container_registry.go
  third_party/terraform/tests/resource_container_registry_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/r/container_registry.html.markdown
Labels: cla: yes

#2786 Update RELEASE_NOTES_GUIDE.md
  .ci/RELEASE_NOTES_GUIDE.md
Labels: ansible, changelog: no-release-note, cla: yes, downstream-generated, inspec, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#3081 Catch new cloud run api defaults
  products/cloudrun/terraform.yaml
Labels: cla: yes

#3082 Wrap all errors so 404s can be caught
  third_party/terraform/resources/resource_google_project.go
Labels: cla: yes

#3086 Add tf-test to iam test names
  products/binaryauthorization/terraform.yaml
  products/cloudfunctions/terraform.yaml
  products/cloudrun/terraform.yaml
  products/compute/terraform.yaml
  products/deploymentmanager/terraform.yaml
  products/iap/terraform.yaml
  products/pubsub/terraform.yaml
  products/runtimeconfig/terraform.yaml
  products/secretmanager/terraform.yaml
  products/storage/terraform.yaml
Labels: cla: yes

#3079 Bump dialogflow agent tier retries
  templates/terraform/post_create/dialogflow_agent_tier.go.erb
Labels: cla: yes

#3087 update sql_database_instance_test import formatting
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
Labels: cla: yes

#3088 Bad shell syntax not caught by -e due to if tests.
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: changelog: no-release-note, cla: yes

#3083 Update `secondary_ip_range` docs for sending an empty array
  products/compute/terraform.yaml
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#3089 change error wrap formatting
  third_party/terraform/resources/resource_google_project.go
Labels: cla: yes

#3090 Correct name for iap tunnel instance generated tests
  products/iap/terraform.yaml
Labels: cla: yes

#3078 Dont return error if we cant find a default value in IAM parse import id
  templates/terraform/iam_policy.go.erb
  third_party/terraform/utils/import.go
Labels: cla: yes

#3091 Fix errors in project retries, add billinginfo retries
  third_party/terraform/resources/resource_google_project.go
Labels: cla: yes

#3044 added boot_disk_kms_key to node_config
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/resources/resource_sql_user.go
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/utils/node_config.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3077 Implement new-style resource state handling for GKE cluster
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/utils/state_util.go
Labels: cla: yes

#3093 fix sqladmin pkg and remove computed and removed
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/node_config.go.erb
Labels: cla: yes

#3094 Fix various tests from changing test prefix
  products/cloudrun/terraform.yaml
  products/vpcaccess/terraform.yaml
Labels: changelog: no-release-note, cla: yes

#3095 Set `public_key` to computed
  third_party/terraform/data_sources/data_source_google_kms_crypto_key_version.go
Labels: cla: yes

#3097 Set database and collection during import of firestore index.
  templates/terraform/custom_import/index_self_link_as_name_set_project.go.erb
Labels: cla: yes

#3096 Refactor error predicates
  third_party/terraform/utils/common_operation.go
  third_party/terraform/utils/error_retry_predicates.go
  third_party/terraform/utils/metadata.go
  third_party/terraform/utils/retry_utils.go
  third_party/terraform/utils/transport.go
  third_party/terraform/utils/utils_test.go
Labels: cla: yes

#3100 Documentation change to reflect the fact that beta provider blocks are optional.
  third_party/terraform/website/docs/guides/provider_versions.html.markdown
Labels: changelog: no-release-note, cla: yes

#3101 Fix lint from #3096
  third_party/terraform/utils/error_retry_predicates.go
Labels: changelog: no-release-note, cla: yes

#3103 Test the terraform repos after they get built.
  .ci/containers/terraform-tester/Dockerfile
  .ci/containers/terraform-tester/test_terraform.sh
  .ci/gcb-generate-diffs.yml
Labels: changelog: no-release-note, cla: yes

#3104 Upstream https://github.com/terraform-providers/terraform-provider-google/pull/5638.
  .ci/gcb-generate-diffs.yml
  third_party/terraform/website/docs/d/google_iam_policy.html.markdown
Labels: cla: yes

#3107 Make the CI machine as big as they go - the linter is huge.
  .ci/gcb-generate-diffs.yml
Labels: changelog: no-release-note, cla: yes

#3105 lint error: ineffectual assignment.
  templates/terraform/custom_flatten/secret_version_access.go.erb
Labels: cla: yes

#3106 Remove `ExactlyOneOf` restriction for `auto_provisioning_defaults`
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3099 Fix sqladmin after revendoring
  products/sql/api.yaml
  products/sql/inspec.yaml
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/resources/resource_sql_user.go
  third_party/terraform/utils/config.go.erb
Labels: changelog: no-release-note, cla: yes

#3102 Bigtable Instance changes
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/tests/resource_bigtable_instance_test.go
Labels: cla: yes

#3080 Ansible: Bigtable Instances and Clusters
  products/bigtable/ansible.yaml
  products/bigtable/ansible_version_added.yaml
  products/bigtable/api.yaml
  products/bigtable/examples/ansible/instance.yaml
  products/bigtable/helpers/ansible/instance.py
  products/bigtable/terraform.yaml
  provider/ansible/custom_code.rb
  templates/ansible/async.erb
Labels: cla: yes

#3111 Fix the SQL API URL in MM
  products/sql/api.yaml
  third_party/terraform/utils/config.go.erb
Labels: changelog: no-release-note, cla: yes

#3112 Rename inst-test networks to tf-test for sweeper
  third_party/terraform/tests/resource_compute_instance_template_test.go
  third_party/terraform/tests/resource_compute_instance_test.go
Labels: changelog: no-release-note, cla: yes

#3085 Build datastore index resource.
  api/resource.rb
  products/datastore/api.yaml
  products/datastore/terraform.yaml
  templates/terraform/examples/datastore_index.tf.erb
  templates/terraform/operation.go.erb
  templates/terraform/resource.erb
  third_party/terraform/utils/appengine_operation.go
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3076 Configure autoscaling profile in GKE clusters
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes, community

#3119 We need to flatten spanner names - previously it hadn't mattered whether we do it or not, but now since we get the name from the operation, it starts to matter.
  products/spanner/terraform.yaml
Labels: cla: yes

#3114 Add state waiting to google_container_node_pool
  third_party/terraform/resources/resource_container_node_pool.go.erb
Labels: cla: yes

#3115 Remove error status check in GKE cluster on read
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: cla: yes

#3123 Fully remove `use_ip_aliases` and `create_subnetwork`
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: cla: yes

#2318 Add endpoints service IAM
  products/servicemanagement/api.yaml
  products/servicemanagement/terraform.yaml
  templates/terraform/examples/endpoints_iam.tf.erb
  templates/terraform/resource_iam.html.markdown.erb
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/provider_handwritten_endpoint.go.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes, downstream-generated, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#3125 clarify virtual fields vs url_param_only
  api/type.rb
  overrides/terraform/resource_override.rb
  provider/terraform/virtual_fields.rb
Labels: cla: yes

#3124 Complain if the changelog isn't compliant.
  .ci/containers/changelog-checker/Dockerfile
  .ci/gcb-generate-diffs.yml
Labels: cla: yes

#3116 Add more generic error predicates
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#3127 Add docs for Secret Manager to sidebar
  templates/terraform/examples/secret_version_basic.tf.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3122 Add tests for healthcare store pubsub topic removal
  third_party/terraform/tests/resource_healthcare_dicom_store_test.go.erb
  third_party/terraform/tests/resource_healthcare_fhir_store_test.go.erb
  third_party/terraform/tests/resource_healthcare_hl7_v2_store_test.go.erb
Labels: cla: yes

#3084 Adds storage_hmac_key_resource
  products/storage/ansible.yaml
  products/storage/api.yaml
  products/storage/inspec.yaml
  products/storage/terraform.yaml
  templates/terraform/custom_check_destroy/storage_hmac_key.go.erb
  templates/terraform/decoders/storage_hmac_key.go.erb
  templates/terraform/examples/storage_hmac_key.tf.erb
  templates/terraform/post_create/storage_hmac_key.go.erb
  templates/terraform/pre_delete/storage_hmac_key.go.erb
  third_party/terraform/tests/resource_storage_hmac_key_test.go
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes, community

#3128 upstream terraform-providers/terraform-provider-google/pull/5647
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3134 Avoid panics on unit tests
  third_party/terraform/utils/bootstrap_utils_test.go
Labels: cla: yes

#3117 Terraform Data Source to get DNSKEY records of DNSSEC-signed managed zones
  products/dns/api.yaml
  third_party/terraform/data_sources/data_source_dns_keys.go
  third_party/terraform/tests/data_source_dns_key_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/d/datasource_dns_keys.html.markdown
Labels: cla: yes, community

#3132 add version field to fhir store
  products/healthcare/api.yaml
  templates/terraform/examples/healthcare_fhir_store_basic.tf.erb
Labels: cla: yes

#3139 Update go .ci containers to go 1.13
  .ci/containers/go-ruby-python/Dockerfile
  .ci/containers/go-ruby/Dockerfile
Labels: cla: yes

#3137 Upstream tpg #5695 and 5686.
  products/compute/api.yaml
  third_party/terraform/website/docs/d/datasource_compute_network.html.markdown
Labels: cla: yes

#3138 Add type field to google_dataflow_job.
  third_party/terraform/resources/resource_dataflow_job.go
  third_party/terraform/website/docs/r/dataflow_job.html.markdown
Labels: cla: yes

#3143 Make connection reset error pred more generic, debug logs
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#3146 Add decoder after OperationWaitTimeWithResponse
  templates/terraform/resource.erb
Labels: cla: yes

#3140 Update to https scheme in idp saml config tests
  templates/terraform/examples/identity_platform_inbound_saml_config_basic.tf.erb
  templates/terraform/examples/identity_platform_tenant_inbound_saml_config_basic.tf.erb
  third_party/terraform/tests/resource_identity_platform_inbound_saml_config_test.go
  third_party/terraform/tests/resource_identity_platform_tenant_indound_saml_config_test.go
Labels: cla: yes

#3141 Ansible needs elements listed in docs
  provider/ansible/documentation.rb
Labels: cla: yes

#3118 add 'PARQUET' to documentation
  third_party/terraform/website/docs/r/bigquery_table.html.markdown
Labels: cla: yes

#3144 Add check for google_compute_router bgp.advertise_mode.
  products/compute/terraform.yaml
  templates/terraform/constants/router.go.erb
  templates/terraform/resource_definition/router.go.erb
Labels: cla: yes

#3145 Google project precheck
  third_party/terraform/resources/resource_google_project.go
Labels: cla: yes

#3142 Add a datasource for google_compute_backend_bucket
  third_party/terraform/data_sources/data_source_google_compute_backend_bucket.go
  third_party/terraform/tests/data_source_google_compute_backend_bucket_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/d/datasource_google_compute_backend_bucket.html.markdown
Labels: cla: yes

#3120 add metadata to storage_bucket_object
  third_party/terraform/resources/resource_storage_bucket_object.go
  third_party/terraform/tests/resource_storage_bucket_object_test.go
  third_party/terraform/website/docs/r/storage_bucket_object.html.markdown
Labels: cla: yes

#3147 Allow `projects/` prefix for the project field in project IAM resources
  third_party/terraform/utils/iam_project.go
Labels: cla: yes

#3148 Fix markdown in KMS key docs
  third_party/terraform/website/docs/r/google_kms_crypto_key_iam.html.markdown
Labels: cla: no

#2890 Add support for range partitioning in BigQuery
  third_party/terraform/resources/resource_bigquery_table.go.erb
  third_party/terraform/tests/resource_bigquery_table_test.go.erb
  third_party/terraform/website/docs/r/bigquery_table.html.markdown
Labels: cla: yes, community

#3098 document updated with right API url for resource google_compute_forwarding_rule. Issue-#5598
  products/compute/api.yaml
Labels: cla: yes, community

#3152 fixing beta example for google_compute_region_autoscaler
  products/compute/terraform.yaml
  templates/terraform/examples/region_autoscaler_beta.tf.erb
Labels: cla: yes, community

#3153 Fetch PR number even if we writing a changelog, needed for message
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: cla: yes

#2269 App Engine Service Split Traffic resource
  products/appengine/ansible.yaml
  products/appengine/api.yaml
  products/appengine/inspec.yaml
  products/appengine/terraform.yaml
  templates/terraform/custom_check_destroy/skip_delete_during_test.go.erb
  templates/terraform/custom_flatten/float64_to_string.go.erb
  templates/terraform/examples/app_engine_service_split_traffic.tf.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes, community, downstream-generated, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#3154 Add desired_status argument to google_compute_instance
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/tests/resource_compute_instance_test.go
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#3158 Update docs - max_pods_per_node has been GA for a while.
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: cla: yes

#3161 Change storage name in resource policy doc
  products/compute/api.yaml
Labels: cla: yes

#3160 Adding support for google game services
  products/gameservices/api.yaml
  products/gameservices/terraform.yaml
  templates/terraform/constants/gameserver_cluster_custom_diff.go
  templates/terraform/custom_create/gameservice_rollout_create.go
  templates/terraform/examples/game_service_config_basic.tf.erb
  templates/terraform/examples/game_service_deployment_basic.tf.erb
  templates/terraform/examples/game_service_deployment_rollout_basic.tf.erb
  templates/terraform/examples/game_service_realm_basic.tf.erb
Labels: cla: yes

#3053 VPC serverless access update version from beta to GA
  products/vpcaccess/api.yaml
  products/vpcaccess/terraform.yaml
  templates/terraform/examples/vpc_access_connector.tf.erb
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
Labels: cla: yes, community

#3157 Add packet mirroring to beta.
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/compute_packet_mirroring_full.tf.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3169 Follow-on to packet mirroring to fix tests which failed overnight.
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/compute_packet_mirroring_full.tf.erb
Labels: cla: yes

#3167 Generate correct stats for oics
  .ci/containers/github-differ/generate_comment.sh
Labels: cla: yes

#3165 Use errwrap.Walk for connection reset error
  third_party/terraform/utils/common_operation.go
  third_party/terraform/utils/retry_utils.go
Labels: cla: yes

#3168 Remove beta-only tags, beta provider from cf vpc connector test
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
Labels: cla: yes

#3172 Remove packet mirroring from ga website.
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3159 Vcr provider test
  third_party/terraform/tests/resource_pubsub_topic_test.go
  third_party/terraform/utils/provider_test.go.erb
Labels: cla: yes

#3171 Change game server tests to google-beta
  templates/terraform/examples/game_service_config_basic.tf.erb
  templates/terraform/examples/game_service_deployment_basic.tf.erb
  templates/terraform/examples/game_service_deployment_rollout_basic.tf.erb
  templates/terraform/examples/game_service_realm_basic.tf.erb
Labels: cla: yes

#3173 Bump up default create timeout for datastore index
  products/datastore/terraform.yaml
Labels: cla: yes

#3164 5750 - fixing a typo in google_access_context_manager_service_perimeter_resource
  templates/terraform/examples/access_context_manager_service_perimeter_resource_basic.tf.erb
Labels: cla: yes, community

#3162 Remove iap base path as tunnel is generated
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/provider.go.erb
Labels: cla: yes

#3175 update the website sidebar
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3176 Tests are failing due to domain verification
  third_party/terraform/tests/resource_big_query_dataset_test.go
Labels: cla: yes

#3174 Allow id for bigtable appprofile instance
  products/bigtable/terraform.yaml
  templates/terraform/encoders/bigtable_app_profile.go.erb
  third_party/terraform/tests/resource_bigtable_app_profile_test.go
  third_party/terraform/utils/self_link_helpers.go
Labels: cla: yes

#3178 Upstream terraform-provider-google-beta#1766
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: cla: yes

#3179 Fix DNS Keys TF Data Source markdown formatting
  third_party/terraform/website/docs/d/datasource_dns_keys.html.markdown
Labels: cla: yes, community

#3180 Add mutexes to storage ACLs
  products/storage/terraform.yaml
  third_party/terraform/resources/resource_storage_bucket_acl.go
  third_party/terraform/resources/resource_storage_default_object_acl.go
  third_party/terraform/resources/resource_storage_object_acl.go
Labels: cla: yes

#3184 add rsync to docker container
  .ci/containers/go-ruby-python/Dockerfile
Labels: cla: yes

#3185 Add custom code constants to terraform conversion
  templates/terraform/objectlib/base.go.erb
Labels: cla: yes

#3181 Added check for bucket retention policy list being empty.
  third_party/terraform/resources/resource_storage_bucket.go
  third_party/validator/storage_bucket.go
Labels: cla: yes

#3183 Fix terraform-google-conversion google.golang.org/api v0.16.0 compatibility issue.
  third_party/validator/sql_database_instance.go
Labels: cla: yes

#3187 Exclude validator from copying interconnect constants
  templates/terraform/constants/interconnect_attachment.go.erb
Labels: cla: yes
