Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2020-01, with the labels that each got.

#2905 Sweeper names for VPN tunnel tests resources
  third_party/terraform/tests/resource_compute_vpn_tunnel_test.go
Labels: ansible, automerged, cla: yes, downstream-generated, inspec, terraform-provider-google, terraform-provider-google-beta

#2880 fix google_bigquery_table encryption_configuration modifications
  third_party/terraform/resources/resource_bigquery_table.go.erb
Labels: automerged, cla: yes, community, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2928 Increase CPU available to GCB job.
  .ci/gcb-push-downstream.yml
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2903 Fixed doctor links to installation and added black
  tools/doctor
Labels: automerged, cla: yes, community, downstream-generated

#2929 Add MM PR to commit message in magician v2.
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated

#2923 Allow add/removing Bigtable clusters
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/tests/resource_bigtable_instance_test.go
  third_party/terraform/website/docs/r/bigtable_instance.html.markdown
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2936 Handle cross-repo PRs.
  .ci/containers/github-differ/Dockerfile
  .ci/containers/github-differ/generate_comment.sh
  .ci/gcb-generate-diffs.yml
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2939 set master_authorized_networks_config.enabled=true ...
  third_party/validator/container.go
Labels: automerged, cla: yes, downstream-generated, terraform-google-conversion

#2930 Add sidebar entry for google_sql_ca_certs
  third_party/terraform/website-compiled/google.erb
Labels: automerged, cla: yes, community, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2952 InSpec generate SQL db instance, user
  products/sql/api.yaml
  products/sql/inspec.yaml
  templates/inspec/examples/attributes/external_attributes.yml
  templates/inspec/examples/google_sql_database_instance/google_sql_database_instance.erb
  templates/inspec/examples/google_sql_database_instance/google_sql_database_instance_attributes.erb
  templates/inspec/examples/google_sql_database_instance/google_sql_database_instances.erb
  templates/inspec/examples/google_sql_user/google_sql_user.erb
  templates/inspec/examples/google_sql_user/google_sql_user_attributes.erb
  templates/inspec/examples/google_sql_user/google_sql_users.erb
  templates/inspec/singular_resource.erb
  third_party/inspec/custom_functions/google_sql_database_instance.erb
Labels: ansible, automerged, cla: yes, downstream-generated, inspec

#2964 Change max dispatches from int to double
  products/cloudtasks/api.yaml
Labels: ansible, automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2975 Change VCR test jobs to use a seed to allow for random suffixes
  .ci/acceptance-tests/inspec-post-approve.sh
  .ci/acceptance-tests/inspec-post-merge.sh
  .ci/acceptance-tests/inspec-vcr.sh
  .ci/unit-tests/inspec.sh
  products/appengine/inspec.yaml
  templates/inspec/examples/google_appengine_standard_app_version/google_appengine_standard_app_version_attributes.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
Labels: automerged, cla: yes, downstream-generated, inspec

#2978 Fixing identifiers in inspec IAM markdown
  templates/inspec/iam_binding/iam_binding.md.erb
  templates/inspec/iam_policy/iam_policy.md.erb
Labels: automerged, cla: yes, downstream-generated, inspec, terraform-provider-google, terraform-provider-google-beta

#2980 Fix TestAccContainerCluster_misc, add alpha cluster test
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#2982 Inspec alert policy
  overrides/inspec/resource_override.rb
  products/monitoring/inspec.yaml
  templates/inspec/doc_template.md.erb
  templates/inspec/examples/google_project_alert_policy/google_project_alert_policies.erb
  templates/inspec/examples/google_project_alert_policy/google_project_alert_policy.erb
  templates/inspec/examples/google_project_alert_policy/google_project_alert_policy_attributes.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
  third_party/inspec/custom_functions/alert_policy.erb
  third_party/inspec/documentation/alert_policies.md
  third_party/inspec/documentation/alert_policy_examples.md
Labels: automerged, cla: yes, downstream-generated, inspec

#2989 Expand boot disk name to full name during instance from template creation
  third_party/terraform/resources/resource_compute_instance_from_template.go
  third_party/terraform/tests/resource_compute_instance_from_template_test.go
Labels: automerged, cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#3002 bugfix for occasional generation failure.
  .ci/containers/downstream-builder/generate_downstream.sh
  .ci/gcb-generate-diffs.yml
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated

#3009 Ensure a merge commit exists so that we can diff both sides of it.
  .ci/gcb-generate-diffs.yml
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated

#3012 Allow Version and Scopes to use overrides
  api/object.rb
  api/product/version.rb
Labels: automerged, cla: yes, downstream-generated

#3006 Ensure that there are no jams in the downstream pusher, even if a build takes a long time to generate.
  .ci/gcb-push-downstream.yml
Labels: automerged, changelog: no-release-note, cla: yes, downstream-generated

#3011 Fix changelog template.
  .ci/release-note.tmpl
Labels: automerged, cla: yes, downstream-generated

#3023 Direct merges to master instead of downstream-master.
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: cla: yes

#3022 Convert compute image with switching constructor to MM
  overrides/inspec/resource_override.rb
  products/compute/api.yaml
  products/compute/inspec.yaml
  templates/inspec/examples/google_compute_image/google_compute_image.erb
  templates/inspec/examples/google_compute_image/google_compute_image_attributes.erb
  templates/inspec/singular_resource.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
  third_party/inspec/custom_functions/compute_image_custom_constructor.erb
Labels: cla: yes, downstream-generated, inspec, terraform-provider-google-beta

#3013 Add support for google_compute_project_info to inspec to migrate
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  templates/inspec/examples/google_compute_project_info/google_compute_project_info.erb
  templates/inspec/examples/google_compute_project_info/google_compute_project_info_attributes.erb
  third_party/inspec/custom_functions/google_compute_project_info.erb
Labels: cla: yes, downstream-generated, inspec

#3021 Migrate organizations. Need support for POST verb in MM plural resources
  overrides/inspec/resource_override.rb
  products/resourcemanager/inspec.yaml
  templates/inspec/examples/google_organization/google_organization.erb
  templates/inspec/examples/google_organization/google_organization_attributes.erb
  templates/inspec/examples/google_organization/google_organizations.erb
  templates/inspec/plural_resource.erb
Labels: cla: yes, downstream-generated, inspec

#3024 Magician signoff on commits
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: cla: yes

#2902 Fix terraform doc website rendering
  third_party/terraform/website/docs/r/compute_instance_from_template.html.markdown
Labels: cla: yes, community

#2877 Fixed file permissions
  third_party/terraform/website/docs/r/app_engine_application.html.markdown
  third_party/terraform/website/docs/r/google_project.html.markdown
Labels: cla: yes, community

#2996 Add error if boot disk specified on non-first disk in instance template
  third_party/terraform/resources/resource_compute_instance_template.go
Labels: cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#3026 Add support for new beta non-rfc fields in dns managed zone
  products/dns/api.yaml
  products/dns/terraform.yaml
  templates/terraform/custom_expand/bool_to_object.go.erb
  templates/terraform/custom_flatten/object_to_bool.go.erb
  third_party/terraform/tests/resource_dns_managed_zone_test.go.erb
Labels: cla: yes

#3029 Move IAM resources to their pre-MM namespaces
  products/iam/inspec.yaml
  templates/inspec/examples/google_iam_service_account/google_iam_service_account.erb
  templates/inspec/examples/google_iam_service_account_key/google_iam_service_account_key.erb
  templates/inspec/examples/google_iam_service_account_key/google_iam_service_account_keys.erb
  templates/inspec/examples/google_project_iam_custom_role/google_project_iam_custom_role.erb
  templates/inspec/examples/google_project_iam_custom_role/google_project_iam_custom_role_attributes.erb
  templates/inspec/examples/google_project_iam_custom_role/google_project_iam_custom_roles.erb
  templates/inspec/examples/google_service_account/google_service_account.erb
  templates/inspec/examples/google_service_account/google_service_account_attributes.erb
  templates/inspec/examples/google_service_account/google_service_accounts.erb
  templates/inspec/examples/google_service_account_key/google_service_account_key.erb
  templates/inspec/examples/google_service_account_key/google_service_account_key_attributes.erb
  templates/inspec/examples/google_service_account_key/google_service_account_keys.erb
Labels: cla: yes

#3018 Highlight Legacy Stackdriver and New Stackdriver for GKE in documentation
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes, community, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#3032 Additional note: role_id must be camel case
  third_party/terraform/website/docs/r/google_project_iam_custom_role.html.markdown
Labels: cla: no

#3027 The beta API is deprecated - move to ga only.
  products/binaryauthorization/api.yaml
  products/binaryauthorization/terraform.yaml
  templates/terraform/decoders/binauth_attestor_note_field_name.go.erb
  templates/terraform/encoders/binauth_attestor_note_field_name.go.erb
Labels: cla: yes

#3030 Ignore reverse_lookup in managed zone datasource test
  third_party/terraform/tests/data_source_dns_managed_zone_test.go.erb
Labels: changelog: no-release-note, cla: yes

#3034 updated expiration_time in tests to use year < 2038, undeprecated it
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: yes

#3028 Move expr to GA
  third_party/terraform/resources/resource_compute_security_policy.go.erb
Labels: cla: yes

#3036 Exclude various generation types from OiCS repo
  provider/terraform_oics.rb
Labels: changelog: no-release-note, cla: yes

#3035 update bigquery_options to be O+C
  third_party/terraform/resources/resource_logging_sink.go
Labels: cla: yes

#3038 Don't delete old changelog entries.
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: changelog: no-release-note, cla: yes

#3037 Fix notification channel test
  third_party/terraform/tests/data_source_monitoring_notification_channel_test.go
Labels: changelog: no-release-note, cla: yes

#3040 Add docs for the id field
  templates/terraform/resource.html.markdown.erb
Labels: changelog: no-release-note, cla: yes

#3031 Add storage object plural support
  products/storage/api.yaml
Labels: cla: yes

#3042 fix dataproc cluster with accelerators test
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
Labels: cla: yes

#3045 Upstream additional validation for cloud router.
  products/compute/terraform.yaml
  third_party/terraform/utils/validation.go
Labels: cla: yes

#3046 Add containers for OiCS generation
  .ci/containers/downstream-builder/generate_downstream.sh
  .ci/containers/github-differ/generate_comment.sh
Labels: changelog: no-release-note, cla: yes

#3047 Add OiCS YAML
  .ci/gcb-generate-diffs.yml
  .ci/gcb-push-downstream.yml
Labels: changelog: no-release-note, cla: yes

#3039 Bootstrap network for redis tests
  products/cloudfunctions/terraform.yaml
  products/redis/terraform.yaml
  provider/terraform/examples.rb
  templates/terraform/examples/base_configs/test_file.go.erb
  templates/terraform/examples/cloudfunctions_cloud_function.tf.erb
  templates/terraform/examples/redis_instance_full.tf.erb
  templates/terraform/iam/iam_context.go.erb
  third_party/terraform/tests/resource_service_networking_connection_test.go
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
  third_party/terraform/utils/bootstrap_utils_test.go
Labels: cla: yes

#3054 Capture subshell output for OiCS
  .ci/containers/github-differ/generate_comment.sh
Labels: cla: yes

#3056 Forcing ASN validation to int64
  third_party/terraform/tests/resource_compute_router_test.go
  third_party/terraform/utils/validation.go
Labels: cla: yes

#3051 Fix cluster tests versions
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: changelog: no-release-note, cla: yes

#3049 Add one line diff summary over-the-fold
  .ci/containers/github-differ/generate_comment.sh
Labels: changelog: no-release-note, cla: yes

#3058 Add support for IAP in google_app_engine_application resource
  third_party/terraform/resources/resource_app_engine_application.go
  third_party/terraform/tests/resource_app_engine_application_test.go
Labels: cla: yes

#3057 handle case where bigtable development instances have one node
  third_party/terraform/resources/resource_bigtable_instance.go
Labels: cla: yes

#3041 update container_cluster.html.markdown and storage_bucket.html.markdown
  third_party/terraform/website/docs/r/container_cluster.html.markdown
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
Labels: cla: yes, community

#3014 Add Dialogflow Agent resource
  products/dialogflow/api.yaml
  products/dialogflow/terraform.yaml
  templates/terraform/examples/dialogflow_agent_full.tf.erb
  templates/terraform/post_create/dialogflow_agent_tier.go.erb
  third_party/terraform/tests/resource_dialogflow_agent_test.go.erb
Labels: cla: yes, downstream-generated, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#3033 Add conditional validation, allow sending empty capacity scaler for regional backend service
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/constants/migrate_state_noop.go.erb
  templates/terraform/constants/region_backend_service.go.erb
  templates/terraform/encoders/region_backend_service.go.erb
  templates/terraform/examples/forwarding_rule_http_lb.tf.erb
  templates/terraform/examples/region_backend_service_balancing_mode.tf.erb
  templates/terraform/resource_definition/region_backend_service.go.erb
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
  third_party/terraform/utils/utils.go.erb
Labels: cla: yes

#3062 update tests that are still using first gen sql instances
  templates/terraform/examples/cloud_run_service_sql.tf.erb
  templates/terraform/examples/sql_database_basic.tf.erb
  third_party/terraform/resources/resource_sql_ssl_cert_test.go
  third_party/terraform/tests/resource_sql_database_test.go
  third_party/terraform/tests/resource_sql_user_test.go
  third_party/terraform/website/docs/d/google_kms_secret.html.markdown
  third_party/terraform/website/docs/r/sql_ssl_cert.html.markdown
  third_party/terraform/website/docs/r/sql_user.html.markdown
Labels: cla: yes

#3064 Fix post create lint error
  templates/terraform/post_create/dialogflow_agent_tier.go.erb
Labels: changelog: no-release-note, cla: yes
