Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2020-04, with the labels that each got.

#3325 Add org id to attributes as it is required in privileged resources
  templates/inspec/examples/google_appengine_standard_app_version/google_appengine_standard_app_version_attributes.erb
  templates/inspec/examples/google_kms_crypto_key/google_kms_crypto_key_attributes.erb
  templates/inspec/examples/google_kms_key_ring/google_kms_key_ring_attributes.erb
  templates/inspec/examples/google_logging_project_exclusion/google_logging_project_exclusion_attributes.erb
  templates/inspec/examples/google_logging_project_sink/google_logging_project_sink_attributes.erb
  templates/inspec/examples/google_project_iam_custom_role/google_project_iam_custom_role_attributes.erb
  templates/inspec/examples/google_service_account/google_service_account_attributes.erb
  templates/inspec/examples/google_service_account_key/google_service_account_key_attributes.erb
  templates/inspec/examples/google_storage_bucket_acl/google_storage_bucket_acl_attributes.erb
  templates/inspec/examples/google_storage_bucket_object/google_storage_bucket_object_attributes.erb
  templates/inspec/examples/google_storage_default_object_acl/google_storage_default_object_acl_attributes.erb
  templates/inspec/examples/google_storage_object_acl/google_storage_object_acl_attributes.erb
Labels: cla: yes

#3319 Add 'resources' reading and 'location_id' setting on Firebase Project
  products/firebase/api.yaml
  products/firebase/terraform.yaml
  templates/terraform/examples/firebase_project_location_basic.tf.erb
Labels: cla: yes, community

#3326 Define error if there are no settable fields
  templates/terraform/resource.erb
Labels: cla: yes

#3328 adding firebase location to side bar
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3221 init os-login sshkey
  products/oslogin/api.yaml
  products/oslogin/terraform.yaml
  provider/terraform/examples.rb
  templates/terraform/examples/os_login_ssh_key_provided_user.tf.erb
  templates/terraform/post_create/sshkeyfingerprint.go.erb
  third_party/terraform/data_sources/data_source_google_client_openid_userinfo.go
  third_party/terraform/utils/test-fixtures/ssh_rsa.pub
  third_party/terraform/utils/userinfo.go
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes, community

#3327 Add mutex for all app engine app resources
  products/appengine/terraform.yaml
  third_party/terraform/resources/resource_app_engine_application.go
Labels: cla: yes

#3312 add bigquery_dataset_access fine-grained resource
  products/bigquery/ansible.yaml
  products/bigquery/api.yaml
  products/bigquery/inspec.yaml
  products/bigquery/terraform.yaml
  templates/terraform/examples/bigquery_dataset_access_basic_user.tf.erb
  templates/terraform/examples/bigquery_dataset_access_view.tf.erb
  templates/terraform/nested_query.go.erb
  templates/terraform/post_create/lien.erb
  templates/terraform/pre_delete/compute_disk_resource_policies_attachment.go.erb
  templates/terraform/pre_delete/compute_network_endpoint.go.erb
  templates/terraform/pre_delete/compute_region_disk_resource_policies_attachment.go.erb
  templates/terraform/resource.erb
  third_party/terraform/tests/resource_bigquery_dataset_access_test.go
Labels: cla: yes

#3334 Fix and update TestAccDialogflowAgent_update
  third_party/terraform/tests/resource_dialogflow_agent_test.go.erb
Labels: cla: yes

#3330 make ipv4_enabled default to true
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
Labels: cla: yes

#3337 Bump GKE API reference to beta
  third_party/terraform/website/docs/r/container_cluster.html.markdown
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: cla: yes

#3338 Add bigquery_dataset_access to sidebar
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3336 Storage bucket: Surface non-retryable object delete error
  third_party/terraform/resources/resource_storage_bucket.go
  third_party/terraform/tests/resource_storage_bucket_test.go
Labels: cla: yes, community

#3343 doc: Fix "regions and regions" into "regions and zones"
  third_party/terraform/website/docs/d/google_compute_regions.html.markdown
Labels: cla: yes

#3342 candidate subnets ignore read, admin enabled computed
  products/compute/api.yaml
  products/compute/terraform.yaml
Labels: cla: yes

#3345 Upstream https://github.com/terraform-providers/terraform-provider-google/pull/6033
  products/compute/api.yaml
Labels: cla: yes

#3329 [Upstream] Standardize google_compute_instance import
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#3349 d.Set default parameters
  templates/terraform/iam_policy.go.erb
Labels: cla: yes

#3285 Dialogflow Intent Resource
  products/dialogflow/api.yaml
  products/dialogflow/terraform.yaml
  templates/terraform/custom_import/self_link_as_name_set_project.go.erb
  templates/terraform/examples/dialogflow_intent_basic.tf.erb
  templates/terraform/examples/dialogflow_intent_full.tf.erb
  third_party/terraform/tests/resource_dialogflow_intent_test.go.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3350 move deleted project check into project service read
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/resources/resource_google_project_service.go
Labels: cla: yes

#3339 Add support for multiple formats for pubsub refs in source repo
  overrides/terraform/property_override.rb
  products/sourcerepo/api.yaml
  products/sourcerepo/terraform.yaml
  templates/terraform/expand_property_method.erb
  templates/terraform/schema_property.erb
  third_party/terraform/utils/pubsub_utils.go
  third_party/terraform/utils/source_repo_utils.go
  third_party/terraform/utils/utils.go.erb
Labels: cla: yes

#3352 use scheduling from template rather than instance defaults
  third_party/terraform/resources/resource_compute_instance_from_template.go
  third_party/terraform/tests/resource_compute_instance_from_template_test.go
Labels: cla: yes

#3353 VPC SC dry-run mode
  products/accesscontextmanager/api.yaml
  products/accesscontextmanager/terraform.yaml
  templates/terraform/examples/access_context_manager_service_perimeter_basic.tf.erb
  templates/terraform/examples/access_context_manager_service_perimeter_dry-run.tf.erb
  third_party/terraform/tests/resource_access_context_manager_service_perimeter_test.go.erb
Labels: cla: yes

#3356 Copy source_repo_utils to mapper
  provider/terraform_object_library.rb
Labels: cla: yes

#3354 treat project 404s correctly in project service read
  third_party/terraform/resources/resource_google_project_service.go
Labels: cla: yes

#3355 remove ForceNew for dns_cache_config
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: cla: yes

#3332 Allow enabling IAP in google_app_engine_application.
  third_party/terraform/resources/resource_app_engine_application.go
  third_party/terraform/tests/resource_app_engine_application_test.go
Labels: cla: yes, community

#3341 Add monitoring service resource, datasource for app engine
  products/monitoring/api.yaml
  products/monitoring/inspec.yaml
  products/monitoring/terraform.yaml
  templates/terraform/encoders/monitoring_service.go.erb
  templates/terraform/examples/monitoring_service_custom.tf.erb
  third_party/terraform/data_sources/data_source_monitoring_service.go
  third_party/terraform/data_sources/data_source_monitoring_service_app_engine.go
  third_party/terraform/data_sources/data_source_monitoring_service_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/d/datasource_monitoring_app_engine_service.html.markdown
Labels: cla: yes

#3358 Remove references to submodules from OiCS tutorial
  .gitignore
  TUTORIAL.md
Labels: cla: yes

#3295 Added TF Validator support for GKE Workload Identity
  third_party/validator/container.go
Labels: cla: yes, community

#3359 Upstream docs change about source for instance template
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
Labels: cla: yes

#3364 Inspec bucket labels
  products/storage/api.yaml
  templates/inspec/examples/google_storage_bucket/google_storage_bucket.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
Labels: cla: yes

#3365 make display name optional on monitoring notification channel
  products/monitoring/api.yaml
Labels: cla: yes

#3333 Global NEG
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  templates/terraform/custom_import/compute_global_network_endpoint.go.erb
  templates/terraform/decoders/network_endpoint.go.erb
  templates/terraform/decoders/unwrap_global_neg.go.erb
  templates/terraform/encoders/compute_global_network_endpoint.go.erb
  templates/terraform/examples/global_network_endpoint.tf.erb
  templates/terraform/examples/global_network_endpoint_group.tf.erb
  templates/terraform/examples/global_network_endpoint_group_ip_address.tf.erb
  templates/terraform/post_create/global_network_endpoint_group.go.erb
  templates/terraform/pre_delete/compute_global_network_endpoint.go.erb
  third_party/terraform/tests/resource_compute_global_network_endpoint_test.go.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3348 add new project for app engine flex tests
  products/appengine/terraform.yaml
  templates/terraform/examples/app_engine_flexible_app_version.tf.erb
  third_party/terraform/tests/resource_app_engine_flexible_app_version_test.go
Labels: cla: yes

#3340 Add Firebase WebApp resource
  products/firebase/api.yaml
  products/firebase/terraform.yaml
  templates/terraform/examples/firebase_web_app_basic.tf.erb
  templates/terraform/resource.erb
  third_party/terraform/data_sources/data_source_google_firebase_web_app.go.erb
  third_party/terraform/data_sources/data_source_google_firebase_web_app_config.go.erb
  third_party/terraform/tests/resource_firebase_web_app_test.go.erb
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/d/datasource_firebase_web_app.html.markdown
  third_party/terraform/website/docs/d/datasource_firebase_web_app_config.html.markdown
Labels: cla: yes, community

#3370 Added name field to both custom project and org roles
  third_party/terraform/resources/resource_google_organization_iam_custom_role.go
  third_party/terraform/resources/resource_google_project_iam_custom_role.go
  third_party/terraform/website/docs/r/google_organization_iam_custom_role.html.markdown
  third_party/terraform/website/docs/r/google_project_iam.html.markdown
  third_party/terraform/website/docs/r/google_project_iam_custom_role.html.markdown
Labels: cla: yes, community

#3374 Remove missed status check in nodepool
  third_party/terraform/resources/resource_container_node_pool.go.erb
Labels: cla: yes

#3372 Add compute security policy to inspec
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/inspec/examples/google_compute_security_policy/google_compute_security_policies.erb
  templates/inspec/examples/google_compute_security_policy/google_compute_security_policy.erb
  templates/inspec/examples/google_compute_security_policy/google_compute_security_policy_attributes.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
Labels: cla: yes

#3363 Add initial monitoring SLO resource
  products/monitoring/api.yaml
  products/monitoring/inspec.yaml
  products/monitoring/terraform.yaml
  templates/terraform/constants/monitoring_slo.go.erb
  templates/terraform/custom_expand/days_to_duration_string.go.erb
  templates/terraform/custom_flatten/duration_string_to_days.go.erb
  templates/terraform/encoders/monitoring_slo.go.erb
  templates/terraform/examples/monitoring_slo_appengine.tf.erb
  templates/terraform/update_mask.erb
  third_party/terraform/tests/resource_monitoring_slo_test.go
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3375 Dataproc Cluster: Preserve preemptible config fields when preeemptible group removed.
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
Labels: cla: yes

#3380 Fix firebase webapp examples
  templates/terraform/examples/firebase_web_app_basic.tf.erb
Labels: cla: yes

#3256 Placement policy support for Compute Instance
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/resource_policy_placement_policy.tf.erb
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/tests/resource_compute_instance_test.go
  third_party/terraform/tests/resource_compute_resource_policy_test.go
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#3384 Add encryption, retention policy to buckets
  products/storage/ansible.yaml
  products/storage/api.yaml
  templates/inspec/examples/google_storage_bucket/google_storage_bucket.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  third_party/inspec/documentation/google_service_account_keys.md
Labels: cla: yes

#3331 adding bigquery job
  products/bigquery/ansible.yaml
  products/bigquery/api.yaml
  products/bigquery/inspec.yaml
  products/bigquery/terraform.yaml
  templates/terraform/encoders/bigquery_job.go.erb
  templates/terraform/examples/bigquery_job_copy.tf.erb
  templates/terraform/examples/bigquery_job_extract.tf.erb
  templates/terraform/examples/bigquery_job_load.tf.erb
  templates/terraform/examples/bigquery_job_query.tf.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3386 Changes for upgraded googleapi library
  third_party/terraform/resources/resource_sql_database_instance.go.erb
Labels: cla: yes

#3261 Support custom schema in Healthcare HL7 V2 stores
  products/healthcare/api.yaml
  products/healthcare/terraform.yaml
  templates/terraform/custom_expand/healthcare_hl7_v2_store_schema.erb
  templates/terraform/custom_flatten/healthcare_hl7_v2_store_schema.erb
  templates/terraform/examples/healthcare_hl7_v2_store_basic.tf.erb
  templates/terraform/examples/healthcare_hl7_v2_store_parser_config.tf.erb
  third_party/terraform/tests/resource_healthcare_hl7_v2_store_test.go.erb
Labels: cla: yes

#3385 fixed time_update attribute in example
  third_party/inspec/documentation/google_storage_bucket_object.md
Labels: cla: yes, community

#3371 Service Directory resources
  products/servicedirectory/api.yaml
  products/servicedirectory/terraform.yaml
  templates/terraform/custom_import/service_directory_endpoint.go.erb
  templates/terraform/custom_import/service_directory_namespace.go.erb
  templates/terraform/custom_import/service_directory_service.go.erb
  templates/terraform/examples/service_directory_endpoint_basic.tf.erb
  templates/terraform/examples/service_directory_namespace_basic.tf.erb
  templates/terraform/examples/service_directory_service_basic.tf.erb
  templates/terraform/resource.erb
  templates/terraform/resource.html.markdown.erb
  third_party/terraform/tests/resource_service_directory_endpoint_test.go.erb
  third_party/terraform/tests/resource_service_directory_namespace_test.go.erb
  third_party/terraform/tests/resource_service_directory_service_test.go.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes, enhancement

#3389 skip SecretVersion sweeper
  products/secretmanager/terraform.yaml
Labels: cla: yes

#3391 Restructure google.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3395 Reapply bigtable patch
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/website/docs/r/bigtable_instance.html.markdown
Labels: cla: yes

#3392 GKE Addon for Compute Engine persistent disk CSI Driver
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes, community

#3388 Add sleep so google_project is ready before returning
  third_party/terraform/resources/resource_google_project.go
Labels: cla: yes

#3390 remove bad html for website sidebar
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3396 Add transformation of SQL DB read error so HandleNotFound works
  overrides/terraform/resource_override.rb
  products/sql/terraform.yaml
  templates/terraform/resource.erb
  third_party/terraform/utils/sql_utils.go
Labels: cla: yes

#3397 force send boolean backup fields
  third_party/terraform/resources/resource_sql_database_instance.go.erb
Labels: cla: yes

#3377 Promote healthcare resources to GA
  products/healthcare/api.yaml
  products/healthcare/terraform.yaml
  templates/stackdriver.json
  templates/terraform/examples/healthcare_dataset_basic.tf.erb
  templates/terraform/examples/healthcare_dicom_store_basic.tf.erb
  templates/terraform/examples/healthcare_fhir_store_basic.tf.erb
  templates/terraform/examples/healthcare_hl7_v2_store_basic.tf.erb
  third_party/terraform/tests/resource_healthcare_dataset_iam_test.go
  third_party/terraform/tests/resource_healthcare_dataset_test.go
  third_party/terraform/tests/resource_healthcare_dicom_store_iam_test.go
  third_party/terraform/tests/resource_healthcare_dicom_store_test.go
  third_party/terraform/tests/resource_healthcare_fhir_store_iam_test.go
  third_party/terraform/tests/resource_healthcare_fhir_store_test.go
  third_party/terraform/tests/resource_healthcare_hl7_v2_store_iam_test.go
  third_party/terraform/tests/resource_healthcare_hl7_v2_store_test.go
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/healthcare_utils.go
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3394 change affected AtLeastOneOfs back to ExactlyOneOf
  products/compute/api.yaml
  third_party/terraform/resources/resource_google_organization_policy.go
  third_party/terraform/tests/resource_compute_health_check_test.go
  third_party/terraform/tests/resource_compute_region_health_check_test.go.erb
Labels: cla: yes

#3398 Service Directory Cloud DNS integration
  products/dns/api.yaml
  products/dns/terraform.yaml
  templates/terraform/custom_expand/sd_full_url.erb
  templates/terraform/custom_flatten/full_to_relative_path.erb
  templates/terraform/examples/dns_managed_zone_service_directory.tf.erb
Labels: cla: yes, enhancement

#3399 more product renames
  api/product.rb
  products/accesscontextmanager/api.yaml
  products/bigquerydatatransfer/api.yaml
  products/bigqueryreservation/api.yaml
  products/bigtable/api.yaml
  products/dataproc/api.yaml
  products/datastore/api.yaml
  products/deploymentmanager/api.yaml
  products/filestore/api.yaml
  products/firestore/api.yaml
  products/gameservices/api.yaml
  products/kms/api.yaml
  products/logging/api.yaml
  products/monitoring/api.yaml
  products/redis/api.yaml
  products/runtimeconfig/api.yaml
  products/securitycenter/api.yaml
  products/servicedirectory/api.yaml
  products/servicemanagement/api.yaml
  templates/inspec/iam_binding/iam_binding.erb
  templates/inspec/iam_policy/iam_policy.erb
  templates/inspec/singular_resource.erb
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/d/datasource_compute_lb_ip_ranges.html.markdown
  third_party/terraform/website/docs/d/datasource_google_secret_manager_secret_version.html.markdown
  third_party/terraform/website/docs/d/datasource_tpu_tensorflow_versions.html.markdown
  third_party/terraform/website/docs/d/google_compute_default_service_account.html.markdown
  third_party/terraform/website/docs/d/google_compute_resource_policy.html.markdown
  third_party/terraform/website/docs/d/google_kms_crypto_key.html.markdown
  third_party/terraform/website/docs/d/google_kms_crypto_key_version.html.markdown
  third_party/terraform/website/docs/d/google_kms_key_ring.html.markdown
  third_party/terraform/website/docs/d/google_kms_secret.html.markdown
  third_party/terraform/website/docs/d/google_kms_secret_ciphertext.html.markdown
  third_party/terraform/website/docs/d/google_storage_project_service_account.html.markdown
  third_party/terraform/website/docs/d/google_storage_transfer_project_service_account.html.markdown
  third_party/terraform/website/docs/r/bigtable_gc_policy.html.markdown
  third_party/terraform/website/docs/r/bigtable_instance.html.markdown
  third_party/terraform/website/docs/r/bigtable_instance_iam.html.markdown
  third_party/terraform/website/docs/r/bigtable_table.html.markdown
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
  third_party/terraform/website/docs/r/dataproc_cluster_iam.html.markdown
  third_party/terraform/website/docs/r/dataproc_job.html.markdown
  third_party/terraform/website/docs/r/dataproc_job_iam.html.markdown
  third_party/terraform/website/docs/r/google_kms_crypto_key_iam.html.markdown
  third_party/terraform/website/docs/r/google_kms_key_ring_iam.html.markdown
  third_party/terraform/website/docs/r/storage_transfer_job.html.markdown
Labels: cla: yes

#3403 Add example for managed ssl certificate
  products/compute/terraform.yaml
  templates/terraform/examples/managed_ssl_certificate_recreation.tf.erb
Labels: cla: yes

#3401 Instance sweeper
  third_party/terraform/tests/data_source_google_compute_instance_test.go
  third_party/terraform/tests/resource_compute_instance_group_test.go
  third_party/terraform/tests/resource_compute_instance_test.go
  third_party/terraform/tests/resource_compute_network_endpoint_test.go.erb
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_route_test.go
  third_party/terraform/tests/resource_compute_target_pool_test.go
Labels: cla: yes

#3360 Added Artifact Registry product
  products/artifactregistry/api.yaml
  products/artifactregistry/terraform.yaml
  templates/terraform/examples/artifact_registry_repository_basic.tf.erb
  templates/terraform/examples/artifact_registry_repository_iam.tf.erb
  third_party/terraform/utils/import.go
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3406 don't check the changelog until after tests have run
  .ci/gcb-generate-diffs.yml
Labels: cla: yes

#3393 add note in docs to generated sensitive fields
  api/resource.rb
  api/type.rb
  compiler.rb
  products/compute/terraform.yaml
  templates/terraform/property_documentation.erb
  templates/terraform/resource.html.markdown.erb
Labels: cla: yes

#3408 add healthcare iam resources to GA
  third_party/terraform/utils/iam_healthcare_dataset.go
  third_party/terraform/utils/iam_healthcare_dicom_store.go
  third_party/terraform/utils/iam_healthcare_fhir_store.go
  third_party/terraform/utils/iam_healthcare_hl7_v2_store.go
  third_party/terraform/utils/provider.go.erb
Labels: cla: yes

#3373 adds scaling properties to appengine standard version
  products/appengine/api.yaml
  products/appengine/terraform.yaml
  templates/terraform/examples/app_engine_standard_app_version.tf.erb
  third_party/terraform/tests/resource_app_engine_standard_app_version_test.go
Labels: cla: yes, community

#3409 more sidebar fixes
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/d/datasource_google_monitoring_uptime_check_ips.html.markdown
  third_party/terraform/website/docs/d/datasource_monitoring_app_engine_service.html.markdown
  third_party/terraform/website/docs/d/datasource_monitoring_notification_channel.html.markdown
  third_party/terraform/website/docs/r/logging_billing_account_exclusion.html.markdown
  third_party/terraform/website/docs/r/logging_billing_account_sink.html.markdown
  third_party/terraform/website/docs/r/logging_folder_exclusion.html.markdown
  third_party/terraform/website/docs/r/logging_folder_sink.html.markdown
  third_party/terraform/website/docs/r/logging_organization_exclusion.html.markdown
  third_party/terraform/website/docs/r/logging_organization_sink.html.markdown
  third_party/terraform/website/docs/r/logging_project_exclusion.html.markdown
  third_party/terraform/website/docs/r/logging_project_sink.html.markdown
  third_party/terraform/website/docs/r/runtimeconfig_config.html.markdown
  third_party/terraform/website/docs/r/runtimeconfig_variable.html.markdown
Labels: cla: yes

#3378 Update urlRedirect property of UrlMap and RegionUrlMap
  products/compute/api.yaml
Labels: cla: yes, community

#3411 allow updating bigtable table column families
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/resources/resource_bigtable_table.go
  third_party/terraform/tests/resource_bigtable_table_test.go
  third_party/terraform/website/docs/r/bigtable_instance.html.markdown
  third_party/terraform/website/docs/r/bigtable_table.html.markdown
Labels: cla: yes

#3412 remove sweepers for healthcare datastores as they'll be swept by the dataset sweepers
  products/healthcare/terraform.yaml
Labels: cla: yes

#3407 Changing Ansible Remote
  .ci/containers/downstream-builder/generate_downstream.sh
  .ci/containers/github-differ/generate_comment.sh
Labels: cla: yes

#3414 generate the sidebar
  .ci/containers/downstream-builder/generate_downstream.sh
  provider/terraform/common~compile.yaml
  third_party/terraform/scripts/sidebar/sidebar.go
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/google.erb.tmpl
Labels: cla: yes

#3416 Docs on fixing the magician.
  .ci/README.md
Labels: cla: yes

#3417 Allow fields to be removed at a specific version
  api/type.rb
  products/healthcare/api.yaml
  provider/terraform/sub_template.rb
  templates/terraform/examples/healthcare_hl7_v2_store_basic.tf.erb
  templates/terraform/schema_property.erb
  third_party/terraform/tests/resource_healthcare_hl7_v2_store_test.go
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/iam_healthcare_dataset.go
  third_party/terraform/utils/iam_healthcare_dicom_store.go
  third_party/terraform/utils/iam_healthcare_fhir_store.go
  third_party/terraform/utils/iam_healthcare_hl7_v2_store.go
Labels: cla: yes

#3413 Remove chrisst from list of random reviewers
  .ci/magic-modules/welcome-contributor.sh
Labels: cla: yes

#3404 Add enum values generation to documentation
  products/accesscontextmanager/api.yaml
  products/appengine/api.yaml
  products/bigquery/api.yaml
  products/compute/api.yaml
  products/compute/terraform.yaml
  products/datastore/api.yaml
  products/dns/api.yaml
  products/firestore/api.yaml
  products/healthcare/api.yaml
  products/redis/api.yaml
  products/sql/api.yaml
  provider/inspec.rb
  templates/terraform/property_documentation.erb
  templates/terraform/schema_property.erb
Labels: cla: yes

#3419 add id's to sweeper templates
  products/bigquery/terraform.yaml
  products/dataproc/api.yaml
  products/iap/terraform.yaml
  products/identityplatform/terraform.yaml
  provider/terraform.rb
  templates/terraform/sweeper_file.go.erb
Labels: cla: yes

#3410 Use ResourceIamPolicy for google_project_iam_policy
  third_party/terraform/resources/resource_google_project_iam_policy.go.erb
  third_party/terraform/resources/resource_google_project_migrate.go
  third_party/terraform/tests/resource_google_project_iam_policy_test.go.erb
  third_party/terraform/utils/iam_project.go
  third_party/terraform/utils/provider.go.erb
Labels: cla: yes

#3379 Add default url redirect to url maps
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/region_target_http_proxy_https_redirect.tf.erb
  templates/terraform/examples/target_http_proxy_https_redirect.tf.erb
  third_party/terraform/tests/resource_compute_region_url_map_test.go.erb
  third_party/terraform/tests/resource_compute_url_map_test.go.erb
Labels: cla: yes, community

#3422 Sql user label
  products/sql/api.yaml
Labels: cla: yes

#3402 Add GKE recommendations / usage docs
  third_party/terraform/website/docs/guides/getting_started.html.markdown
  third_party/terraform/website/docs/guides/using_gke_with_terraform.html.markdown
  third_party/terraform/website/docs/guides/version_2_upgrade.html.markdown
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
  third_party/terraform/website/docs/r/container_cluster.html.markdown
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
  third_party/terraform/website/google.erb.tmpl
Labels: cla: yes

#3418 Include iap in appengine patch updatemask.
  third_party/terraform/resources/resource_app_engine_application.go
Labels: cla: yes, community

#3421 stop converting timeouts to/from minutes
  templates/terraform/custom_delete/appversion_delete.go.erb
  templates/terraform/operation.go.erb
  templates/terraform/post_create/labels.erb
  templates/terraform/resource.erb
  third_party/terraform/resources/common_operation_test.go
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/resources/resource_composer_environment.go.erb
  third_party/terraform/resources/resource_compute_attached_disk.go
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/resources/resource_compute_instance_from_template.go
  third_party/terraform/resources/resource_compute_instance_group_manager.go
  third_party/terraform/resources/resource_compute_project_metadata_item.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
  third_party/terraform/resources/resource_compute_security_policy.go.erb
  third_party/terraform/resources/resource_compute_shared_vpc_host_project.go
  third_party/terraform/resources/resource_compute_shared_vpc_service_project.go
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_container_node_pool.go.erb
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/resources/resource_dataproc_job.go
  third_party/terraform/resources/resource_google_folder.go
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/resources/resource_service_networking_connection.go
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/tests/resource_dataproc_job_test.go
  third_party/terraform/utils/appengine_operation.go
  third_party/terraform/utils/cloudfunctions_operation.go
  third_party/terraform/utils/common_operation.go
  third_party/terraform/utils/composer_operation.go
  third_party/terraform/utils/compute_operation.go
  third_party/terraform/utils/container_operation.go
  third_party/terraform/utils/dataproc_cluster_operation.go
  third_party/terraform/utils/dataproc_job_operation.go
  third_party/terraform/utils/deployment_manager_operation.go
  third_party/terraform/utils/service_networking_operation.go
  third_party/terraform/utils/serviceman_operation.go
  third_party/terraform/utils/serviceusage_operation.go
  third_party/terraform/utils/sqladmin_operation.go
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3405 add optional service account for scheduled queries
  products/bigquerydatatransfer/api.yaml
  third_party/terraform/tests/resource_bigquery_data_transfer_config_test.go
Labels: cla: yes, community

#3429 [upstream] Add support for providing additional experiments to Dataflow job
  third_party/terraform/resources/resource_dataflow_job.go
  third_party/terraform/tests/resource_dataflow_job_test.go
  third_party/terraform/website/docs/r/dataflow_job.html.markdown
Labels: cla: no

#3382 Stateful disk support for igm/rigm
  third_party/terraform/resources/resource_compute_instance_group_manager.go.erb
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go.erb
  third_party/terraform/tests/resource_compute_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go.erb
  third_party/terraform/website/docs/r/compute_instance_group_manager.html.markdown
  third_party/terraform/website/docs/r/compute_region_instance_group_manager.html.markdown
Labels: cla: yes

#3432 Add timeouts to all resources that use Operations
  templates/terraform/post_create/compute_backend_service_security_policy.go.erb
  templates/terraform/post_create/compute_network_delete_default_route.erb
  templates/terraform/pre_delete/detach_disk.erb
  third_party/terraform/resources/resource_app_engine_application.go
  third_party/terraform/resources/resource_compute_instance_group.go
  third_party/terraform/resources/resource_compute_instance_template.go
  third_party/terraform/resources/resource_compute_network_peering.go.erb
  third_party/terraform/resources/resource_compute_project_default_network_tier.go
  third_party/terraform/resources/resource_compute_project_metadata.go
  third_party/terraform/resources/resource_compute_router_interface.go
  third_party/terraform/resources/resource_compute_shared_vpc_host_project.go
  third_party/terraform/resources/resource_compute_shared_vpc_service_project.go
  third_party/terraform/resources/resource_compute_target_pool.go
  third_party/terraform/resources/resource_endpoints_service.go
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/resources/resource_service_networking_connection.go
  third_party/terraform/resources/resource_sql_ssl_cert.go
  third_party/terraform/resources/resource_sql_user.go
  third_party/terraform/resources/resource_usage_export_bucket.go
  third_party/terraform/tests/resource_compute_instance_migrate_test.go
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
  third_party/terraform/utils/appengine_operation.go
  third_party/terraform/utils/compute_operation.go
  third_party/terraform/utils/service_networking_operation.go
  third_party/terraform/utils/serviceman_operation.go
  third_party/terraform/utils/serviceusage_operation.go
  third_party/terraform/utils/sqladmin_operation.go
  third_party/terraform/website/docs/r/app_engine_application.html.markdown
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
  third_party/terraform/website/docs/r/compute_network_peering.html.markdown
  third_party/terraform/website/docs/r/compute_project_default_network_tier.html.markdown
  third_party/terraform/website/docs/r/compute_project_metadata.html.markdown
  third_party/terraform/website/docs/r/compute_router_interface.html.markdown
  third_party/terraform/website/docs/r/compute_shared_vpc_host_project.html.markdown
  third_party/terraform/website/docs/r/compute_shared_vpc_service_project.html.markdown
  third_party/terraform/website/docs/r/compute_target_pool.html.markdown
  third_party/terraform/website/docs/r/endpoints_service.html.markdown
  third_party/terraform/website/docs/r/sql_ssl_cert.html.markdown
  third_party/terraform/website/docs/r/sql_user.html.markdown
  third_party/terraform/website/docs/r/usage_export_bucket.html.markdown
Labels: cla: yes

#3400 Resource for managing logging buckets
  third_party/terraform/resources/resource_logging_billing_account_bucket_config.go
  third_party/terraform/resources/resource_logging_bucket_config.go
  third_party/terraform/resources/resource_logging_folder_bucket_config.go
  third_party/terraform/resources/resource_logging_organization_bucket_config.go
  third_party/terraform/resources/resource_logging_project_bucket_config.go
  third_party/terraform/tests/resource_logging_bucket_config_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/r/logging_billing_account_bucket_config.html.markdown
  third_party/terraform/website/docs/r/logging_folder_bucket_config.html.markdown
  third_party/terraform/website/docs/r/logging_organization_bucket_config.html.markdown
  third_party/terraform/website/docs/r/logging_project_bucket_config.html.markdown
Labels: cla: yes

#3431 Add validation to label keys for cloud functions
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
  third_party/terraform/website/docs/r/cloudfunctions_function.html.markdown
Labels: cla: yes

#3433 Add different api name for screen lock
  products/accesscontextmanager/api.yaml
  templates/terraform/examples/access_context_manager_access_level_basic.tf.erb
Labels: cla: yes

#3434 Add retry for storage bucket 412
  products/storage/terraform.yaml
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#3435 Make localityLbPolicy updateable
  products/compute/api.yaml
Labels: cla: yes

#3437 Add nil checks to stateful disk flatten
  third_party/terraform/resources/resource_compute_instance_group_manager.go.erb
Labels: cla: yes

#3424 add bigquery connection with examples
  products/bigqueryconnection/api.yaml
  products/bigqueryconnection/terraform.yaml
  templates/terraform/examples/bigquery_connection_basic.tf.erb
  templates/terraform/examples/bigquery_connection_full.tf.erb
  third_party/terraform/tests/resource_bigquery_connection_test.go.erb
Labels: cla: yes, community

#3438 don't include IGM URLs that 404 in instance_group_urls
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_container_node_pool.go.erb
Labels: cla: yes

#3439 Add mutex to route for peering
  products/compute/terraform.yaml
Labels: cla: yes

#3381 Promote region* compute services to GA
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/region_backend_service_balancing_mode.tf.erb
  templates/terraform/examples/region_backend_service_ilb_ring_hash.tf.erb
  templates/terraform/examples/region_backend_service_ilb_round_robin.tf.erb
  templates/terraform/examples/region_ssl_certificate_target_https_proxies.tf.erb
  templates/terraform/examples/region_target_http_proxy_basic.tf.erb
  templates/terraform/examples/region_target_http_proxy_https_redirect.tf.erb
  templates/terraform/examples/region_target_https_proxy_basic.tf.erb
  templates/terraform/examples/region_url_map_basic.tf.erb
  templates/terraform/examples/region_url_map_l7_ilb_path.tf.erb
  templates/terraform/examples/region_url_map_l7_ilb_path_partial.tf.erb
  templates/terraform/examples/region_url_map_l7_ilb_route.tf.erb
  templates/terraform/examples/region_url_map_l7_ilb_route_partial.tf.erb
  third_party/terraform/tests/resource_compute_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_region_target_http_proxy_test.go.erb
  third_party/terraform/tests/resource_compute_region_target_https_proxy_test.go.erb
  third_party/terraform/tests/resource_compute_region_url_map_test.go.erb
Labels: cla: yes, community

#3441 fix hardcoded int timeouts
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/resources/resource_google_service_account_key.go
  third_party/terraform/tests/resource_composer_environment_test.go.erb
  third_party/terraform/tests/resource_compute_instance_test.go
  third_party/terraform/utils/bootstrap_utils_test.go
  third_party/terraform/utils/service_account_waiter.go
Labels: cla: yes

#3427 Add contributor checker to GCB.
  .ci/containers/contributor-checker/Dockerfile
  .ci/containers/contributor-checker/check-contributor.sh
  .ci/gcb-generate-diffs.yml
Labels: cla: yes

#3446 duplicate fhir version and set it to required
  products/healthcare/api.yaml
Labels: cla: yes

#3444 Un-guard node_locations on google_container_node_pool resource
  third_party/terraform/resources/resource_container_node_pool.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: cla: yes, community

#3387 dataflow job update-by-replacement
  third_party/terraform/resources/resource_dataflow_job.go
  third_party/terraform/tests/resource_dataflow_job_test.go
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#3451 Fix service account examples
  templates/inspec/examples/google_service_account_key/google_service_account_key.erb
  third_party/inspec/documentation/google_service_account.md
Labels: cla: yes
