Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2020-08, with the labels that each got.

#3805 Add persistence_iam_identity to Redis Instance
  products/redis/api.yaml
  templates/terraform/examples/redis_instance_full.tf.erb
  templates/terraform/examples/redis_instance_private_service.tf.erb
Labels: cla: yes

#3801 Make project field in google_compute_network_endpoint_group ds optional
  third_party/terraform/data_sources/data_source_compute_network_endpoint_group.go
Labels: cla: yes

#3793 Add labels to Bigtable instance
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/tests/resource_bigtable_instance_test.go
  third_party/terraform/website/docs/r/bigtable_instance.html.markdown
Labels: cla: yes

#3808 Update compute_security_policy docs to match src_ip_ranges constraints
  third_party/terraform/resources/resource_compute_security_policy.go.erb
  third_party/terraform/website/docs/r/compute_security_policy.html.markdown
Labels: cla: yes

#3783 Fix collapsed markdown for enum values on Terraform website
  templates/terraform/property_documentation.erb
Labels: cla: yes

#3811 Bigtable: Refer to a functional role for bigtable
  third_party/terraform/website/docs/r/bigtable_instance_iam.html.markdown
Labels: cla: no

#3810 Fix description for ip_allocation_policy.cluster_secondary_range_name…
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: cla: yes

#3812 add warning in spanner db doc
  products/spanner/terraform.yaml
Labels: cla: yes

#3803 Add google_storage_bucket_object.media_link
  third_party/terraform/data_sources/data_source_google_storage_bucket_object.go
  third_party/terraform/resources/resource_storage_bucket_object.go
  third_party/terraform/website/docs/d/storage_bucket_object.html.markdown
  third_party/terraform/website/docs/r/storage_bucket_object.html.markdown
Labels: cla: yes

#3815 more notebook instance fixes
  products/notebooks/terraform.yaml
Labels: cla: yes

#3626 Org Security Policies (Hierarchical Firewalls)
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  provider/terraform.rb
  provider/terraform/custom_code.rb
  provider/terraform_object_library.rb
  templates/terraform/custom_import/organization_security_policy_rule.go.erb
  templates/terraform/examples/organization_security_policy_association_basic.tf.erb
  templates/terraform/examples/organization_security_policy_basic.tf.erb
  templates/terraform/examples/organization_security_policy_rule_basic.tf.erb
  templates/terraform/post_create/org_security_policy.go.erb
  templates/terraform/post_create/org_security_policy_association.go.erb
  templates/terraform/post_create/org_security_policy_rule.go.erb
  templates/terraform/post_delete/org_security_policy.go.erb
  templates/terraform/post_update/org_security_policy.go.erb
  templates/terraform/resource.erb
  third_party/terraform/tests/resource_compute_organization_security_policy_rule_test.go.erb
  third_party/terraform/tests/resource_compute_organization_security_policy_test.go.erb
  third_party/terraform/utils/compute_operation.go.erb
  third_party/terraform/utils/deployment_manager_operation.go.erb
Labels: cla: yes, enhancement

#3813 Update google_cloudfunctions_function datasource documentation.
  third_party/terraform/website/docs/d/cloudfunctions_function.html.markdown
Labels: cla: yes

#3818 iamPolicyVersion needed to be configurable
  api/resource/iam_policy.rb
  templates/terraform/iam_policy.go.erb
Labels: cla: yes

#3627 Adding Missing Cloud Build Attributes
  products/cloudbuild/api.yaml
  products/cloudbuild/terraform.yaml
  templates/terraform/examples/cloudbuild_trigger_build.tf.erb
  third_party/terraform/tests/resource_cloudbuild_trigger_test.go
Labels: cla: yes

#3821 Add additional fields to Memcached Instance
  products/memcache/api.yaml
  templates/terraform/examples/memcache_instance_basic.tf.erb
Labels: cla: yes

#3822 Move shieldedvmconfig -> shieldedinstanceconfig due to rename.
  third_party/terraform/data_sources/data_source_google_compute_instance.go
  third_party/terraform/resources/resource_compute_instance.go.erb
  third_party/terraform/resources/resource_compute_instance_template.go.erb
  third_party/terraform/utils/compute_instance_helpers.go.erb
Labels: cla: yes

#3819 add support for point_in_time_recovery for sql instance
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: no

#3823 Update ospatch's windows update classification field to be an array.
  products/osconfig/api.yaml
  templates/terraform/examples/os_config_patch_deployment_full.tf.erb
  templates/terraform/property_documentation.erb
  templates/terraform/schema_property.erb
Labels: cla: yes

#3829 Remove test that tests legacy behavior which has been removed.
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#3814 Make `iap` field computed
  third_party/terraform/resources/resource_app_engine_application.go
Labels: cla: yes

#3834 Promote release_channel to GA for GKE
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#3820 Convert inboundServices to an enum.
  products/appengine/api.yaml
  templates/terraform/flatten_property_method.erb
  templates/terraform/schema_property.erb
Labels: cla: yes

#3838 Fix buggy import of artifact repository.
  products/artifactregistry/terraform.yaml
Labels: cla: yes

#3837 Promote the schema block for release_channel to GA
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: cla: yes

#3807 Add serverless negs
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/region_network_endpoint_group_appengine.tf.erb
  templates/terraform/examples/region_network_endpoint_group_cloudrun.tf.erb
  templates/terraform/examples/region_network_endpoint_group_functions.tf.erb
Labels: cla: yes

#3839 Promote release_channel_default_version field in data.google_container_engine_versions to GA
  third_party/terraform/data_sources/data_source_google_container_engine_versions.go.erb
  third_party/terraform/website/docs/d/container_engine_versions.html.markdown
Labels: cla: yes

#3826 Fixed validation of service_level_indicator.0.windows_based_sli.0.metric_sum_in_range.0.range.0.max
  products/monitoring/api.yaml
Labels: cla: yes

#3841 reconfigure PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#3799 add source_image and source_snapshot to google_compute_image
  products/compute/api.yaml
  third_party/terraform/tests/resource_compute_image_test.go
Labels: cla: yes

#3846 Follow redirects so downstreams get merged correctly.
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: cla: yes

#3790 Adding support for v1 game servers.
  products/gameservices/api.yaml
  products/gameservices/terraform.yaml
  templates/terraform/examples/game_service_cluster_basic.tf.erb
  templates/terraform/examples/game_service_config_basic.tf.erb
  templates/terraform/examples/game_service_deployment_basic.tf.erb
  templates/terraform/examples/game_service_deployment_rollout_basic.tf.erb
  templates/terraform/examples/game_service_realm_basic.tf.erb
  third_party/terraform/data_sources/data_google_game_services_game_server_deployment_rollout.go.erb
  third_party/terraform/tests/data_google_game_services_game_server_deployment_rollout_test.go.erb
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/game_services_game_server_deployment_rollout.html.markdown
Labels: cla: yes

#3835 migrating google and google-beta repos to hashicorp org
  .ci/containers/downstream-builder/generate_downstream.sh
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  products/compute/api.yaml
  products/compute/terraform.yaml
  products/pubsub/terraform.yaml
  templates/terraform/examples/cloudbuild_trigger_github.tf.erb
  third_party/terraform/data_sources/data_source_google_storage_bucket_object.go
  third_party/terraform/main.go.erb
  third_party/terraform/resources/resource_app_engine_application.go
  third_party/terraform/resources/resource_compute_instance_template.go.erb
  third_party/terraform/resources/resource_compute_security_policy.go.erb
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_google_organization_policy.go
  third_party/terraform/resources/resource_logging_exclusion.go
  third_party/terraform/scripts/affectedtests/affectedtests.go
  third_party/terraform/scripts/changelog-links.sh.erb
  third_party/terraform/tests/resource_compute_security_policy_test.go.erb
  third_party/terraform/tests/resource_pubsub_subscription_test.go
  third_party/terraform/utils/error_retry_predicates.go
  third_party/terraform/utils/iam.go.erb
  third_party/terraform/utils/provider_handwritten_endpoint.go.erb
  third_party/terraform/utils/transport.go
  third_party/terraform/website/docs/guides/version_2_upgrade.html.markdown
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
  third_party/terraform/website/docs/index.html.markdown
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
  tools/bootstrap
Labels: cla: yes

#3847 Temporarily remove danawillow as a reviewer
  .ci/containers/contributor-checker/check-contributor.sh
Labels: cla: yes

#3842 Add missing region argument for dataflow job
  third_party/terraform/website/docs/r/dataflow_job.html.markdown
Labels: cla: yes

#3845 Set region as optional in doc for cloud_scheduler_job
  products/cloudscheduler/terraform.yaml
Labels: cla: yes

#3851 Add warning about initial_node_count
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: cla: yes

#3831 Collection fixes for release
  products/bigquery/ansible_version_added.yaml
  products/cloudbuild/ansible_version_added.yaml
  products/compute/api.yaml
  products/container/helpers/python/kubectl.py
  products/iam/helpers/ansible/service_account_key_template.erb
  products/logging/ansible_version_added.yaml
  products/pubsub/ansible_version_added.yaml
  products/pubsub/api.yaml
  provider/ansible/documentation.rb
  provider/ansible/gcp_utils.py
  templates/ansible/documentation.erb
  templates/ansible/facts.erb
  templates/ansible/resource.erb
Labels: cla: yes

#3844 Update documentation for Folder and Organization IAM resources.
  third_party/terraform/website/docs/r/google_folder_iam.html.markdown
  third_party/terraform/website/docs/r/google_folder_iam_audit_config.html.markdown
  third_party/terraform/website/docs/r/google_folder_iam_binding.html.markdown
  third_party/terraform/website/docs/r/google_folder_iam_member.html.markdown
  third_party/terraform/website/docs/r/google_folder_iam_policy.html.markdown
  third_party/terraform/website/docs/r/google_organization_iam.markdown
  third_party/terraform/website/docs/r/google_organization_iam_audit_config.html.markdown
  third_party/terraform/website/docs/r/google_organization_iam_binding.html.markdown
  third_party/terraform/website/docs/r/google_organization_iam_member.html.markdown
  third_party/terraform/website/docs/r/google_organization_iam_policy.html.markdown
Labels: cla: yes

#3817 Update google_billing_budget resource to add notifications
  products/billingbudget/api.yaml
  products/billingbudget/terraform.yaml
  templates/terraform/examples/billing_budget_notify.tf.erb
Labels: cla: yes

#3759 Add new field filter to pubsub.
  products/pubsub/api.yaml
  third_party/terraform/tests/resource_pubsub_subscription_test.go
Labels: cla: yes

#3849 Enable Uploading Serviceaccount keys
  third_party/terraform/resources/resource_google_service_account_key.go
  third_party/terraform/tests/resource_google_service_account_key_test.go
  third_party/terraform/utils/test-fixtures/serviceaccount/public_key.pem
  third_party/terraform/website/docs/r/google_service_account_key.html.markdown
Labels: cla: yes

#3824 Add Confidential VM support to instances and instance templates
  third_party/terraform/resources/resource_compute_instance.go.erb
  third_party/terraform/resources/resource_compute_instance_template.go.erb
  third_party/terraform/tests/resource_compute_instance_template_test.go.erb
  third_party/terraform/tests/resource_compute_instance_test.go.erb
  third_party/terraform/utils/compute_instance_helpers.go.erb
Labels: cla: yes

#3854 Fix project field for SQL instance data source
  third_party/terraform/data_sources/data_source_sql_database_instance.go
  third_party/terraform/tests/data_source_sql_database_instance_test.go
  third_party/terraform/website/docs/d/sql_database_instance.html.markdown
Labels: cla: yes

#3855 add sweepers to igm/rigm tests, prefix igm/rigms with tf-test
  products/compute/terraform.yaml
  templates/terraform/examples/backend_service_signed_url_key.tf.erb
  templates/terraform/examples/global_forwarding_rule_internal.tf.erb
  third_party/terraform/tests/data_source_google_compute_instance_group_test.go.erb
  third_party/terraform/tests/data_source_google_compute_region_instance_group_test.go.erb
  third_party/terraform/tests/resource_compute_autoscaler_test.go.erb
  third_party/terraform/tests/resource_compute_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_global_forwarding_rule_test.go.erb
  third_party/terraform/tests/resource_compute_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_per_instance_config_test.go.erb
  third_party/terraform/tests/resource_compute_region_autoscaler_test.go.erb
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_region_per_instance_config_test.go.erb
Labels: cla: yes

#3828 add access approval settings resources
  products/accessapproval/api.yaml
  products/accessapproval/terraform.yaml
  templates/terraform/custom_delete/clear_folder_access_approval_settings.go.erb
  templates/terraform/custom_delete/clear_organization_access_approval_settings.go.erb
  templates/terraform/custom_delete/clear_project_access_approval_settings.go.erb
  templates/terraform/examples/folder_access_approval_full.tf.erb
  templates/terraform/examples/organization_access_approval_full.tf.erb
  templates/terraform/examples/project_access_approval_full.tf.erb
  templates/terraform/pre_create/access_approval_settings.go.erb
  third_party/terraform/tests/resource_access_approval_folder_settings_test.go
  third_party/terraform/tests/resource_access_approval_organization_settings_test.go
  third_party/terraform/tests/resource_access_approval_project_settings_test.go
Labels: cla: yes

#3858 updates more info link for cloud run service spec.containers.resources
  products/cloudrun/api.yaml
Labels: cla: yes

#3833 Upstream TPG #6920.
  products/bigquery/api.yaml
Labels: cla: yes

#3804 Add skips for beta tests that don't work with VCR.
  products/bigqueryconnection/terraform.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/base_configs/iam_test_file.go.erb
  third_party/terraform/tests/resource_bigquery_connection_test.go.erb
  third_party/terraform/tests/resource_compute_health_check_test.go
  third_party/terraform/tests/resource_endpoints_service_test.go
  third_party/terraform/tests/resource_google_folder_iam_audit_config_test.go
Labels: cla: yes

#3857 Rename google_organization_iam markdown file to fix Travis
  third_party/terraform/website/docs/r/google_organization_iam.html.markdown
Labels: cla: yes

#3860 Update google_billing_budget resource to add last_period_amount
  products/billingbudget/api.yaml
  products/billingbudget/terraform.yaml
  templates/terraform/examples/billing_budget_lastperiod.tf.erb
Labels: cla: yes

#3862 fix cloud identity group import
  products/cloudidentity/terraform.yaml
  templates/terraform/custom_import/set_id_name_with_slashes.go.erb
Labels: cla: yes

#3865 Send empty privateVisibilityConfig network array
  products/dns/api.yaml
  products/dns/terraform.yaml
  templates/terraform/custom_expand/dns_managed_zone_private_visibility_config.go.erb
Labels: cla: yes

#3866 Check for self_links in replaceVarsForTest
  third_party/terraform/utils/transport_test.go
Labels: cla: yes

#3852 Add ability to bulk edit access manager access levels and service perimeters
  products/accesscontextmanager/api.yaml
  products/accesscontextmanager/inspec.yaml
  products/accesscontextmanager/terraform.yaml
  templates/terraform/custom_delete/replace_all_access_levels_empty_list.go.erb
  templates/terraform/custom_delete/replace_all_service_perimeters_empty_list.go.erb
  templates/terraform/custom_import/set_access_policy_parent_from_access_policy.go.erb
  templates/terraform/examples/access_context_manager_access_levels_basic.tf.erb
  templates/terraform/examples/access_context_manager_service_perimeters_basic.tf.erb
  third_party/terraform/tests/resource_access_context_manager_access_levels_test.go
  third_party/terraform/tests/resource_access_context_manager_access_policy_test.go.erb
  third_party/terraform/tests/resource_access_context_manager_services_perimeters_test.go
Labels: cla: yes

#3864 Add user prefix for generated iam import statements
  templates/terraform/resource_iam.html.markdown.erb
Labels: cla: yes

#3859 Skip more beta tests in VCR
  .ci/containers/vcr-cassette-merger/vcr_merge.sh
  products/datacatalog/terraform.yaml
  third_party/terraform/tests/resource_compute_per_instance_config_test.go.erb
  third_party/terraform/tests/resource_compute_region_per_instance_config_test.go.erb
  third_party/terraform/tests/resource_dataflow_flex_template_job_test.go.erb
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
Labels: cla: yes

#3867 Add archive class to gcs
  products/storage/api.yaml
  templates/terraform/examples/storage_bucket_storage_class.tf.erb
  third_party/terraform/resources/resource_storage_bucket.go
  third_party/terraform/resources/resource_storage_bucket_object.go
  third_party/terraform/tests/resource_storage_bucket_test.go
  third_party/terraform/website/docs/d/storage_bucket_object.html.markdown
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
  third_party/terraform/website/docs/r/storage_bucket_object.html.markdown
Labels: cla: yes

#3869 typo correction - value (singular) to values
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#3871 handle pagination in cloud identity datasources
  third_party/terraform/data_sources/data_source_cloud_identity_group_memberships.go.erb
  third_party/terraform/data_sources/data_source_cloud_identity_groups.go.erb
Labels: cla: yes

#3870 Add more skips for beta tests
  products/activedirectory/terraform.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/active_directory_domain_basic.tf.erb
  third_party/terraform/tests/resource_compute_region_health_check_test.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/tests/resource_storage_bucket_test.go
Labels: cla: yes

#3825 Add support for gRPC healthchecks
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/health_check_grpc.tf.erb
  templates/terraform/examples/health_check_grpc_full.tf.erb
  templates/terraform/examples/region_health_check_grpc.tf.erb
  templates/terraform/examples/region_health_check_grpc_full.tf.erb
Labels: cla: yes

#3872 Add enableMessageOrdering to Pub/Sub Subscription
  products/pubsub/api.yaml
  templates/terraform/examples/pubsub_subscription_pull.tf.erb
  third_party/terraform/tests/resource_pubsub_subscription_test.go
Labels: cla: yes

#3875 fix cloud identity groups sweeper
  products/cloudidentity/terraform.yaml
  third_party/terraform/resources/resource_cloud_identity_group_sweeper_test.go.erb
Labels: cla: yes

#3856 Add support for BigQuery table ACLs
  products/bigquery/terraform.yaml
  templates/terraform/examples/bigquery_bigquery_table.tf.erb
Labels: cla: yes

#3874 Specify possible values for arg only once
  products/compute/api.yaml
Labels: cla: yes

#3876 Revert "Temporarily remove danawillow as a reviewer"
  .ci/containers/contributor-checker/check-contributor.sh
Labels: cla: yes

#3877 Add attributes reference to `google_compute_instance_from_template`
  third_party/terraform/website/docs/r/compute_instance_from_template.html.markdown
Labels: cla: yes

#3755 use {product}.googleapis.com endpoints
  products/bigquery/api.yaml
  products/compute/api.yaml
  products/dns/api.yaml
  products/storage/api.yaml
  third_party/terraform/data_sources/data_source_google_compute_zones.go
  third_party/terraform/resources/resource_compute_network_peering.go
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/tests/data_source_google_compute_zones_test.go
Labels: cla: yes

#3741 fix bug with data access iam member
  products/bigquery/terraform.yaml
  templates/terraform/constants/bigquery_dataset_access.go
  templates/terraform/constants/bigquery_dataset_access.go.erb
  templates/terraform/extra_schema_entry/bigquery_dataset_access.go.erb
  templates/terraform/post_create/bigquery_dataset_access.go.erb
  third_party/terraform/tests/resource_bigquery_dataset_access_test.go
Labels: cla: yes

#3880 google_dataflow_job - return more fields on the read
  third_party/terraform/resources/resource_dataflow_job.go
Labels: cla: yes

#3861 Fix logConfig field in Compute Health Check resource.
  products/compute/api.yaml
Labels: cla: yes

#3882 Make sql db instance recreate when going private -> public
  third_party/terraform/resources/resource_sql_database_instance.go.erb
Labels: cla: yes

#3798 Add trust to ad domain 5731
  products/activedirectory/api.yaml
  products/activedirectory/terraform.yaml
  templates/terraform/custom_delete/active_directory_domain_trust.go.erb
  templates/terraform/encoders/active_directory_domain_trust.go.erb
  templates/terraform/examples/active_directory_domain_trust_basic.tf.erb
  templates/terraform/update_encoder/active_directory_domain_trust.go.erb
  third_party/terraform/tests/resource_active_directory_domain_trust_test.go
Labels: cla: yes

#3878 Shorten domain name to fit regex
  products/activedirectory/terraform.yaml
Labels: cla: yes

#3760 Upstream support for Kubelet and Linux Node configurations in GKE
  third_party/terraform/resources/resource_container_node_pool.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/utils/node_config.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3883 Fix grpc healthcheck behaviour.
  templates/terraform/encoders/health_check_type.erb
  third_party/terraform/tests/resource_compute_health_check_test.go
  third_party/terraform/tests/resource_compute_region_health_check_test.go.erb
Labels: cla: yes

#3789 Add vpcAccessConnector property on google_app_engine_standard_app_version terraform resource
  products/appengine/api.yaml
  third_party/terraform/tests/resource_app_engine_standard_app_version_test.go
Labels: cla: yes

#3885 Use `lineage` instead of `api_name` for property conflicts
  api/type.rb
  products/appengine/api.yaml
  products/compute/api.yaml
  products/mlengine/api.yaml
Labels: cla: yes

#3884 Add support for regional NEG stripping of maxUtilization based on url
  templates/terraform/encoders/backend_service.go.erb
  third_party/terraform/tests/resource_compute_backend_service_test.go.erb
Labels: cla: yes

#3889 Fix test resource names to match example
  templates/terraform/examples/region_health_check_grpc.tf.erb
  templates/terraform/examples/region_health_check_grpc_full.tf.erb
Labels: cla: yes

#3887 add support for iam resources for google_compute_image
  products/compute/terraform.yaml
Labels: cla: yes

#3891 Add Discovery endpoint to Memcached Instance
  products/memcache/api.yaml
Labels: cla: yes

#3904 fixed data_source_secret_manager_secret_version on its id
  third_party/terraform/data_sources/data_source_secret_manager_secret_version.go.erb
Labels: cla: yes

#3603 Advanced logging config options in google_compute_subnetwork
  README.md
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/custom_expand/subnetwork_log_config.go.erb
  templates/terraform/custom_flatten/subnetwork_log_config.go.erb
  third_party/terraform/tests/resource_compute_subnetwork_test.go
Labels: cla: yes

#3894 Drop recommendation to use -provider= on import
  templates/terraform/resource.html.markdown.erb
  templates/terraform/resource_iam.html.markdown.erb
  third_party/terraform/website/docs/guides/provider_versions.html.markdown
  third_party/terraform/website/docs/r/google_kms_crypto_key_iam.html.markdown
  third_party/terraform/website/docs/r/google_kms_key_ring_iam.html.markdown
  third_party/terraform/website/docs/r/google_service_account_iam.html.markdown
  third_party/terraform/website/docs/r/monitoring_dashboard.html.markdown
Labels: cla: yes

#3906 update docs now that upgrade_settings is no longer beta
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: cla: yes

#3863 Add DatabaseConfig and WebServerConfig to Cloud Composer's EnvironmentConfig
  third_party/terraform/resources/resource_composer_environment.go.erb
  third_party/terraform/tests/resource_composer_environment_test.go.erb
  third_party/terraform/website/docs/r/composer_environment.html.markdown
Labels: cla: yes

#3902 fix active directory domain sweeper
  products/activedirectory/api.yaml
  products/activedirectory/terraform.yaml
  third_party/terraform/tests/resource_active_directory_domain_update_test.go
Labels: cla: yes

#3827 Add support for pd-balanced disk type
  products/compute/api.yaml
  third_party/terraform/resources/resource_compute_instance.go.erb
  third_party/terraform/resources/resource_compute_instance_template.go.erb
  third_party/terraform/utils/node_config.go.erb
  third_party/terraform/website/docs/r/compute_instance.html.markdown
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3905 Fix kubelet expected error test
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
Labels: cla: yes

#3901 fixed audit_config in iam_policy doc
  third_party/terraform/website/docs/d/iam_policy.html.markdown
Labels: cla: yes

#3888 added IAM resources for disk & regionDisk
  products/compute/terraform.yaml
Labels: cla: yes

#3900 Fix PerInstanceConfig tests
  third_party/terraform/tests/resource_compute_per_instance_config_test.go.erb
  third_party/terraform/tests/resource_compute_region_per_instance_config_test.go.erb
Labels: cla: yes

#3909 Mark Resource usage export config as GA in Docs
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3886 Add `billing_project` configuration to the provider
  products/accesscontextmanager/terraform.yaml
  templates/terraform/pre_create/cloud_asset_feed.go.erb
  templates/terraform/resource.erb
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/field_helpers.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/utils.go.erb
  third_party/terraform/website/docs/guides/provider_reference.html.markdown
Labels: cla: yes

#3892 Add project overrides to gke services
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_container_node_pool.go.erb
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/tests/resource_google_project_service_test.go
Labels: cla: yes

#3903 Cloud Storage: docs improvements for automatic service account
  third_party/terraform/website/docs/d/storage_project_service_account.html.markdown
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
  third_party/terraform/website/docs/r/storage_notification.html.markdown
Labels: cla: yes

#3913 Update cloudfunctions_function.html.markdown
  third_party/terraform/website/docs/r/cloudfunctions_function.html.markdown
Labels: cla: no

#3893 Data Losss Prevention resources
  products/dlp/api.yaml
  products/dlp/terraform.yaml
  templates/terraform/custom_import/dlp_inspect_template.go.erb
  templates/terraform/custom_import/dlp_job_trigger.go.erb
  templates/terraform/encoders/wrap_object.go.erb
  templates/terraform/examples/dlp_inspect_template_basic.tf.erb
  templates/terraform/examples/dlp_job_trigger_basic.tf.erb
  third_party/terraform/tests/resource_data_loss_prevention_inspect_template_test.go
  third_party/terraform/tests/resource_data_loss_prevention_job_trigger_test.go
Labels: cla: yes

#3898 Add Erase Windows VSS support to compute disk
  products/compute/api.yaml
  templates/terraform/examples/disk_basic.tf.erb
  templates/terraform/examples/stateful_igm.tf.erb
  templates/terraform/examples/stateful_rigm.tf.erb
  third_party/terraform/tests/resource_compute_disk_test.go.erb
Labels: cla: yes

#3915 Fix failing active_directory_domain_trust tests
  third_party/terraform/tests/resource_active_directory_domain_trust_test.go
Labels: cla: yes

#3918 only update shielded_instance_config for stopped instances
  third_party/terraform/resources/resource_compute_instance.go.erb
  third_party/terraform/tests/resource_compute_instance_test.go.erb
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#3921 Upstream: Add google_project_service_identity resource
  third_party/terraform/resources/resource_project_service_identity.go.erb
  third_party/terraform/tests/resource_project_service_identity_test.go.erb
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/r/project_service_identity.html.markdown
Labels: cla: yes

#3912 Correct data type for Notebook Instance Owners field, add some enums
  products/notebooks/api.yaml
Labels: cla: yes

#3925 Update GKE Docs to mentions labels that can't be used.
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3868 Add additional fields to projects data source
  third_party/terraform/data_sources/data_source_google_projects.go
  third_party/terraform/tests/data_source_google_projects_test.go
Labels: cla: yes

#3926 Cleanup legacy provider formatting
  templates/terraform/examples/data_fusion_instance_basic.tf.erb
  templates/terraform/examples/data_fusion_instance_full.tf.erb
  templates/terraform/examples/organization_security_policy_association_basic.tf.erb
  templates/terraform/examples/organization_security_policy_basic.tf.erb
  templates/terraform/examples/organization_security_policy_rule_basic.tf.erb
  third_party/terraform/website/docs/d/container_engine_versions.html.markdown
  third_party/terraform/website/docs/guides/provider_reference.html.markdown
Labels: cla: yes

#3916 Deprecate bucket policy field in google_storage_bucket
  third_party/terraform/resources/resource_storage_bucket.go
  third_party/terraform/tests/resource_storage_bucket_test.go
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
Labels: cla: yes

#3927 Add permission name.
  third_party/terraform/website/docs/r/google_project_service.html.markdown
Labels: cla: yes

#3929 Bump cloudbuild timeout to avoid queued jobs failing
  .ci/gcb-generate-diffs.yml
Labels: cla: yes

#3922 Stored info
  products/dlp/api.yaml
  products/dlp/terraform.yaml
  templates/terraform/custom_import/dlp_import.go.erb
  templates/terraform/custom_import/dlp_inspect_template.go.erb
  templates/terraform/decoders/dlp_stored_info_type.go.erb
  templates/terraform/encoders/dlp_stored_info_type.go.erb
  templates/terraform/examples/dlp_stored_info_type_basic.tf.erb
  templates/terraform/examples/dlp_stored_info_type_dictionary.tf.erb
  templates/terraform/examples/dlp_stored_info_type_large_custom_dictionary.tf.erb
  third_party/terraform/tests/resource_data_loss_prevention_stored_info_type_test.go
  third_party/terraform/utils/test-fixtures/dlp/words.txt
Labels: cla: yes

#3930 Add DSFs to references in snapshot tests (and other MM-generated tests)
  templates/terraform/examples/base_configs/test_file.go.erb
  third_party/terraform/tests/resource_compute_snapshot_test.go
Labels: cla: yes

#3928 Allow IGM to resume operation after interruption
  third_party/terraform/resources/resource_compute_instance_group_manager.go.erb
  third_party/terraform/utils/compute_operation.go.erb
Labels: cla: yes

#3924 Export email output in service_identity
  third_party/terraform/resources/resource_project_service_identity.go.erb
  third_party/terraform/tests/resource_project_service_identity_test.go.erb
  third_party/terraform/website/docs/r/project_service_identity.html.markdown
Labels: cla: yes

#3936 Update issue chooser to link to the other repos
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla: yes
