Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2020-12, with the labels that each got.

#4274 Update google_container_node_pool oauth_scopes to cloud-platform
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
Labels: cla: yes

#4247 Promote Managed SSL to GA + Doc fixes
  products/cloudscheduler/api.yaml
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/managed_ssl_certificate_basic.tf.erb
  templates/terraform/examples/managed_ssl_certificate_recreation.tf.erb
  templates/terraform/examples/scheduler_job_http.tf.erb
  third_party/terraform/utils/common_diff_suppress.go.erb
Labels: cla: yes

#4277 some APIs treat 412s as the conflict code.
  third_party/terraform/utils/utils.go.erb
  third_party/terraform/utils/utils_test.go
Labels: cla: yes

#4269 Allow url map to handle backend service fields that can also be backend buckets.
  products/compute/terraform.yaml
  templates/terraform/custom_expand/reference_to_backend.erb
  templates/terraform/examples/url_map_basic.tf.erb
Labels: cla: yes

#4275 Added new ci container for testing terraform-google-conversion
  .ci/containers/terraform-google-conversion-tester/Dockerfile
  .ci/containers/terraform-google-conversion-tester/test_terraform_google_conversion.sh
Labels: cla: yes

#4265 Promote resource policy to GA
  third_party/terraform/data_sources/data_source_google_compute_resource_policy.go.erb
  third_party/terraform/tests/data_source_google_compute_resource_policy_test.go.erb
  third_party/terraform/utils/provider.go.erb
Labels: cla: yes

#4258 Add replacement_method to IGM and RIGM update_policy
  third_party/terraform/resources/resource_compute_instance_group_manager.go
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
  third_party/terraform/tests/resource_compute_instance_group_manager_test.go
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go
Labels: cla: yes

#4281 Added step to generate-diffs to run tgc tester
  .ci/gcb-generate-diffs.yml
Labels: cla: yes

#4289 Upstream Correct documentation for google_service_account_iam
  third_party/terraform/website/docs/r/google_service_account_iam.html.markdown
Labels: cla: yes

#4279 Add resource document to google_firestore
  products/firestore/api.yaml
  products/firestore/terraform.yaml
  templates/terraform/custom_import/firestore_document.go.erb
  templates/terraform/decoders/firestore_document.go.erb
  templates/terraform/examples/firestore_document_basic.tf.erb
  templates/terraform/examples/firestore_document_nested_document.tf.erb
  third_party/terraform/tests/resource_firestore_document_test.go
Labels: cla: yes

#4253 V1
  products/notebooks/api.yaml
  products/notebooks/terraform.yaml
  provider/terraform/examples.rb
  templates/terraform/examples/base_configs/iam_test_file.go.erb
  templates/terraform/examples/notebook_instance_basic.tf.erb
  templates/terraform/examples/notebook_instance_basic_container.tf.erb
  templates/terraform/examples/notebook_instance_basic_gpu.tf.erb
  templates/terraform/examples/notebook_instance_full.tf.erb
Labels: cla: yes

#4221 Add More GCS Bucket lifecycle conditions
  third_party/terraform/resources/resource_storage_bucket.go
  third_party/terraform/tests/resource_storage_bucket_test.go
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
Labels: cla: yes

#4276 Add CDN to regional backend service, add flexible cache control to backend service.
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/backend_service_cache.tf.erb
  templates/terraform/examples/region_backend_service_cache.tf.erb
Labels: cla: yes

#4286 Move `customResponseHeaders` to beta only
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/backend_service_network_endpoint.tf.erb
  third_party/terraform/tests/resource_compute_backend_service_test.go.erb
Labels: cla: yes

#4290 Mark oidc and aws fields as Forcenew
  products/iambeta/api.yaml
  third_party/terraform/tests/resource_iam_beta_workload_identity_pool_provider_test.go.erb
Labels: cla: yes

#4291 Update CVM docs
  third_party/terraform/website/docs/r/compute_instance.html.markdown
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
Labels: cla: yes

#4294 Remove string concatenation in spanner DB update
  templates/terraform/update_encoder/spanner_database.go.erb
  third_party/terraform/tests/resource_spanner_database_test.go
Labels: cla: yes

#4301 Add customized diff for unique_writer_identity on resource google_logging_project_sink
  third_party/terraform/resources/resource_logging_project_sink.go
  third_party/terraform/tests/resource_logging_project_sink_test.go
  third_party/terraform/website/docs/r/logging_project_sink.html.markdown
Labels: cla: yes

#4287 container_cluster - document possible release_channel configurations
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: cla: yes

#4303 Bump default request timeout to 90s
  third_party/terraform/utils/retry_transport.go
Labels: cla: yes

#4293 Use updated policy to update, not empty policy for DEPRIVILEGE
  third_party/terraform/resources/resource_google_project_default_service_accounts.go
Labels: cla: yes

#4309 Marked terraform provider imports as v3
  third_party/terraform/main.go.erb
  third_party/terraform/utils/provider_handwritten_endpoint.go.erb
Labels: cla: yes

#4169 Add SHARED_LOADBALANCER_VIP purpose to regional addresses.
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/address_with_shared_loadbalancer_vip.tf.erb
Labels: cla: yes

#4305 Add missing 'location' option in sql_database_instance.settings.backup_configuration documentation
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: no

#4260 add tests and docs for using custom service account in dataflow flex template job
  third_party/terraform/tests/resource_dataflow_flex_template_job_test.go.erb
  third_party/terraform/website/docs/r/dataflow_flex_template_job.html.markdown
Labels: cla: yes

#4280 fix scheduler_job_http example
  templates/terraform/examples/scheduler_job_http.tf.erb
Labels: cla: yes

#4312 Mark replication type computed as it no longer comes back from API
  third_party/terraform/resources/resource_sql_database_instance.go.erb
Labels: cla: yes

#4306 Added support for Google Virtual Network Interface (gVNIC) for image part
  products/compute/api.yaml
Labels: cla: yes

#4311 MM Codelab Changes
  TUTORIAL.md
Labels: cla: yes

#4292 Zero out upload url before update
  third_party/terraform/resources/resource_cloudfunctions_function.go
Labels: cla: yes

#4295 Add Pub/Sub Lite Resources
  products/pubsublite/api.yaml
  products/pubsublite/terraform.yaml
  templates/terraform/custom_expand/computed_lite_subscription_topic.erb
  templates/terraform/encoders/pubsub_lite.erb
  templates/terraform/examples/pubsub_lite_subscription_basic.tf.erb
  templates/terraform/examples/pubsub_lite_topic_basic.tf.erb
Labels: cla: yes

#4296 Test TestAccFirebaseWebApp_firebaseWebAppFull
  third_party/terraform/tests/resource_firebase_web_app_test.go.erb
Labels: cla: yes

#4313 last tutorial changes
  TUTORIAL.md
Labels: cla: yes

#4252 Update IAM Documentation
  templates/terraform/resource_iam.html.markdown.erb
  third_party/terraform/website/docs/d/iam_policy.html.markdown
  third_party/terraform/website/docs/r/google_folder_iam.html.markdown
  third_party/terraform/website/docs/r/google_project_iam.html.markdown
Labels: cla: yes

#4254 added data source for storage bucket object content
  third_party/terraform/data_sources/data_source_storage_bucket_object_content.go
  third_party/terraform/tests/data_source_storage_bucket_object_content_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/storage_bucket_object_content.html.markdown
Labels: cla: yes

#4315 Corrected generateUserAgentString usage
  templates/terraform/custom_expand/route_instance.erb
  templates/terraform/custom_expand/secret_version_enable.go.erb
  third_party/validator/compute_instance.go
Labels: cla: yes

#4316 add better error message for no cassette
  third_party/terraform/utils/provider_test.go.erb
Labels: cla: yes

#2640 Add billing subaccount
  third_party/terraform/resources/resource_google_billing_subaccount.go
  third_party/terraform/tests/resource_google_billing_subaccount_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/website/docs/r/google_billing_subaccount.html.markdown
Labels: cla: yes, community

#4273 Promote Billing Budgets to GA
  products/billingbudget/api.yaml
  products/billingbudget/terraform.yaml
  provider/terraform/examples.rb
  templates/terraform/examples/base_configs/test_file.go.erb
  templates/terraform/examples/billing_budget_basic.tf.erb
  templates/terraform/examples/billing_budget_filter.tf.erb
  templates/terraform/examples/billing_budget_lastperiod.tf.erb
  templates/terraform/examples/billing_budget_notify.tf.erb
Labels: cla: yes

#4320 Add dependency to fix test
  templates/terraform/examples/data_catalog_taxonomies_policy_tag_child_policies.tf.erb
Labels: cla: yes

#4304 ForceOverride as ignore read as it does not appear in response
  products/cloudrun/terraform.yaml
  templates/terraform/custom_flatten/cloudrun_ignore_force_override.go.erb
  templates/terraform/examples/cloud_run_domain_mapping_basic.tf.erb
Labels: cla: yes

#4319 Fix reading connection_id from API
  products/bigqueryconnection/api.yaml
  products/bigqueryconnection/terraform.yaml
  templates/terraform/encoders/bigquery_connection.go.erb
  templates/terraform/post_create/bigquery_connection_id.go.erb
Labels: cla: yes

#4327 Fix documentation link
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: no

#4325 Ignores for tests that shouldn't use VCR
  third_party/terraform/tests/data_source_spanner_instance_test.go
  third_party/terraform/tests/resource_bigquery_data_transfer_config_test.go
  third_party/terraform/tests/resource_os_login_ssh_public_key_test.go
Labels: cla: yes

#4323 Fix composer tests
  third_party/terraform/data_sources/data_source_google_composer_environment.go
  third_party/terraform/tests/data_source_google_composer_environment_test.go
  third_party/terraform/tests/resource_composer_environment_test.go.erb
Labels: cla: yes

#4328 Removed trailing references to kubernetes_dashboard
  third_party/inspec/custom_functions/google_container_cluster.erb
  third_party/validator/container.go
Labels: cla: yes

#3991 Refer to the value of `labels` as a 'map'
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
Labels: cla: yes

#4321 Clean up IAM Scopes in the documentation
  templates/terraform/examples/base_configs/test_file.go.erb
  third_party/terraform/website/docs/d/service_account_access_token.html.markdown
  third_party/terraform/website/docs/guides/version_2_upgrade.html.markdown
  third_party/terraform/website/docs/r/composer_environment.html.markdown
  third_party/terraform/website/docs/r/compute_instance.html.markdown
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
  third_party/terraform/website/docs/r/container_cluster.html.markdown
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
Labels: cla: yes

#4322 add support for IAM authentication to google_sql_user for #7512
  third_party/terraform/resources/resource_sql_user.go
  third_party/terraform/tests/resource_sql_user_test.go
  third_party/terraform/website/docs/r/sql_user.html.markdown
Labels: cla: no

#4329 Correct documentation for importing google_service_account_iam
  third_party/terraform/website/docs/r/google_service_account_iam.html.markdown
Labels: cla: no

#4330 fix tests failures
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#4324 Add support for enableIndependentEndpointMapping to router nat
  products/compute/api.yaml
  third_party/terraform/tests/resource_compute_router_nat_test.go.erb
Labels: cla: yes

#4332 Fix typos from cleaning up IAM Scopes
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
  third_party/terraform/website/docs/r/container_cluster.html.markdown
  third_party/terraform/website/docs/r/container_node_pool.html.markdown
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
  third_party/terraform/website/docs/r/google_service_account.html.markdown
  third_party/terraform/website/docs/r/google_service_account_key.html.markdown
Labels: cla: yes

#4318 Remove TestAccComputeBackendService_backendServiceCacheExample from tpg.
  products/compute/terraform.yaml
  templates/terraform/examples/backend_service_cache_simple.tf.erb
Labels: cla: yes

#4339 Update SCC docs link (was incorrectly binauth)
  products/securitycenter/api.yaml
Labels: cla: yes

#4341 dataproc_job add support for job status RUNNING
  third_party/terraform/utils/dataproc_job_operation.go
Labels: cla: yes

#4298 Fix path_matcher in region url maps
  products/compute/api.yaml
  third_party/terraform/tests/resource_compute_region_url_map_test.go.erb
Labels: cla: yes

#4345 Add customized diff scenario for google_container_cluster.private_cluster_config.master_ipv4_cidr_block
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#4337 Add diff suppress for max retry 0s on google_cloud_tasks_queue.retry_config.max_retry_duration
  compiler.rb
  products/cloudtasks/terraform.yaml
  provider/file_template.rb
  templates/terraform/constants/cloud_tasks_retry_config_custom_diff.go
  third_party/terraform/tests/resource_cloud_tasks_queue_test.go.erb
Labels: cla: yes

#4342 Add ga version of bigquery reservation
  products/bigqueryreservation/api.yaml
  products/bigqueryreservation/terraform.yaml
  templates/terraform/examples/bigquery_reservation_basic.tf.erb
Labels: cla: yes

#4334 Eliminate retries in the inner loop for errors that will not succeed.
  products/filestore/terraform.yaml
  products/storage/terraform.yaml
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#4282 Upstream Bigtable seconds
  third_party/terraform/resources/resource_bigtable_gc_policy.go
  third_party/terraform/tests/resource_bigtable_gc_policy_test.go
  third_party/terraform/website/docs/r/bigtable_gc_policy.html.markdown
Labels: cla: no

#4343 Always set master_global_access_config in google_container_cluster
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: cla: yes

#4326 Promote Confidential VM to GA
  third_party/terraform/resources/resource_compute_instance.go.erb
  third_party/terraform/resources/resource_compute_instance_template.go.erb
  third_party/terraform/tests/resource_compute_instance_template_test.go.erb
  third_party/terraform/tests/resource_compute_instance_test.go.erb
  third_party/terraform/utils/compute_instance_helpers.go.erb
  third_party/terraform/website/docs/r/compute_instance.html.markdown
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
Labels: cla: yes

#4314 Promote Redis Auth to GA
  products/redis/api.yaml
  products/redis/terraform.yaml
  templates/terraform/decoders/redis_instance.go.erb
  templates/terraform/extra_schema_entry/redis_instance.erb
  third_party/terraform/tests/resource_redis_instance_test.go
Labels: cla: yes

#4331 Fixed setting kubelet_config to disable cpu_cfs_quota does not seem to work
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/utils/node_config.go.erb
Labels: cla: yes

#4351 Update RELEASE_NOTES_GUIDE.md
  .ci/RELEASE_NOTES_GUIDE.md
Labels: cla: yes

#4340 Fixed google_logging_project_sink.disabled can not updated
  third_party/terraform/resources/resource_logging_sink.go
  third_party/terraform/tests/resource_logging_project_sink_test.go
Labels: cla: yes

#3911 [Compute_Disk] - Add beta multi-writer support
  products/compute/api.yaml
  third_party/terraform/tests/resource_compute_disk_test.go.erb
Labels: cla: yes

#4353 Fix some network / firewall prefixes to allow sweeping
  third_party/terraform/tests/data_source_google_compute_subnetwork_test.go
  third_party/terraform/tests/resource_compute_firewall_test.go.erb
  third_party/terraform/tests/resource_compute_network_peering_test.go
  third_party/terraform/tests/resource_compute_network_test.go
Labels: cla: yes

#4352 Add SQL Backup Run Datasource
  third_party/terraform/data_sources/data_source_sql_backup_run.go
  third_party/terraform/tests/data_source_sql_backup_run_test.go
  third_party/terraform/utils/bootstrap_utils_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/sql_backup_run.html.markdown
Labels: cla: yes

#4350 GA packet mirroring, add filter direction, ga mirroring collector flag
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/compute_packet_mirroring_full.tf.erb
Labels: cla: yes
