Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2020-05, with the labels that each got.

#3443 Add back requireds on stripquery
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/terraform.yaml
Labels: cla: yes

#3454 Add default value for advertise_mode on compute_router_peer
  products/compute/terraform.yaml
Labels: cla: yes

#3458 Fix metadata for storage bucket object
  third_party/terraform/data_sources/data_source_google_storage_bucket_object.go
  third_party/terraform/resources/resource_storage_bucket_object.go
Labels: cla: yes

#3462 Change credentials to sensitive
  third_party/terraform/data_sources/data_source_storage_object_signed_url.go
Labels: cla: yes

#3456 Update PR template to request everyone write release notes.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: cla: yes

#3459 kalm (K8s Application lifecycle manager) addon config added
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3463 Make retryConfig computed for Cloud Scheduler jobs
  products/cloudscheduler/terraform.yaml
  templates/terraform/examples/scheduler_job_app_engine.tf.erb
  templates/terraform/examples/scheduler_job_http.tf.erb
  third_party/terraform/tests/resource_cloud_scheduler_job_test.go
Labels: cla: yes

#3440 Stateful mig instance
  overrides/terraform/resource_override.rb
  products/appengine/terraform.yaml
  products/bigquery/terraform.yaml
  products/cloudrun/terraform.yaml
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  provider/terraform/virtual_fields.rb
  templates/terraform/custom_expand/preserved_state_disks.go.erb
  templates/terraform/custom_flatten/preserved_state_disks.go.erb
  templates/terraform/encoders/compute_per_instance_config.go.erb
  templates/terraform/examples/stateful_igm.tf.erb
  templates/terraform/post_update/compute_per_instance_config.go.erb
  templates/terraform/pre_delete/compute_per_instance_config.go.erb
  templates/terraform/resource.erb
  templates/terraform/update_encoder/compute_per_instance_config.go.erb
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go.erb
  third_party/terraform/tests/resource_compute_per_instance_config_test.go.erb
Labels: cla: yes

#3457 Fix bigquery table google_sheets_options
  third_party/terraform/resources/resource_bigquery_table.go.erb
  third_party/terraform/tests/resource_bigquery_table_test.go.erb
Labels: cla: yes

#3465 Fix tests requiring strip_query
  templates/terraform/examples/region_target_http_proxy_https_redirect.tf.erb
  templates/terraform/examples/target_http_proxy_https_redirect.tf.erb
  third_party/terraform/tests/resource_compute_region_url_map_test.go.erb
  third_party/terraform/tests/resource_compute_url_map_test.go.erb
Labels: cla: yes

#3464 add version to FHIR tests
  third_party/terraform/tests/resource_healthcare_fhir_store_iam_test.go
  third_party/terraform/tests/resource_healthcare_fhir_store_test.go
Labels: cla: yes

#3467 Replace self link 1 for #5542
  templates/terraform/examples/access_context_manager_access_level_basic.tf.erb
  templates/terraform/examples/backend_service_basic.tf.erb
  templates/terraform/examples/backend_service_signed_url_key.tf.erb
  templates/terraform/examples/backend_service_traffic_director_ring_hash.tf.erb
  templates/terraform/examples/backend_service_traffic_director_round_robin.tf.erb
  templates/terraform/examples/compute_packet_mirroring_full.tf.erb
  templates/terraform/examples/dns_managed_zone_private.tf.erb
  templates/terraform/examples/dns_managed_zone_private_forwarding.tf.erb
  templates/terraform/examples/dns_managed_zone_private_peering.tf.erb
  templates/terraform/examples/dns_policy_basic.tf.erb
  templates/terraform/examples/forwarding_rule_basic.tf.erb
  templates/terraform/examples/forwarding_rule_global_internallb.tf.erb
  templates/terraform/examples/forwarding_rule_http_lb.tf.erb
  templates/terraform/examples/forwarding_rule_internallb.tf.erb
Labels: cla: yes

#3452 Add test for key types, fix service account keys resource
  products/iam/api.yaml
  templates/inspec/examples/google_service_account_key/google_service_account_key.erb
  templates/inspec/examples/google_service_account_key/google_service_account_keys.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
Labels: cla: yes

#2526 Add dataproc component gateway
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
Labels: cla: yes, downstream-generated, terraform-provider-google, terraform-provider-google-beta

#3472 Move enable_shielded_nodes from beta to GA.
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3470 Move cloudrun_config from beta to GA, fix doc.
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3476 Cause node pool to be written to statefile even if creation fails.
  third_party/terraform/resources/resource_container_node_pool.go.erb
Labels: cla: yes

#3471 Fix bigquery dataset access iam roles with primative equivalent
  products/bigquery/api.yaml
  products/bigquery/terraform.yaml
  templates/terraform/constants/bigquery_dataset_access.go
  templates/terraform/custom_expand/bigquery_access_role.go.erb
  third_party/terraform/tests/resource_bigquery_dataset_access_test.go
Labels: cla: yes

#3477 Update Cloud SQL high availability flag documentation
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: yes

#3430 Provide links to other objects
  products/compute/terraform.yaml
Labels: cla: yes, community

#3469 Retry internal errors from cloud SQL.
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/resources/resource_sql_user.go
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#3466 Stateful mig instance regional
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/stateful_rigm.tf.erb
  templates/terraform/post_update/compute_region_per_instance_config.go.erb
  third_party/terraform/tests/resource_compute_region_per_instance_config_test.go.erb
Labels: cla: yes

#3461 VCR body comparison fixes
  products/identityplatform/terraform.yaml
  templates/terraform/custom_check_destroy/storage_hmac_key.go.erb
  third_party/terraform/resources/resource_sql_ssl_cert_test.go
  third_party/terraform/tests/resource_google_folder_iam_binding_test.go
  third_party/terraform/tests/resource_google_folder_iam_member_test.go
  third_party/terraform/tests/resource_google_folder_iam_policy_test.go
  third_party/terraform/tests/resource_google_project_iam_audit_config_test.go
  third_party/terraform/tests/resource_google_project_iam_binding_test.go.erb
  third_party/terraform/tests/resource_google_project_iam_member_test.go.erb
  third_party/terraform/tests/resource_google_project_iam_policy_test.go.erb
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/iam.go.erb
  third_party/terraform/utils/metadata.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/utils/utils.go.erb
Labels: cla: yes

#3265 Add region_backend_service portName
  products/compute/api.yaml
  products/compute/terraform.yaml
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
Labels: cla: yes, community

#3488 Fix compute instance metadata methods, dns managed zone defaults
  templates/inspec/examples/google_compute_instance/google_compute_instance.erb
  third_party/inspec/custom_functions/dns_managed_zone.erb
  third_party/inspec/custom_functions/google_compute_instance.erb
Labels: cla: yes

#3483 Add new enum values to dataproc cluster.
  products/dataproc/api.yaml
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
Labels: cla: yes

#3492 Fix test with partial revert of #3467.
  templates/terraform/examples/dns_managed_zone_private.tf.erb
  templates/terraform/examples/dns_managed_zone_private_forwarding.tf.erb
  templates/terraform/examples/dns_managed_zone_private_peering.tf.erb
Labels: cla: yes

#3487 Dialogflow EntityType Resource
  products/dialogflow/api.yaml
  products/dialogflow/terraform.yaml
  templates/terraform/examples/dialogflow_entity_type_basic.tf.erb
  third_party/terraform/tests/resource_dialogflow_entity_type_test.go.erb
Labels: cla: yes

#3495 add docs for app engine application iap block
  third_party/terraform/website/docs/r/app_engine_application.html.markdown
Labels: cla: yes

#3493 Set network_tier to forcenew.
  third_party/terraform/resources/resource_compute_instance_template.go
Labels: cla: yes

#3497 Remove portNames for default INTERNAL backend services in tests
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
Labels: cla: yes

#3478 Replace self_link (part 2 of #5542)
  templates/terraform/examples/global_forwarding_rule_http.tf.erb
  templates/terraform/examples/global_forwarding_rule_internal.tf.erb
  templates/terraform/examples/global_network_endpoint.tf.erb
  templates/terraform/examples/ha_vpn_gateway_basic.tf.erb
  templates/terraform/examples/ha_vpn_gateway_gcp_to_gcp.tf.erb
  templates/terraform/examples/interconnect_attachment_basic.tf.erb
  templates/terraform/examples/kms_crypto_key_asymmetric_sign.tf.erb
  templates/terraform/examples/kms_crypto_key_basic.tf.erb
  templates/terraform/examples/managed_ssl_certificate_basic.tf.erb
  templates/terraform/examples/managed_ssl_certificate_recreation.tf.erb
  templates/terraform/examples/network_endpoint.tf.erb
  templates/terraform/examples/network_endpoint_group.tf.erb
  templates/terraform/examples/network_peering_routes_config_basic.tf.erb
  templates/terraform/examples/node_group_autoscaling_policy.tf.erb
  templates/terraform/examples/node_group_basic.tf.erb
  templates/terraform/examples/pubsub_topic_cmek.tf.erb
  templates/terraform/examples/redis_instance_full.tf.erb
  templates/terraform/examples/redis_instance_private_service.tf.erb
Labels: cla: yes

#3491 Added support for request-based SLIs in monitoring SLO
  products/monitoring/api.yaml
  products/monitoring/terraform.yaml
  provider/terraform.rb
  spec/compiler_spec.rb
  spec/data/good-file.yaml
  spec/data/good-tf-override.yaml
  spec/data/terraform-config.yaml
  spec/provider_terraform_spec.rb
  templates/terraform/examples/monitoring_slo_request_based.tf.erb
  templates/terraform/schema_property.erb
  templates/terraform/update_mask.erb
  third_party/terraform/tests/resource_monitoring_slo_test.go
Labels: cla: yes

#3501 report bucket name when not empty while deleting
  third_party/terraform/resources/resource_storage_bucket.go
Labels: cla: yes

#3450 add deletion_protection field for bigtable instance
  products/bigtable/terraform.yaml
  provider/terraform/examples.rb
  templates/terraform/examples/bigtable_app_profile_multicluster.tf.erb
  templates/terraform/examples/bigtable_app_profile_singlecluster.tf.erb
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/resources/resource_bigtable_instance_migrate.go
  third_party/terraform/tests/resource_bigtable_app_profile_test.go
  third_party/terraform/tests/resource_bigtable_gc_policy_test.go
  third_party/terraform/tests/resource_bigtable_instance_iam_test.go
  third_party/terraform/tests/resource_bigtable_instance_test.go
  third_party/terraform/tests/resource_bigtable_table_test.go
  third_party/terraform/website/docs/r/bigtable_instance.html.markdown
Labels: cla: yes

#3500 Add Cloud Run - Traffic Splitting example
  products/cloudrun/terraform.yaml
  templates/terraform/examples/cloud_run_service_traffic_split.tf.erb
Labels: cla: yes

#3504 Use "terraform" in "client-name" annotation
  templates/terraform/examples/cloud_run_service_sql.tf.erb
  third_party/terraform/website/docs/guides/version_3_upgrade.html.markdown
Labels: cla: yes

#3498 configConnector GKE addon config added to cluster resource
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3499 if google_compute_region_disk_resource_policy_attachment is empty, shouldn't error
  templates/terraform/nested_query.go.erb
Labels: cla: yes

#3506 Add back changelog template
  .ci/changelog.tmpl
Labels: cla: yes

#3509 Add support for GKE release channel updates
  third_party/terraform/data_sources/data_source_google_container_engine_versions.go.erb
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/d/google_container_engine_versions.html.markdown
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3508 Add back .ci/release-note.tmpl
  .ci/release-note.tmpl
Labels: cla: yes

#3486 Vcr ignore tests
  products/compute/terraform.yaml
  products/dns/terraform.yaml
  products/spanner/terraform.yaml
  provider/terraform/examples.rb
  templates/terraform/examples/base_configs/test_file.go.erb
  third_party/terraform/data_sources/data_source_compute_network_endpoint_group_test.go
  third_party/terraform/resources/resource_compute_instance_iam_test.go
  third_party/terraform/tests/data_source_google_compute_region_instance_group_test.go.erb
  third_party/terraform/tests/resource_access_context_manager_service_perimeter_resource_test.go
  third_party/terraform/tests/resource_bigquery_dataset_access_test.go
  third_party/terraform/tests/resource_compute_disk_test.go.erb
  third_party/terraform/tests/resource_compute_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_instance_template_test.go
  third_party/terraform/tests/resource_compute_instance_test.go
  third_party/terraform/tests/resource_compute_network_endpoint_test.go.erb
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_ssl_certificate_test.go
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
  third_party/terraform/tests/resource_dialogflow_intent_test.go.erb
  third_party/terraform/tests/resource_firebase_web_app_test.go.erb
  third_party/terraform/tests/resource_google_folder_iam_binding_test.go
  third_party/terraform/tests/resource_google_folder_iam_member_test.go
  third_party/terraform/tests/resource_google_organization_iam_audit_config_test.go
  third_party/terraform/tests/resource_google_project_iam_audit_config_test.go
  third_party/terraform/tests/resource_google_project_iam_binding_test.go.erb
  third_party/terraform/tests/resource_google_project_iam_member_test.go.erb
  third_party/terraform/tests/resource_google_project_service_test.go
  third_party/terraform/tests/resource_service_directory_namespace_test.go.erb
  third_party/terraform/tests/resource_service_directory_service_test.go.erb
  third_party/terraform/tests/resource_spanner_instance_test.go
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
  third_party/terraform/tests/resource_sql_user_test.go
  third_party/terraform/utils/bootstrap_utils_test.go
  third_party/terraform/utils/metadata.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/provider_test.go.erb
Labels: cla: yes

#3510 Add window based SLI
  products/monitoring/api.yaml
  products/monitoring/terraform.yaml
  templates/terraform/examples/monitoring_slo_windows_based_good_bad_metric_filter.tf.erb
  templates/terraform/examples/monitoring_slo_windows_based_metric_mean.tf.erb
  templates/terraform/examples/monitoring_slo_windows_based_metric_sum.tf.erb
  templates/terraform/examples/monitoring_slo_windows_based_ratio_threshold.tf.erb
  third_party/terraform/tests/resource_monitoring_slo_test.go
Labels: cla: yes

#3460 Data source for IAM Testable Permissions
  third_party/terraform/data_sources/data_source_google_iam_testable_permissions.go
  third_party/terraform/tests/data_source_google_iam_testable_permissions_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/datasource_iam_testable_permissions.html.markdown
Labels: cla: yes

#3475 Fix node pool tests.
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
Labels: cla: yes

#3513 Add retry to service account creation
  third_party/terraform/resources/resource_google_service_account.go
  third_party/terraform/website/docs/r/google_service_account.html.markdown
Labels: cla: yes

#3503 Composer access control
  third_party/terraform/resources/resource_composer_environment.go.erb
  third_party/terraform/tests/resource_composer_environment_test.go.erb
  third_party/terraform/website/docs/r/composer_environment.html.markdown
Labels: cla: yes

#3516 cloud app armor: Maximum number of src_ip_ranges is 10
  third_party/terraform/resources/resource_compute_security_policy.go.erb
Labels: cla: yes

#3507 Add descriptions to schema #1
  third_party/terraform/resources/resource_bigtable_instance.go
Labels: cla: yes

#3522 Update environment variable `GOOGLE_CLOUD_KEYFILE_JSON`
  third_party/terraform/website/docs/guides/getting_started.html.markdown
Labels: cla: no

#3519 allow bigquery job fields that reference resources in blocks to do so with one field
  products/bigquery/terraform.yaml
  provider/terraform/examples.rb
  templates/terraform/constants/bigquery_job.go
  templates/terraform/custom_expand/bigquery_dataset_ref.go.erb
  templates/terraform/custom_expand/bigquery_table_ref.go.erb
  templates/terraform/custom_expand/bigquery_table_ref_array.go.erb
  templates/terraform/custom_flatten/bigquery_dataset_ref.go.erb
  templates/terraform/custom_flatten/bigquery_table_ref.go.erb
  templates/terraform/custom_flatten/bigquery_table_ref_copy_destinationtable.go.erb
  templates/terraform/custom_flatten/bigquery_table_ref_copy_sourcetables.go.erb
  templates/terraform/custom_flatten/bigquery_table_ref_extract_sourcetable.go.erb
  templates/terraform/custom_flatten/bigquery_table_ref_load_destinationtable.go.erb
  templates/terraform/custom_flatten/bigquery_table_ref_query_destinationtable.go.erb
  templates/terraform/examples/bigquery_job_copy_table_reference.tf.erb
  templates/terraform/examples/bigquery_job_extract_table_reference.tf.erb
  templates/terraform/examples/bigquery_job_load_table_reference.tf.erb
  templates/terraform/examples/bigquery_job_query_table_reference.tf.erb
  templates/terraform/flatten_property_method.erb
  templates/terraform/resource.html.markdown.erb
Labels: cla: yes

#3511 Single quotes
  third_party/inspec/custom_functions/google_compute_instance.erb
Labels: cla: yes

#3521 Fix composer resource names
  third_party/terraform/tests/resource_composer_environment_test.go.erb
Labels: cla: yes

#3526 Skip tests due to GKE version constraints
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#3518 Add compute_route retry for "peering operation in progress"
  products/compute/terraform.yaml
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#3525 Single quotes
  third_party/inspec/custom_functions/google_compute_instance.erb
Labels: cla: yes

#3529 Check for diffs in allowed ranges set
  third_party/terraform/resources/resource_composer_environment.go.erb
Labels: cla: yes

#3538 Mark interconnect edge availability domain as computed
  products/compute/terraform.yaml
Labels: cla: yes

#3534 Exact domain matching for organization data source
  third_party/terraform/data_sources/data_source_google_organization.go
Labels: cla: yes

#3496 Add disk encryption settings and status to sql instance
  products/sql/api.yaml
Labels: cla: yes

#3383 add min_cpu_platform to google_container_cluster.cluster_autoscaling.auto_provisioning_defaults
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3530 Use self link for DNS networks
  templates/terraform/examples/dns_policy_basic.tf.erb
Labels: cla: yes

#3490 stackdriver dashboards resource
  products/monitoring/api.yaml
  products/monitoring/inspec.yaml
  templates/terraform/objectlib/base.go.erb
  third_party/terraform/resources/resource_monitoring_dashboard.go
  third_party/terraform/tests/resource_monitoring_dashboard_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/guides/provider_reference.html.markdown
  third_party/terraform/website/docs/r/monitoring_dashboard.html.markdown
Labels: cla: yes

#3541 Empty reservations must ignore empty
  templates/terraform/examples/bigquery_reservation_basic.tf.erb
  third_party/terraform/tests/resource_bigquery_reservation_test.go.erb
Labels: cla: yes

#3540 use explicit version in monitoring data sources
  third_party/terraform/data_sources/data_source_monitoring_notification_channel.go
  third_party/terraform/data_sources/data_source_monitoring_service.go
Labels: cla: yes

#3512 Allow update of node pool workload metadata config
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/resources/resource_container_node_pool.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
  third_party/terraform/utils/node_config.go.erb
  third_party/terraform/utils/utils.go.erb
Labels: cla: yes

#3542 Dataset access viewer is primitive role READER not VIEWER
  templates/terraform/constants/bigquery_dataset_access.go
  third_party/terraform/tests/resource_bigquery_dataset_access_test.go
Labels: cla: yes

#3533 Ga secret manager
  products/secretmanager/api.yaml
  products/secretmanager/terraform.yaml
  templates/terraform/examples/secret_config_basic.tf.erb
  templates/terraform/examples/secret_version_basic.tf.erb
  third_party/terraform/data_sources/data_source_secret_manager_secret_version.go.erb
  third_party/terraform/tests/data_source_secret_manager_secret_version_test.go.erb
  third_party/terraform/tests/resource_secret_manager_secret_test.go.erb
  third_party/terraform/tests/resource_secret_manager_secret_version_test.go.erb
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/datasource_google_secret_manager_secret_version.html.markdown
Labels: cla: yes

#3543 Mark ssh key as force new
  products/oslogin/api.yaml
Labels: cla: yes

#3536 Fix fetching of app_engine_standard_app_version data
  products/appengine/api.yaml
  products/appengine/terraform.yaml
Labels: cla: yes

#3535 add id and replace self_link in docs (part 5 of #5542)
  third_party/terraform/website/docs/r/compute_instance_from_template.html.markdown
  third_party/terraform/website/docs/r/compute_instance_group.html.markdown
  third_party/terraform/website/docs/r/compute_instance_group_manager.html.markdown
  third_party/terraform/website/docs/r/compute_instance_template.html.markdown
  third_party/terraform/website/docs/r/compute_network_peering.html.markdown
  third_party/terraform/website/docs/r/compute_region_instance_group_manager.html.markdown
  third_party/terraform/website/docs/r/dns_record_set.html.markdown
  third_party/terraform/website/docs/r/google_kms_crypto_key_iam.html.markdown
  third_party/terraform/website/docs/r/google_project.html.markdown
  third_party/terraform/website/docs/r/google_project_iam.html.markdown
  third_party/terraform/website/docs/r/google_project_service.html.markdown
  third_party/terraform/website/docs/r/google_service_account.html.markdown
  third_party/terraform/website/docs/r/google_service_account_key.html.markdown
  third_party/terraform/website/docs/r/service_networking_connection.html.markdown
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: yes

#3485 Data Catalog EntryGroup
  products/datacatalog/api.yaml
  products/datacatalog/terraform.yaml
  templates/terraform/examples/data_catalog_entry_group_basic.tf.erb
  templates/terraform/examples/data_catalog_entry_group_full.tf.erb
  third_party/terraform/tests/resource_data_catalog_entry_group_test.go
Labels: cla: yes

#3524 Promote DNS resources to GA
  products/dns/ansible.yaml
  products/dns/api.yaml
  products/dns/terraform.yaml
  templates/terraform/examples/dns_managed_zone_private_forwarding.tf.erb
  templates/terraform/examples/dns_managed_zone_private_peering.tf.erb
  templates/terraform/examples/dns_policy_basic.tf.erb
  third_party/terraform/tests/data_source_dns_managed_zone_test.go.erb
  third_party/terraform/tests/resource_dns_managed_zone_test.go.erb
  third_party/terraform/tests/resource_dns_policy_test.go.erb
Labels: cla: yes

#3532 Data Catalog Entry
  products/datacatalog/api.yaml
  products/datacatalog/terraform.yaml
  products/healthcare/terraform.yaml
  templates/terraform/custom_expand/json_schema.erb
  templates/terraform/custom_flatten/json_schema.erb
  templates/terraform/custom_import/data_catalog_entry.go.erb
  templates/terraform/custom_import/data_catalog_entry_group.go.erb
  templates/terraform/examples/data_catalog_entry_basic.tf.erb
  templates/terraform/examples/data_catalog_entry_fileset.tf.erb
  templates/terraform/examples/data_catalog_entry_full.tf.erb
  templates/terraform/examples/data_catalog_tag_template_basic.tf.erb
  third_party/terraform/tests/resource_data_catalog_entry_group_test.go
  third_party/terraform/tests/resource_data_catalog_entry_test.go
Labels: cla: yes

#3531 Fix more VCR tests
  products/compute/terraform.yaml
  third_party/terraform/data_sources/data_source_monitoring_service_test.go
  third_party/terraform/tests/data_source_google_kms_secret_test.go
  third_party/terraform/tests/data_source_storage_object_signed_url_test.go
  third_party/terraform/tests/resource_compute_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_instance_test.go
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_resource_policy_test.go
  third_party/terraform/tests/resource_dataflow_job_test.go
  third_party/terraform/tests/resource_dialogflow_entity_type_test.go.erb
  third_party/terraform/tests/resource_dialogflow_intent_test.go.erb
  third_party/terraform/tests/resource_firebase_web_app_test.go.erb
  third_party/terraform/tests/resource_google_folder_iam_binding_test.go
  third_party/terraform/tests/resource_kms_crypto_key_test.go
  third_party/terraform/tests/resource_logging_bucket_config_test.go
  third_party/terraform/tests/resource_monitoring_slo_test.go
  third_party/terraform/tests/resource_service_directory_endpoint_test.go.erb
  third_party/terraform/tests/resource_service_directory_namespace_test.go.erb
  third_party/terraform/tests/resource_service_directory_service_test.go.erb
  third_party/terraform/tests/resource_storage_bucket_test.go
  third_party/terraform/utils/provider_test.go.erb
Labels: cla: yes

#3550 fix issue #6436
  products/spanner/terraform.yaml
Labels: cla: yes

#3551 adding id for exported attributes in more manual docs
  third_party/terraform/website/docs/r/logging_billing_account_bucket_config.html.markdown
  third_party/terraform/website/docs/r/logging_billing_account_exclusion.html.markdown
  third_party/terraform/website/docs/r/logging_billing_account_sink.html.markdown
  third_party/terraform/website/docs/r/logging_folder_bucket_config.html.markdown
  third_party/terraform/website/docs/r/logging_folder_exclusion.html.markdown
  third_party/terraform/website/docs/r/logging_folder_sink.html.markdown
  third_party/terraform/website/docs/r/logging_organization_bucket_config.html.markdown
  third_party/terraform/website/docs/r/logging_organization_exclusion.html.markdown
  third_party/terraform/website/docs/r/logging_organization_sink.html.markdown
  third_party/terraform/website/docs/r/logging_project_bucket_config.html.markdown
  third_party/terraform/website/docs/r/logging_project_exclusion.html.markdown
  third_party/terraform/website/docs/r/logging_project_sink.html.markdown
  third_party/terraform/website/docs/r/runtimeconfig_config.html.markdown
  third_party/terraform/website/docs/r/runtimeconfig_variable.html.markdown
Labels: cla: yes

#3552 Use correct import format for iam member docs
  templates/terraform/resource_iam.html.markdown.erb
Labels: cla: yes

#3545 continue updates for view=full app engine version
  products/appengine/api.yaml
  products/appengine/terraform.yaml
  templates/terraform/examples/app_engine_flexible_app_version.tf.erb
Labels: cla: yes

#3357 Auto-generate the Cloud IoT Core Device Registry resource
  products/cloudiot/api.yaml
  products/cloudiot/terraform.yaml
  templates/terraform/constants/cloudiot.go.erb
  templates/terraform/decoders/cloudiot_device_registry.go.erb
  templates/terraform/encoders/cloudiot_device_registry.go.erb
  templates/terraform/examples/cloudiot_device_registry_basic.tf.erb
  templates/terraform/examples/cloudiot_device_registry_full.tf.erb
  templates/terraform/examples/cloudiot_device_registry_single_event_notification_configs.tf.erb
  templates/terraform/extra_schema_entry/cloudiot_device_registry.go.erb
  templates/terraform/pre_update/cloudiot_device_registry.go.erb
  third_party/terraform/resources/resource_cloudiot_registry.go
  third_party/terraform/tests/resource_cloudiot_device_registry_id_test.go
  third_party/terraform/tests/resource_cloudiot_device_registry_update_test.go
  third_party/terraform/tests/resource_cloudiot_registry_test.go
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/provider_handwritten_endpoint.go.erb
  third_party/terraform/website/docs/r/cloudiot_registry.html.markdown
Labels: cla: yes

#3553 google_bigquery_job - suppress diffs between fully qualified URLs and relative paths that reference the same table or dataset
  products/bigquery/terraform.yaml
Labels: cla: yes

#3568 docs(cloudsql): complete POSTGRES version list
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: no

#3556 Create the MachineImage resource
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/machine_image_basic.tf.erb
Labels: cla: yes

#3567 Make dataflow on_delete a virtual field
  third_party/terraform/resources/resource_dataflow_job.go
  third_party/terraform/tests/resource_dataflow_job_test.go
Labels: cla: yes

#3546 Add credentials to bigquery connection.
  products/bigqueryconnection/api.yaml
  products/bigqueryconnection/terraform.yaml
  templates/terraform/custom_flatten/bigquery_connection_flatten.go.erb
  templates/terraform/examples/bigquery_connection_basic.tf.erb
  templates/terraform/examples/bigquery_connection_full.tf.erb
  third_party/terraform/tests/resource_bigquery_connection_test.go.erb
Labels: cla: yes

#3554 Skip instance migrate tests, they handle config directly
  third_party/terraform/tests/resource_bigtable_app_profile_test.go
  third_party/terraform/tests/resource_bigtable_gc_policy_test.go
  third_party/terraform/tests/resource_bigtable_instance_iam_test.go
  third_party/terraform/tests/resource_bigtable_instance_test.go
  third_party/terraform/tests/resource_bigtable_table_test.go
  third_party/terraform/tests/resource_compute_instance_migrate_test.go
Labels: cla: yes

#3571 Remove credentials from error message in TF
  third_party/terraform/utils/config.go.erb
Labels: cla: yes

#3564 Support containeranalysis Note and Occurence for attestation
  products/containeranalysis/api.yaml
  products/containeranalysis/terraform.yaml
  templates/terraform/decoders/containeranalysis_occurrence.go.erb
  templates/terraform/encoders/containeranalysis_occurrence.go.erb
  templates/terraform/examples/container_analysis_note_attestation_full.tf.erb
  templates/terraform/examples/container_analysis_occurence_attestation.tf.erb
  templates/terraform/examples/container_analysis_occurrence_kms.tf.erb
  templates/terraform/update_encoder/containeranalysis_occurrence.go.erb
  third_party/terraform/tests/resource_container_analysis_occurrence_test.go
  third_party/terraform/utils/bootstrap_utils_test.go
  third_party/terraform/utils/test-fixtures/binauthz/generated_payload.json.tmpl
Labels: cla: yes

#3515 Add precondition retry to node pool deletion - upstreams tpg#6334
  third_party/terraform/resources/resource_container_node_pool.go.erb
Labels: cla: yes

#3570 Add retry on cloud functions error when pulling source from GCS
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/utils/common_operation.go
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#3573 Add dependency change handbook.
  .ci/README.md
Labels: cla: yes

#3574 Fixed typos in website for google_iam_testable_permissions
  third_party/terraform/website/docs/d/datasource_iam_testable_permissions.html.markdown
Labels: cla: yes

#3575 replace self_link for external_vpn_gateway
  templates/terraform/examples/external_vpn_gateway.tf.erb
Labels: cla: yes

#3555 Data Catalog tag template
  products/datacatalog/api.yaml
  products/datacatalog/terraform.yaml
  templates/terraform/custom_import/data_catalog_tag_template.go.erb
  templates/terraform/examples/data_catalog_tag_template_basic.tf.erb
Labels: cla: yes

#3547 Vcr cloud build
  .ci/containers/terraform-vcr-tester/Dockerfile
  .ci/containers/terraform-vcr-tester/teamcityparams.xml
  .ci/containers/terraform-vcr-tester/vcr_test_terraform.sh
  .ci/gcb-generate-diffs.yml
Labels: cla: yes

#3335 Terraform BigQuery Table Hive partitioning support
  third_party/terraform/resources/resource_bigquery_table.go
  third_party/terraform/tests/resource_bigquery_table_test.go
  third_party/terraform/website/docs/r/bigquery_table.html.markdown
Labels: cla: yes, community

#3579 Add post-create retry for big query job
  products/bigquery/terraform.yaml
Labels: cla: yes

#3580 Move workload identity to GA
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#3581 allow updating (R)IGM target pools to empty
  third_party/terraform/resources/resource_compute_instance_group_manager.go.erb
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go.erb
  third_party/terraform/tests/resource_compute_instance_group_manager_test.go.erb
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go.erb
Labels: cla: yes

#3583 Add post-merge VCR copy step
  .ci/containers/terraform-vcr-tester/teamcityparams.xml
  .ci/containers/terraform-vcr-tester/vcr_test_terraform.sh
  .ci/containers/vcr-cassette-merger/Dockerfile
  .ci/containers/vcr-cassette-merger/vcr_merge.sh
  .ci/gcb-push-downstream.yml
Labels: cla: yes

#3560 add desc to schema for google_bigtable_table
  third_party/terraform/resources/resource_bigtable_table.go
Labels: cla: yes
