Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2020-03, with the labels that each got.

#2762 Fixed KeyError due to deletionProtection
  products/compute/helpers/python/instance_update_methods.py
Labels: cla: yes, community

#3188 Update appengine split traffic example to fix test
  products/appengine/terraform.yaml
  templates/terraform/examples/app_engine_service_split_traffic.tf.erb
Labels: cla: yes

#3192 Fix bigquery basic example test
  templates/terraform/examples/bigquery_dataset_basic.tf.erb
Labels: cla: yes

#3194 Fix `google_compute_instance_template` crash
  third_party/terraform/resources/resource_compute_instance_template.go
  third_party/terraform/tests/resource_compute_instance_template_test.go
Labels: cla: yes

#3195 Add support for google_iam_organization_custom_role to inspec
  products/iam/ansible.yaml
  products/iam/api.yaml
  products/iam/inspec.yaml
  products/resourcemanager/inspec.yaml
  templates/inspec/examples/attributes/external_attributes.yml
  templates/inspec/examples/google_iam_organization_custom_role/google_iam_organization_custom_role.erb
  templates/inspec/examples/google_iam_organization_custom_role/google_iam_organization_custom_role_attributes.erb
  templates/inspec/examples/google_iam_organization_custom_role/google_iam_organization_custom_roles.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
  templates/inspec/tests/integration/configuration/mm-attributes.yml
Labels: cla: yes

#3151 added website, cors and lifecycle examples to storage_bucket resource
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
Labels: cla: yes, community

#3182 `project_service` update to read/acquire a service on create
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/website/docs/r/google_project_service.html.markdown
Labels: cla: yes

#3197 Add missing fields to instance template's network_interfaces schema
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/resources/resource_compute_instance_template.go
Labels: cla: yes

#3155 Add 404-retries for pubsub and poll async utils
  api/async.rb
  products/cloudrun/api.yaml
  products/cloudrun/terraform.yaml
  products/pubsub/api.yaml
  products/pubsub/terraform.yaml
  provider/terraform.rb
  provider/terraform/async.rb
  templates/terraform/resource.erb
  third_party/terraform/tests/resource_pubsub_subscription_test.go
  third_party/terraform/utils/cloudrun_polling.go
  third_party/terraform/utils/common_polling.go
Labels: cla: yes

#3199 fixed id for 5542
  third_party/terraform/website/docs/r/app_engine_application.html.markdown
Labels: cla: yes, community

#3200 Ansible Default Object Access Control
  products/storage/ansible.yaml
  products/storage/ansible_version_added.yaml
  products/storage/examples/ansible/default_object_acl.yaml
Labels: cla: yes

#3203 Remove mutex locking during read for storage ACLs.
  third_party/terraform/resources/resource_storage_bucket_acl.go
  third_party/terraform/resources/resource_storage_default_object_acl.go
  third_party/terraform/resources/resource_storage_object_acl.go
Labels: cla: yes

#3206 Fix bigquery dataset test to use valid userByEmail
  products/bigquery/terraform.yaml
  templates/terraform/examples/bigquery_dataset_basic.tf.erb
Labels: cla: yes

#3209 Move drain_nat_ips to GA from beta.
  products/compute/api.yaml
Labels: cla: yes

#2907 update isEmptyValue function
  templates/terraform/resource.erb
  third_party/terraform/utils/transport.go
Labels: cla: yes, downstream-generated, terraform-google-conversion, terraform-provider-google, terraform-provider-google-beta

#3212 Ensure that code that doesn't compile returns useful errors.
  .ci/containers/terraform-tester/test_terraform.sh
Labels: cla: yes

#3208 Much longer docs about metadata attributes, including links to non-linux load-bearing attributes.
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#3214 Fix batcher error messages after single request split-out
  third_party/terraform/utils/batcher.go
  third_party/terraform/utils/batcher_test.go
Labels: cla: yes

#3215 fix race condition with modification of global state across processes.
  .ci/containers/downstream-builder/generate_downstream.sh
Labels: cla: yes

#3211 add vpc_connector to update
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
Labels: cla: yes

#3216 Remove extra address attribute from compute address.
  products/compute/terraform.yaml
Labels: cla: yes

#3218 Marked `time_zone` as ForceNew due to change in API behavior
  products/dialogflow/api.yaml
  third_party/terraform/tests/resource_dialogflow_agent_test.go.erb
Labels: cla: yes

#3202 add customize diff to prevent two rules with the same priority
  third_party/terraform/resources/resource_compute_security_policy.go.erb
  third_party/terraform/tests/resource_compute_security_policy_test.go.erb
Labels: cla: yes

#3223 Make tier ignore_read
  products/dialogflow/api.yaml
  products/dialogflow/terraform.yaml
  templates/terraform/post_create/dialogflow_agent_tier.go.erb
  third_party/terraform/tests/resource_dialogflow_agent_test.go.erb
Labels: cla: yes

#3222 bigtable_table and bigtable_gc_policy support long form ids
  third_party/terraform/resources/resource_bigtable_gc_policy.go
  third_party/terraform/resources/resource_bigtable_table.go
  third_party/terraform/tests/resource_bigtable_gc_policy_test.go
  third_party/terraform/tests/resource_bigtable_table_test.go
Labels: cla: yes

#3224 network endpoint support long form ids for network endpoint groups
  products/compute/terraform.yaml
  templates/terraform/encoders/compute_network_endpoint.go.erb
  third_party/terraform/tests/resource_compute_network_endpoint_test.go.erb
Labels: cla: yes

#3186 add sql_source_representation_instance
  products/sql/ansible.yaml
  products/sql/api.yaml
  products/sql/inspec.yaml
  products/sql/terraform.yaml
  templates/terraform/decoders/sql_source_representation_instance.go.erb
  templates/terraform/encoders/sql_source_representation_instance.go.erb
  templates/terraform/examples/sql_source_representation_instance_basic.tf.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3213 Bigquery reservation
  products/bigqueryreservation/api.yaml
  products/bigqueryreservation/terraform.yaml
  templates/terraform/examples/bigquery_reservation_basic.tf.erb
  third_party/terraform/tests/resource_bigquery_reservation_test.go.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3163 google_dataflow_job - Fix bug where the wrong error variable was bein…
  third_party/terraform/resources/resource_dataflow_job.go
Labels: cla: yes

#3226 Don't break the website by including things that aren't GA in the GA sidebar.
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3228 Regional disk resource policies attachment resource.
  products/compute/ansible.yaml
  products/compute/ansible_version_added.yaml
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  templates/terraform/encoders/compute_region_disk_resource_policies_attachment.go.erb
  templates/terraform/examples/region_disk_resource_policy_attachment_basic.tf.erb
  templates/terraform/pre_delete/compute_region_disk_resource_policies_attachment.go.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3229 s/zone/region in an error message.
  templates/terraform/encoders/compute_region_disk_resource_policies_attachment.go.erb
Labels: cla: yes

#3231 update link name for app engine service split traffic
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3232 bump container rake dependency
  .ci/containers/go-ruby/Gemfile.lock
Labels: cla: yes

#3217 Placement policy support for Compute Instance
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/resource_policy_placement_policy.tf.erb
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/tests/resource_compute_instance_test.go
  third_party/terraform/tests/resource_compute_resource_policy_test.go
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#3233 Bump rake
  .ci/containers/go-ruby-python/Dockerfile
Labels: cla: yes

#3235 storage_bucket: Correct website docs
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
Labels: cla: no

#3230 Add node group autoscaling policy
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/node_group_autoscaling_policy.tf.erb
Labels: cla: yes

#3238 update golang links
  products/cloudbuild/api.yaml
Labels: cla: yes

#3239 no-op: comment to explain ciphertext of token
  .ci/gcb-push-downstream.yml
Labels: cla: yes

#3234 Collapse sidebars by default.
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3177 Allow passwords and tokens to be sensitive
  products/monitoring/api.yaml
  products/monitoring/terraform.yaml
  templates/terraform/constants/monitoring_notification_channel.go.erb
  templates/terraform/custom_flatten/monitoring_obfuscated_labels.go.erb
  templates/terraform/decoders/monitoring_notification_channel.go.erb
  templates/terraform/encoders/monitoring_notification_channel.go.erb
  templates/terraform/examples/notification_channel_sensitive.tf.erb
  templates/terraform/resource_definition/monitoring_notification_channel.erb
  third_party/terraform/tests/resource_monitoring_notification_channel_test.go
Labels: cla: yes

#3240 add extra host_rule to example
  templates/terraform/examples/url_map_basic.tf.erb
Labels: cla: yes

#3241 Ensure that no matter what the ID is, we can still wait for state.
  third_party/terraform/resources/resource_container_node_pool.go.erb
Labels: cla: yes

#3243 Remove the last iap base path leftovers from handwritten tunnel
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/utils/provider_handwritten_endpoint.go.erb
Labels: cla: yes

#3135 IAP brand & client
  products/iap/api.yaml
  products/iap/terraform.yaml
  provider/terraform/examples.rb
  templates/terraform/custom_import/iap_brand.go.erb
  templates/terraform/custom_import/iap_client.go.erb
  templates/terraform/env_var_context.go.erb
  templates/terraform/examples/iap_brand.tf.erb
  templates/terraform/examples/iap_client.tf.erb
  templates/terraform/post_create/iap_client.go.erb
  third_party/terraform/tests/resource_iap_brand_test.go
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes, enhancement

#3110 add app engine flex version
  products/appengine/ansible.yaml
  products/appengine/api.yaml
  products/appengine/inspec.yaml
  products/appengine/terraform.yaml
  templates/terraform/custom_delete/appversion_delete.go.erb
  templates/terraform/encoders/flex_app_version.go.erb
  templates/terraform/examples/app_engine_flexible_app_version.tf.erb
  third_party/terraform/tests/resource_app_engine_app_version_sweeper_test.go
  third_party/terraform/tests/resource_app_engine_flexible_app_version_test.go
  third_party/terraform/utils/test-fixtures/appengine/hello-world-flask/app.yaml
  third_party/terraform/utils/test-fixtures/appengine/hello-world-flask/main.py
  third_party/terraform/utils/test-fixtures/appengine/hello-world-flask/requirements.txt
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3244 fix typos in billing account IAM docs
  third_party/terraform/website/docs/r/google_billing_account_iam_binding.html.markdown
Labels: cla: yes, community

#3245 Ignore empty vs null list in data source tests
  third_party/terraform/utils/test_utils.go
Labels: cla: yes

#3250 Revert "Placement policy support for Compute Instance (#3217)"
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/resource_policy_placement_policy.tf.erb
  third_party/terraform/resources/resource_compute_instance.go
  third_party/terraform/tests/resource_compute_instance_test.go
  third_party/terraform/tests/resource_compute_resource_policy_test.go
  third_party/terraform/website/docs/r/compute_instance.html.markdown
Labels: cla: yes

#3242 Updated CI documentation.
  .ci/README.md
Labels: cla: yes

#3126 [Terraform] Add support for dns_cache_config to resource_container_cluster
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes, community

#3246 Memorystore Redis connectMode support
  products/redis/api.yaml
  products/redis/terraform.yaml
  templates/terraform/examples/redis_instance_private_service.tf.erb
Labels: cla: yes

#3193 Vcr wrapper
  templates/terraform/operation.go.erb
  third_party/terraform/resources/common_operation_test.go
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/resources/resource_composer_environment.go.erb
  third_party/terraform/tests/resource_composer_environment_test.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/tests/resource_pubsub_topic_test.go
  third_party/terraform/utils/appengine_operation.go
  third_party/terraform/utils/cloudfunctions_operation.go
  third_party/terraform/utils/common_operation.go
  third_party/terraform/utils/composer_operation.go
  third_party/terraform/utils/compute_operation.go
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/container_operation.go
  third_party/terraform/utils/dataproc_cluster_operation.go
  third_party/terraform/utils/dataproc_job_operation.go
  third_party/terraform/utils/deployment_manager_operation.go
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/utils/service_networking_operation.go
  third_party/terraform/utils/serviceman_operation.go
  third_party/terraform/utils/serviceusage_operation.go
  third_party/terraform/utils/sqladmin_operation.go
Labels: cla: yes

#3196 Initial retry transport
  provider/terraform_object_library.rb
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/error_retry_predicates.go
  third_party/terraform/utils/retry_transport.go
  third_party/terraform/utils/retry_transport_test.go
Labels: cla: yes

#3248 Add current status on compute instance
  third_party/terraform/resources/resource_compute_instance.go
Labels: cla: yes, community

#3254 Add podSecurityPolicyConfig to gke cluster
  products/container/api.yaml
Labels: cla: yes

#3252 upgrade_settings is now ga, and O+C
  third_party/terraform/resources/resource_container_node_pool.go.erb
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
Labels: cla: yes

#3247 Serial port datasource
  third_party/terraform/data_sources/data_source_google_compute_instance_serial_port.go
  third_party/terraform/tests/data_source_google_compute_instance_serial_port_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/datasource_compute_instance_serial_port.html.markdown
Labels: cla: yes

#3259 Remove expression to avoid the interpolation-only expressions warning
  third_party/terraform/website/docs/guides/getting_started.html.markdown
Labels: cla: no

#3253 GA ILB global access
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/forwarding_rule_global_internallb.tf.erb
Labels: cla: yes

#3262 Ansible - Sql SSL Cert
  products/sql/ansible.yaml
  products/sql/ansible_version_added.yaml
  products/sql/examples/ansible/ssl_cert.yaml
Labels: cla: yes

#3260 Ansible - External VPN Gateways
  products/compute/ansible.yaml
  products/compute/ansible_version_added.yaml
  products/compute/api.yaml
  products/compute/examples/ansible/external_vpn_gateway.yaml
  products/compute/terraform.yaml
Labels: cla: yes

#3210 Ansible - Regional SSL Certs + Health Check
  products/compute/ansible.yaml
  products/compute/ansible_version_added.yaml
  products/compute/api.yaml
  products/compute/examples/ansible/region_health_check.yaml
  products/compute/examples/ansible/ssl_certificate.yaml
  products/compute/terraform.yaml
  templates/terraform/examples/region_ssl_certificate_basic.tf.erb
  templates/terraform/examples/region_ssl_certificate_random_provider.tf.erb
Labels: cla: yes

#3205 fixed ids for #5542
  templates/terraform/examples/address_with_subnetwork.tf.erb
  templates/terraform/examples/autoscaler_basic.tf.erb
  templates/terraform/examples/autoscaler_single_instance.tf.erb
  templates/terraform/examples/binary_authorization_attestor_kms.tf.erb
  templates/terraform/examples/instance_with_ip.tf.erb
  templates/terraform/examples/region_autoscaler_basic.tf.erb
  third_party/terraform/website/docs/d/datasource_google_compute_backend_service.html.markdown
  third_party/terraform/website/docs/r/cloudfunctions_function.html.markdown
  third_party/terraform/website/docs/r/cloudiot_registry.html.markdown
  third_party/terraform/website/docs/r/composer_environment.html.markdown
  third_party/terraform/website/docs/r/compute_attached_disk.html.markdown
Labels: cla: yes, community

#3263 Force zone for dataproc cluster gpu test
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
Labels: cla: yes

#3266 Update list of random reviewers + welcome message
  .ci/magic-modules/welcome-contributor.sh
Labels: cla: yes

#3264 Ansible - All the Regional Resources
  products/compute/ansible.yaml
  products/compute/ansible_version_added.yaml
  products/compute/api.yaml
  products/compute/examples/ansible/region_autoscaler.yaml
  products/compute/examples/ansible/region_instance_group_manager.yaml
  products/compute/examples/ansible/region_target_http_proxy.yaml
  products/compute/examples/ansible/region_target_https_proxy.yaml
  products/compute/examples/ansible/region_url_map.yaml
  products/compute/terraform.yaml
Labels: cla: yes

#3268 Add serial port ds and region ssl cert to sidebar
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3269 Add google_compute_instance current_status to data source
  third_party/terraform/data_sources/data_source_google_compute_instance.go
  third_party/terraform/tests/data_source_google_compute_instance_test.go
Labels: cla: yes, community

#3236 Add a resource for fine-grained management of named ports
  products/compute/ansible.yaml
  products/compute/api.yaml
  products/compute/inspec.yaml
  products/compute/terraform.yaml
  templates/terraform/encoders/normalize_group.go.erb
  templates/terraform/examples/instance_group_named_port_gke.tf.erb
  templates/terraform/flatten_property_method.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3272 Revert changes to compute image selflink in examples
  templates/terraform/examples/autoscaler_basic.tf.erb
  templates/terraform/examples/autoscaler_single_instance.tf.erb
  templates/terraform/examples/instance_with_ip.tf.erb
  templates/terraform/examples/region_autoscaler_basic.tf.erb
Labels: cla: yes

#3275 Ansible - Resource Policy
  products/compute/ansible.yaml
  products/compute/ansible_version_added.yaml
  products/compute/api.yaml
  products/compute/examples/ansible/resource_policy.yaml
Labels: cla: yes

#3276 Consume original request body from retry transport
  third_party/terraform/utils/retry_transport.go
Labels: cla: yes

#3274 Add pollasync to eventually consistent iap brand
  products/iap/api.yaml
  products/iap/terraform.yaml
  templates/terraform/resource.erb
Labels: cla: yes

#3249 Bumping cloudrun Update timeout
  products/cloudrun/terraform.yaml
Labels: cla: yes

#3279 Removing the license file from third_party file
  spec/copyright_spec.rb
  third_party/terraform/utils/test-fixtures/appengine/hello-world-flask/app.yaml
Labels: cla: yes

#3283 Update test_terraform.sh
  .ci/containers/terraform-tester/test_terraform.sh
Labels: cla: yes

#3270 Allow import of logging_metric in a non-default project.
  products/logging/terraform.yaml
  templates/terraform/custom_import/self_link_as_name.erb
Labels: cla: yes

#3282 Fix lint issues, adding folder IAM
  products/resourcemanager/inspec.yaml
  templates/inspec/iam_binding/iam_binding.erb
  templates/inspec/iam_policy/iam_policy.erb
  templates/inspec/iam_policy/properties/iam_binding_condition.rb
Labels: cla: yes

#3284 compute: subnet IAM conditions
  products/compute/terraform.yaml
  templates/terraform/resource_iam.html.markdown.erb
Labels: cla: yes, enhancement

#3280 Add tfgen to sweepable prefixes
  templates/terraform/sweeper_file.go.erb
  third_party/terraform/tests/resource_app_engine_app_version_sweeper_test.go
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/tests/resource_monitoring_group_test.go
  third_party/terraform/utils/gcp_sweeper_test.go
Labels: cla: yes

#3255 Add retry for `google_kms_crypto_key_version`
  third_party/terraform/data_sources/data_source_google_kms_crypto_key_version.go
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#3287 removing ansible release pipeline
  .ci/release.yml.tmpl
Labels: cla: yes

#3289 GA ILB multi-nic
  products/compute/api.yaml
  third_party/terraform/tests/resource_compute_region_backend_service_test.go.erb
Labels: cla: yes

#3290 Add note to `google_storage_notification` about IAM policy side effects
  third_party/terraform/website/docs/r/storage_notification.html.markdown
Labels: cla: yes

#3291 Access Context Manager: add support for access level condition 'regions'
  products/accesscontextmanager/api.yaml
  templates/terraform/examples/access_context_manager_access_level_basic.tf.erb
  templates/terraform/examples/access_context_manager_service_perimeter_basic.tf.erb
  third_party/terraform/tests/resource_access_context_manager_access_level_test.go.erb
Labels: cla: yes, community

#3288 GA google_container_cluster maintenance policy recurring window
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/utils/validation.go
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3267 Add serviceusage's consumerquotaoverride and adminquotaoverride.
  products/serviceusage/ansible.yaml
  products/serviceusage/api.yaml
  products/serviceusage/inspec.yaml
  products/serviceusage/terraform.yaml
  templates/terraform/examples/consumer_quota_override.tf.erb
  templates/terraform/nested_query.go.erb
  templates/terraform/resource.erb
  third_party/terraform/resources/resource_google_project.go
  third_party/terraform/resources/resource_google_project_service.go
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/provider_handwritten_endpoint.go.erb
  third_party/terraform/utils/serviceusage_operation.go
Labels: cla: yes

#3281 Add resource for enabling firebase
  overrides/terraform/resource_override.rb
  products/firebase/api.yaml
  products/firebase/terraform.yaml
  templates/terraform/examples/base_configs/test_file.go.erb
  templates/terraform/examples/firebase_project_basic.tf.erb
  templates/terraform/resource.erb
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3271 Additional Authenticated Data AAD for Cloud KMS secrets
  products/kms/api.yaml
  products/kms/terraform.yaml
  third_party/terraform/data_sources/data_source_google_kms_secret.go
  third_party/terraform/tests/data_source_google_kms_secret_ciphertext_test.go
  third_party/terraform/tests/data_source_google_kms_secret_test.go
  third_party/terraform/tests/resource_kms_secret_ciphertext_test.go
  third_party/terraform/website/docs/d/google_kms_secret.html.markdown
Labels: cla: yes, community

#3296 ACM: service perimeter's restricted_services as set
  products/accesscontextmanager/terraform.yaml
  third_party/terraform/utils/bootstrap_utils_test.go
Labels: cla: yes, enhancement

#3292 Catch googleapi errors from flattenprop
  templates/terraform/resource.erb
Labels: cla: yes

#3293 Add vcr tests to gke handwritten
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#3294 Add docs on dataproc cluster optional_components
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
Labels: cla: yes

#3298 Validation of the fleet spec changed.
  templates/terraform/examples/game_service_config_basic.tf.erb
Labels: cla: yes

#3297 add google-beta provider to all resources in this test.
  templates/terraform/examples/consumer_quota_override.tf.erb
Labels: cla: yes

#3300 Remove null characters from seed when reading
  third_party/terraform/utils/provider_test.go.erb
Labels: cla: yes

#3299 Do not retry requests without GetBody
  third_party/terraform/utils/retry_transport.go
  third_party/terraform/utils/retry_transport_test.go
Labels: cla: yes

#3302 Add google_service_usage_consumer_quota_override to sidebar
  third_party/terraform/website-compiled/google.erb
Labels: cla: yes

#3304 storage_bucket: explain what happens when multiple conditions are spe…
  third_party/terraform/website/docs/r/storage_bucket.html.markdown
Labels: cla: no

#3191 Adding support for IngressSettings field to cloudfunctions. Also upda…
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
  third_party/terraform/website/docs/d/datasource_cloudfunctions_function.html.markdown
  third_party/terraform/website/docs/r/cloudfunctions_function.html.markdown
Labels: cla: yes, community

#3286 add new project to app engine flex version tests
  products/appengine/api.yaml
  products/appengine/terraform.yaml
  templates/terraform/examples/app_engine_flexible_app_version.tf.erb
  third_party/terraform/tests/resource_app_engine_flexible_app_version_test.go
Labels: cla: yes

#3307 PR feedback
  templates/inspec/examples/google_compute_project_info/google_compute_project_info.erb
  templates/inspec/integration_test_template.erb
  templates/inspec/tests/integration/build/gcp-mm.tf
Labels: cla: yes

#3306 Virtual field for `google_cloud_run_service` revision names
  products/cloudrun/terraform.yaml
  templates/terraform/constants/cloud_run_service.go.erb
  templates/terraform/custom_expand/cloud_run_service_revision_name.erb
  templates/terraform/examples/cloud_run_service_multiple_environment_variables.tf.erb
  templates/terraform/examples/cloud_run_service_sql.tf.erb
  templates/terraform/resource_definition/cloud_run_service.go.erb
Labels: cla: yes

#3303 Add GKE Resource Consumption Metering, promote resource export to GA
  third_party/terraform/resources/resource_container_cluster.go.erb
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#3310 Modify gke vcr testacc check to not panic
  third_party/terraform/tests/resource_container_cluster_test.go.erb
  third_party/terraform/utils/provider_test.go.erb
Labels: cla: yes

#3309 Add missing quotes to example for saving GCP SA key as k8s secret
  third_party/terraform/website/docs/r/google_service_account_key.html.markdown
Labels: cla: no

#3311 Add support for VpcConnectorEgressSettings field to cloudfunctions
  third_party/terraform/resources/resource_cloudfunctions_function.go
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
  third_party/terraform/website/docs/d/datasource_cloudfunctions_function.html.markdown
  third_party/terraform/website/docs/r/cloudfunctions_function.html.markdown
Labels: cla: yes

#3314 Do not return container cluster sweeper errors
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#3316 Do not diffSuppress `port` when `port_specification` is not "USED_FIXED_PORT"
  templates/terraform/constants/health_check.erb
Labels: cla: yes

#3317 Add BQ SA datasource to the sidebar, plus docs and test.
  third_party/terraform/data_sources/data_source_google_bigquery_default_service_account.go
  third_party/terraform/tests/data_source_google_bigquery_default_service_account_test.go
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/d/google_bigquery_default_service_account.html.markdown
Labels: cla: yes

#3308 Support compute reservation resize
  products/compute/api.yaml
  products/compute/terraform.yaml
  templates/terraform/resource.erb
  templates/terraform/update_encoder/reservation.go.erb
  third_party/terraform/tests/resource_compute_reservation_test.go
Labels: cla: yes

#3315 Do not return most sweeper errors
  third_party/terraform/tests/resource_access_context_manager_access_policy_test.go.erb
  third_party/terraform/tests/resource_cloudfunctions_function_test.go.erb
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
Labels: cla: yes

#3318 ACM: service perimeter's vpc_accessible_services
  products/accesscontextmanager/api.yaml
  products/accesscontextmanager/terraform.yaml
  third_party/terraform/tests/resource_access_context_manager_service_perimeter_test.go.erb
Labels: cla: yes, enhancement

#3136 clarify specification of audit log types
  third_party/terraform/website/docs/r/google_project_iam.html.markdown
Labels: cla: yes, community

#3320 Add monitoring uptime check ips datasource
  third_party/terraform/data_sources/data_source_google_monitoring_uptime_check_ips.go
  third_party/terraform/tests/data_source_google_monitoring_uptime_check_ips_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website-compiled/google.erb
  third_party/terraform/website/docs/d/datasource_google_monitoring_uptime_check_ips.html.markdown
Labels: cla: yes

#3305 Add deadLetterPolicy to Pub/Sub Subscription resource
  products/pubsub/api.yaml
  products/pubsub/terraform.yaml
  templates/terraform/examples/pubsub_subscription_dead_letter.tf.erb
Labels: cla: yes, community

#3313 allow google_dns_managed_zone.dnssec_config to be updated
  products/dns/api.yaml
  third_party/terraform/tests/resource_dns_managed_zone_test.go.erb
Labels: cla: yes

#3321 Add game service cluster test
  products/gameservices/terraform.yaml
  templates/terraform/examples/game_service_cluster_basic.tf.erb
Labels: cla: yes

#3323 Fix TestAccDataSourceGoogleMonitoringUptimeCheckIps_basic
  third_party/terraform/tests/data_source_google_monitoring_uptime_check_ips_test.go
Labels: cla: yes

#3322 Make batching documentation match code
  third_party/terraform/website/docs/guides/provider_reference.html.markdown
Labels: cla: yes

#3324 storage bucket IAM diff suppress
  products/storage/api.yaml
  templates/terraform/iam/storage_bucket_diff_suppress.go.erb
Labels: cla: yes
