Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2021-01, with the labels that each got.

#4364 update documentation field on resource monitoring_alert_policy
  products/monitoring/api.yaml
Labels: cla: no

#4288 Remove codelab and references to submodules.
  README.md
Labels: cla: yes

#4365 correct typo in documentation
  third_party/terraform/website/docs/guides/provider_reference.html.markdown
Labels: cla: no

#4359 kms_key_name parameter for google_dataflow_job resource
  third_party/terraform/resources/resource_dataflow_job.go
  third_party/terraform/tests/resource_dataflow_job_test.go
  third_party/terraform/website/docs/r/dataflow_job.html.markdown
Labels: cla: yes

#4366 Delete mm-codelab.png
  images/mm-codelab.png
Labels: cla: yes

#4370 Remove Nathan from random reviewers
  .ci/containers/contributor-checker/check-contributor.sh
Labels: cla: yes

#4346 sync handwritten validator storage bucket with the provider version
  third_party/validator/storage_bucket.go
Labels: cla: yes

#4372 Fix wrong initialization of maintenance_exclusion
  third_party/terraform/resources/resource_container_cluster.go.erb
Labels: cla: yes

#4347 Add diff supress for json comparison on specific keys for bigquery table
  third_party/terraform/resources/resource_bigquery_table.go
  third_party/terraform/tests/resource_bigquery_table_test.go
Labels: cla: yes

#4363 Add support cloudsql mysql 8.0
  products/sql/api.yaml
  templates/terraform/examples/sql_source_representation_instance_basic.tf.erb
  third_party/terraform/resources/resource_sql_database_instance.go.erb
Labels: cla: yes

#4362 Add new data source google_compute_instance_template
  third_party/terraform/data_sources/data_source_google_compute_instance_template.go
  third_party/terraform/tests/data_source_google_compute_instance_template_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/compute_instance_template.html.markdown
Labels: cla: yes

#4369 Updated tgc-test docker container to be built with go 1.14, which is required by terraform-google-conversion
  .ci/containers/terraform-google-conversion-tester/Dockerfile
Labels: cla: yes

#4336 Add restoreBackup support for sql db instance
  third_party/terraform/resources/resource_sql_database_instance.go.erb
  third_party/terraform/tests/resource_sql_database_instance_test.go.erb
  third_party/terraform/website/docs/r/sql_database_instance.html.markdown
Labels: cla: yes

#4367 Sweep vpc connector
  products/vpcaccess/terraform.yaml
Labels: cla: yes

#4378 Update cloud_identity_groups.html.markdown
  third_party/terraform/website/docs/d/cloud_identity_groups.html.markdown
Labels: cla: no

#4374 example corrected in the doc
  third_party/terraform/website/docs/d/sql_database_instance.html.markdown
Labels: cla: yes

#4373 Promote github fields in Cloud Build Trigger to GA
  products/cloudbuild/api.yaml
Labels: cla: yes

#4368 Add support for Context Aware Access UserAccessBinding resource
  products/accesscontextmanager/api.yaml
  products/accesscontextmanager/inspec.yaml
  products/accesscontextmanager/terraform.yaml
  templates/terraform/examples/access_context_manager_gcp_user_access_binding_basic.tf.erb
  templates/terraform/operation.go.erb
  third_party/terraform/tests/resource_access_approval_folder_settings_test.go
  third_party/terraform/tests/resource_access_approval_organization_settings_test.go
  third_party/terraform/tests/resource_access_approval_project_settings_test.go
  third_party/terraform/tests/resource_access_context_manager_access_level_condition_test.go
  third_party/terraform/tests/resource_access_context_manager_access_level_test.go.erb
  third_party/terraform/tests/resource_access_context_manager_access_levels_test.go
  third_party/terraform/tests/resource_access_context_manager_access_policy_test.go.erb
  third_party/terraform/tests/resource_access_context_manager_gcp_user_access_binding_test.go
  third_party/terraform/tests/resource_access_context_manager_service_perimeter_resource_test.go
  third_party/terraform/tests/resource_access_context_manager_service_perimeter_test.go.erb
  third_party/terraform/tests/resource_access_context_manager_services_perimeters_test.go
  third_party/terraform/tests/resource_bigquery_data_transfer_config_test.go
Labels: cla: yes

#4383 Update project to project_id in project access settings
  products/accessapproval/api.yaml
  products/accessapproval/terraform.yaml
  templates/terraform/custom_delete/clear_project_access_approval_settings.go.erb
Labels: cla: yes

#4379 Fix dataproc tests
  third_party/terraform/tests/resource_dataproc_job_test.go
Labels: cla: yes

#4380 Fix api gateway tests
  products/apigateway/terraform.yaml
Labels: cla: yes

#4376 Update Google Projects docs
  third_party/terraform/website/docs/r/google_folder_organization_policy.html.markdown
  third_party/terraform/website/docs/r/google_project.html.markdown
  third_party/terraform/website/docs/r/google_project_default_service_accounts.html.markdown
Labels: cla: yes

#4317 Apigee organization
  products/apigee/api.yaml
  products/apigee/terraform.yaml
  templates/terraform/custom_import/apigee_organization.go.erb
  templates/terraform/encoders/apigee_organization.go.erb
  templates/terraform/examples/apigee_organization_cloud_basic.tf.erb
  templates/terraform/examples/apigee_organization_cloud_basic_test.tf.erb
  templates/terraform/examples/apigee_organization_cloud_full.tf.erb
  templates/terraform/examples/apigee_organization_cloud_full_test.tf.erb
Labels: cla: yes

#4386 Fix subnetwork datasource test
  third_party/terraform/tests/data_source_google_compute_subnetwork_test.go
Labels: cla: yes

#4384 Fix confidential GKE test
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#4387 Use beta provider for backend service cache tests
  products/compute/terraform.yaml
  templates/terraform/examples/backend_service_cache.tf.erb
  templates/terraform/examples/region_backend_service_cache.tf.erb
Labels: cla: yes

#4390 Service account key keepers
  third_party/terraform/resources/resource_google_service_account_key.go
  third_party/terraform/website/docs/r/google_service_account_key.html.markdown
Labels: cla: yes

#4391 Use connection_name in Cloud Run Sql example
  products/cloudrun/terraform.yaml
  templates/terraform/examples/cloud_run_service_sql.tf.erb
Labels: cla: yes

#4389 Depends on breaks old TF version
  templates/terraform/examples/notebook_environment_basic.tf.erb
  third_party/terraform/tests/data_source_storage_bucket_object_content_test.go
  third_party/terraform/tests/resource_compute_instance_migrate_test.go
Labels: cla: yes

#4394 Fix inconsistent locations in some resources - Part II
  products/memcache/api.yaml
  products/memcache/terraform.yaml
  products/tpu/api.yaml
  products/tpu/terraform.yaml
  products/vpcaccess/api.yaml
  products/vpcaccess/terraform.yaml
  templates/terraform/examples/memcache_instance_basic.tf.erb
  templates/terraform/examples/vpc_access_connector.tf.erb
Labels: cla: yes

#4360 Add Cloud Run Locations datasource
  templates/terraform/examples/cloud_run_domain_mapping_basic.tf.erb
  templates/terraform/examples/cloud_run_service_basic.tf.erb
  templates/terraform/examples/cloud_run_service_multiple_environment_variables.tf.erb
  templates/terraform/examples/cloud_run_service_noauth.tf.erb
  templates/terraform/examples/cloud_run_service_sql.tf.erb
  templates/terraform/examples/cloud_run_service_traffic_split.tf.erb
  templates/terraform/examples/region_network_endpoint_group_cloudrun.tf.erb
  third_party/terraform/data_sources/data_source_cloud_run_locations.go
  third_party/terraform/tests/data_source_cloud_run_locations_test.go
  third_party/terraform/tests/data_source_tpu_tensorflow_versions_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/cloud_run_locations.html.markdown
Labels: cla: yes

#4396 Computed, custom flatten for log config
  products/compute/terraform.yaml
  templates/terraform/custom_flatten/health_check_log_config.go.erb
  third_party/terraform/tests/resource_compute_health_check_test.go
Labels: cla: yes

#4398 Fix test expectation
  third_party/terraform/tests/resource_container_cluster_test.go.erb
Labels: cla: yes

#4397 Fix depends_on in test
  third_party/terraform/tests/data_source_google_compute_instance_template_test.go
  third_party/terraform/tests/resource_container_node_pool_test.go.erb
Labels: cla: yes

#4356 Add `X-Goog-Request-Reason` header if environment variable `CLOUDSDK_CORE_REQUEST_REASON` is set
  provider/terraform_object_library.rb
  third_party/terraform/utils/config.go.erb
  third_party/terraform/utils/header_transport.go
  third_party/terraform/utils/provider.go.erb
Labels: cla: yes

#4392 Infer bigtable zone from provider
  third_party/terraform/resources/resource_bigtable_instance.go
  third_party/terraform/tests/resource_bigtable_instance_test.go
  third_party/terraform/utils/provider_test.go.erb
  third_party/terraform/website/docs/r/bigtable_gc_policy.html.markdown
  third_party/terraform/website/docs/r/bigtable_instance.html.markdown
Labels: cla: yes

#4377 Fix inconsistent locations in some resources
  products/compute/terraform.yaml
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
  third_party/terraform/tests/resource_compute_per_instance_config_test.go
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go
  third_party/terraform/tests/resource_compute_region_per_instance_config_test.go
  third_party/terraform/website/docs/r/compute_instance.html.markdown
  third_party/terraform/website/docs/r/compute_region_instance_group_manager.html.markdown
Labels: cla: yes

#4388 Ignore members with "deleted:" prefix in bigquery IAM member
  third_party/terraform/utils/iam_bigquery_dataset.go
Labels: cla: yes

#4400 bigquery_table - add customized diff for specific properties and changes on schema
  third_party/terraform/resources/resource_bigquery_table.go
  third_party/terraform/tests/resource_bigquery_table_test.go
  third_party/terraform/utils/test_utils.go
  third_party/terraform/utils/utils.go.erb
Labels: cla: no

#4382 Add Certificate Authority Resource (Certificate Authority Service)
  products/privateca/api.yaml
  products/privateca/terraform.yaml
  templates/terraform/custom_check_destroy/privateca_certificate_authority.go.erb
  templates/terraform/examples/privateca_certificate_authority_basic.tf.erb
  templates/terraform/examples/privateca_certificate_authority_full.tf.erb
  templates/terraform/pre_delete/privateca_certificate_authority.go.erb
Labels: cla: yes

#4401 Add requested policy version to folder IAM GET
  products/apigee/terraform.yaml
  third_party/terraform/tests/resource_google_folder_iam_member_test.go
  third_party/terraform/utils/iam_folder.go
Labels: cla: yes

#4406 Generated iam policy updaters for terraform-google-conversion
  provider/terraform_object_library.rb
Labels: cla: yes

#4357 Add Autoscaler scaling schedules
  products/compute/api.yaml
  third_party/terraform/tests/resource_compute_autoscaler_test.go.erb
  third_party/terraform/tests/resource_compute_region_autoscaler_test.go.erb
Labels: cla: yes

#4403 set ignore_read for noRemoveDataDisk
  products/notebooks/terraform.yaml
Labels: cla: yes

#4404 Fix TestAccLoggingBucketConfig_CreateBuckets_withCustomId
  third_party/terraform/tests/resource_logging_bucket_config_test.go
Labels: cla: yes

#4409 Support cloud scheduler update
  products/cloudscheduler/api.yaml
Labels: cla: yes

#4407 Misc improvements for Certificate Authority
  products/privateca/api.yaml
  products/privateca/terraform.yaml
  templates/terraform/constants/certificate_authority.go.erb
  templates/terraform/encoders/certificate_authority.go.erb
  templates/terraform/examples/privateca_certificate_authority_basic.tf.erb
  templates/terraform/examples/privateca_certificate_authority_cmek.tf.erb
  templates/terraform/examples/privateca_certificate_authority_full.tf.erb
  templates/terraform/iam/example_config_body/privateca_certificate_authority.tf.erb
  templates/terraform/pre_delete/privateca_certificate_authority.go.erb
Labels: cla: yes, enhancement

#4411 Fix broken link
  products/cloudbuild/api.yaml
Labels: cla: yes

#4413 Revert "Generated iam policy updaters for terraform-google-conversion"
  provider/terraform_object_library.rb
Labels: cla: yes

#4412 add retry logic on healthcare dataset not initialized error
  products/healthcare/terraform.yaml
  third_party/terraform/utils/error_retry_predicates.go
Labels: cla: yes

#4414 Revert "Revert "Generated iam policy updaters for terraform-google-conversion""
  provider/terraform_object_library.rb
Labels: cla: yes

#4417 Mark test as beta only, make into erb
  third_party/terraform/tests/resource_compute_health_check_test.go.erb
Labels: cla: yes

#4405 fix diff on currency_code in google_billing_budget
  products/billingbudget/terraform.yaml
  third_party/terraform/tests/resource_billing_budget_test.go
Labels: cla: yes

#4408 Add RuntimeConfig datasource
  third_party/terraform/data_sources/data_source_redis_instance.go
  third_party/terraform/data_sources/data_source_runtimeconfig_config.go
  third_party/terraform/tests/data_source_redis_instance_test.go
  third_party/terraform/tests/data_source_runtimeconfig_config_test.go
  third_party/terraform/utils/provider.go.erb
  third_party/terraform/website/docs/d/cloud_run_service.html.markdown
  third_party/terraform/website/docs/d/runtimeconfig_config.html.markdown
  third_party/terraform/website/docs/r/runtimeconfig_config.html.markdown
Labels: cla: yes

#4420 Added copying of handwritten iam updater files
  provider/terraform_object_library.rb
Labels: cla: yes

#4375 Add temp_bucket parameter for resource google_dataproc_cluster (#7927)
  third_party/terraform/resources/resource_dataproc_cluster.go.erb
  third_party/terraform/tests/resource_dataproc_cluster_test.go.erb
  third_party/terraform/website/docs/r/dataproc_cluster.html.markdown
Labels: cla: no

#4348 Add support for capacity aware modes to `google_compute_region_instance_group_manager
  third_party/terraform/resources/resource_compute_region_instance_group_manager.go
  third_party/terraform/tests/resource_compute_region_instance_group_manager_test.go
  third_party/terraform/website/docs/r/compute_region_instance_group_manager.html.markdown
Labels: cla: yes

#4423 CI updates after folder move
  .ci/containers/downstream-builder/Dockerfile
  .ci/containers/downstream-builder/generate_downstream.sh
  .ci/gcb-run-rake-tests.yml
Labels: cla: yes

#4427 Add mmv1/ to readme links
  README.md
Labels: cla: yes

#4426 Made iam updaters accept TerraformResourceData interface
  mmv1/templates/terraform/iam_policy.go.erb
  mmv1/third_party/terraform/utils/iam.go.erb
  mmv1/third_party/terraform/utils/iam_bigquery_dataset.go
  mmv1/third_party/terraform/utils/iam_bigtable_instance.go
  mmv1/third_party/terraform/utils/iam_bigtable_table.go
  mmv1/third_party/terraform/utils/iam_billing_account.go
  mmv1/third_party/terraform/utils/iam_dataproc_cluster.go
  mmv1/third_party/terraform/utils/iam_dataproc_job.go
  mmv1/third_party/terraform/utils/iam_folder.go
  mmv1/third_party/terraform/utils/iam_healthcare_dataset.go
  mmv1/third_party/terraform/utils/iam_healthcare_dicom_store.go
  mmv1/third_party/terraform/utils/iam_healthcare_fhir_store.go
  mmv1/third_party/terraform/utils/iam_healthcare_hl7_v2_store.go
  mmv1/third_party/terraform/utils/iam_kms_crypto_key.go.erb
  mmv1/third_party/terraform/utils/iam_kms_key_ring.go.erb
  mmv1/third_party/terraform/utils/iam_organization.go
  mmv1/third_party/terraform/utils/iam_project.go
  mmv1/third_party/terraform/utils/iam_pubsub_subscription.go
  mmv1/third_party/terraform/utils/iam_service_account.go.erb
  mmv1/third_party/terraform/utils/iam_spanner_database.go
  mmv1/third_party/terraform/utils/iam_spanner_instance.go
  mmv1/third_party/terraform/utils/regional_utils.go
  mmv1/third_party/terraform/utils/test_utils.go
  mmv1/third_party/terraform/utils/utils.go.erb
Labels: cla: yes

#4395 authorized_network set as a computed field
  mmv1/products/memcache/terraform.yaml
Labels: cla: yes

#4425 v1 Updates: Add tags, serviceAccountScopes, V100 GPU, ShieldedInstanc…
  mmv1/products/notebooks/api.yaml
  mmv1/products/notebooks/terraform.yaml
Labels: cla: yes

#4424 add fingerprint for privateIpv6GoogleAccess
  mmv1/products/compute/api.yaml
Labels: cla: yes

#4428 Implemented a simple PascalCase function to remove strcase dependency
  mmv1/third_party/terraform/resources/resource_compute_instance_from_machine_image.go.erb
  mmv1/third_party/terraform/resources/resource_compute_instance_from_template.go
  mmv1/third_party/terraform/utils/utils.go.erb
  mmv1/third_party/terraform/utils/utils_test.go
Labels: cla: yes

#4419 fix permadiff on expiration_ms for google_bigquery_table
  mmv1/third_party/terraform/resources/resource_bigquery_table.go
Labels: cla: yes

#4416 fix two tests for cloud_run_service
  mmv1/products/cloudrun/api.yaml
  mmv1/templates/terraform/examples/cloud_run_service_multiple_environment_variables.tf.erb
  mmv1/third_party/terraform/tests/resource_cloud_run_service_test.go
Labels: cla: yes

#4432 Promote datapath and some networking fields of GKE to GA.
  mmv1/third_party/terraform/resources/resource_container_cluster.go.erb
  mmv1/third_party/terraform/tests/resource_container_cluster_test.go.erb
  mmv1/third_party/terraform/website/docs/r/container_cluster.html.markdown
Labels: cla: yes

#4338 Validate base64 fields in the Google Provider
  mmv1/products/apigateway/terraform.yaml
  mmv1/products/cloudscheduler/api.yaml
  mmv1/products/cloudscheduler/terraform.yaml
  mmv1/products/healthcare/terraform.yaml
  mmv1/products/kms/terraform.yaml
  mmv1/third_party/terraform/utils/validation.go
Labels: cla: yes

#4434 Add correct signer and viewer roles for private CA
  mmv1/templates/terraform/examples/privateca_certificate_authority_cmek.tf.erb
Labels: cla: yes

#4399 doc updated to match examples for google_billing_budget
  mmv1/products/billingbudget/api.yaml
Labels: cla: yes

#4439 Fix inspec-gcp #302 - incorrect parsing of Memcached discoveryEndpoint property
  mmv1/products/memcache/api.yaml
Labels: cla: yes

#4435 Fix time_rotating argument name
  mmv1/third_party/terraform/website/docs/r/google_service_account_key.html.markdown
Labels: cla: no

#4440 sort array of schema for bigquery_table
  mmv1/third_party/terraform/resources/resource_bigquery_table.go
  mmv1/third_party/terraform/tests/resource_bigquery_table_test.go
Labels: cla: yes

#4445 Remove qualifier about # of supported projects in billing budget
  mmv1/products/billingbudget/api.yaml
Labels: cla: yes

#4442 Add SSH Metadata Key Entry Example
  mmv1/third_party/terraform/website/docs/r/compute_project_metadata.html.markdown
Labels: cla: yes

#4446 Remove validation on data.google_service_account account_id
  mmv1/third_party/terraform/data_sources/data_source_google_service_account.go
  mmv1/third_party/terraform/website/docs/d/service_account.html.markdown
Labels: cla: no

#4447 Minor: wording cleanup in Using GKE with Terraform
  mmv1/third_party/terraform/website/docs/guides/using_gke_with_terraform.html.markdown
Labels: cla: no
