Repository GoogleCloudPlatform/magic-modules, pull requests merged in 2023-08, with the labels that each got.

#8267 adding user_ip_request_headers support to compute_security_policy
  mmv1/third_party/terraform/services/compute/resource_compute_security_policy.go.erb
  mmv1/third_party/terraform/services/compute/resource_compute_security_policy_test.go.erb
  mmv1/third_party/terraform/website/docs/r/compute_security_policy.html.markdown
Labels: awaiting-approval

#8573 Make routineType required in the BigQuery Routine resource
  mmv1/products/bigquery/Routine.yaml
Labels: override-breaking-change

#8531 remove deprecated fields
  mmv1/products/privateca/Certificate.yaml
Labels: override-breaking-change

#8635 feat: add resource for dataform repository workflow config
  mmv1/products/dataform/WorkflowConfig.yaml
  mmv1/templates/terraform/examples/dataform_repository_workflow_config.tf.erb
Labels: awaiting-approval

#8669 Remove Terraform support for game services
  .ci/infra/terraform/main.tf
  mmv1/products/gameservices/GameServerCluster.yaml
  mmv1/products/gameservices/GameServerConfig.yaml
  mmv1/products/gameservices/GameServerDeployment.yaml
  mmv1/products/gameservices/GameServerDeploymentRollout.yaml
  mmv1/products/gameservices/Realm.yaml
  mmv1/products/gameservices/product.yaml
  mmv1/templates/terraform/custom_create/gameservice_rollout_create.go
  mmv1/templates/terraform/examples/game_service_cluster_basic.tf.erb
  mmv1/templates/terraform/examples/game_service_config_basic.tf.erb
  mmv1/templates/terraform/examples/game_service_deployment_basic.tf.erb
  mmv1/templates/terraform/examples/game_service_deployment_rollout_basic.tf.erb
  mmv1/templates/terraform/examples/game_service_realm_basic.tf.erb
  mmv1/third_party/terraform/provider/provider.go.erb
  mmv1/third_party/terraform/services/gameservices/data_source_google_game_services_game_server_deployment_rollout.go
  mmv1/third_party/terraform/website/docs/d/game_services_game_server_deployment_rollout.html.markdown
Labels: override-breaking-change

#8776 Removed MembershipRBACRoleBinding from ga provider
  mmv1/products/gkehub2/MembershipRBACRoleBinding.yaml
  mmv1/templates/terraform/examples/gkehub_membership_rbac_role_binding_basic.tf.erb
Labels: override-breaking-change

#8790 Switched biglake database to use parent field implementation
  mmv1/products/biglake/Database.yaml
  mmv1/templates/terraform/examples/biglake_database.tf.erb
  mmv1/third_party/terraform/services/biglake/resource_biglake_database_test.go
Labels: override-breaking-change

#8118 Make SQL database flags a set
  mmv1/third_party/terraform/services/sql/resource_sql_database_instance.go.erb
  mmv1/third_party/terraform/services/sql/resource_sql_database_instance_test.go
  mmv1/third_party/tgc/sql_database_instance.go
Labels: terraform-5.0
